import { frame } from "../grid";
import type { SpriteDef } from "../textures";
import type { BossId } from "../../ids";

// Task 14 — The Glitch Toad, 48x64. A giant corrupted toad-beetle-mushroom:
// a green mushroom cap (G outer dome / g gill underside) sits on its back like
// a shell, over a bloated dark beetle body (k, with a D shell-seam for volume
// and a dotted thorax line above the legs). Two big white eyes (W/O) read cute
// at rest; the closed mouth is a thin toothy grin (X/W) until it cracks open
// into a corrupted X/R/W maw for its attacks — cute-menacing, matching the
// Bugling's mushroom-cap-beetle motif (art/sprites/enemies1.ts) scaled up to
// boss size. R/r glitch patches fleck the cap and belly, plus a thin
// mid-frame glitch slice line, selling the "corrupted" theme. Four stubby
// G/g legs plant it on the arena floor.
//
// Anims: idle (2f, breathing/glitch-shift), attack (2f, maw cracks open wide
// with a jagged corrupted tongue -- the lunge telegraphed by "player-hit" fx),
// hurt (1f, wide eyes + cracks -- "boss-hit" fx), defeat (3f, a dissolve from
// buckling legs -> crumbling body -> a sparse fading remnant that CombatBackdropScene
// holds on the last frame after "combat:over" victory).

const IDLE_0 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGrrGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGrrGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGrrGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........ggggggggggggggggggggggggggggg..........
  ...........kkkkkkkkkkkkkkkkkkkkkkkkkk...........
  ............kkkRkkkkRkkkkRkkkkRkkkkR............
  .............kkkkkkkkkkkkkkkkkkkkkk.............
  ............WWWWkkkkkkkkkkkkkkkkWWWW............
  ...........WWWWWWkkkkkkkkkkkkkkWWWWWW...........
  ..........WWWWWWWWkkkkkkkkkkkkWWWWWWWW..........
  ..........WWWOOWWWkkkkkkkkkkkkWWWOOWWW..........
  ..........WWWOOWWWkkkkkkkkkkkkWWWOOWWW..........
  .........kWWWWWWWWkkkkkkkkkkkkWWWWWWWWk.........
  ........kkDWWWWWWkkkkkkkkkkkkkkWWWWWWkkk........
  .......kkDDkWWWWkkkkkkkkkkkkkkkkWWWWkkkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kDDXXWXXXWXXXWXXXWXXXWXXXWXXXWXXXWXXkkkk....
  ...kkDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkkkkk...
  ...kkDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkkkkk...
  ...kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkRRRkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkRRRkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkDkDkDkDkDkDkrrDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkkkkkkkkkkkkkkkkrrkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgkkkGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  .......GGGGGGGkkkkkkkkkkkGGGGGGkkkkkkkkk........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......gggggggkkGGGGGGkkkggggggkkGGGGGGG........
  .......gggggggkkggggggkkkggggggkkggggggg........
  .......ggggggg..ggggggkkkgggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  ................................................
`);

// idle f1: cap flecks drift, teeth-grin narrows a hair, legs shift weight,
// a fresh pair of belly flecks -- the quiet "breathing" glitch-shift.
const IDLE_1 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............rGGGGGGGGGGGGGGGGGGGGG.............
  ............rrGGGGGGGGGGGGRRRGGGGGGG............
  ...........GGGGGGGGGGGGGGGRRRGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........ggggggggggggggggggggggggggggg..........
  ...........kkkkkkkkkkkkkkkkkkkkkkkkkk...........
  ............kkkkkkkkkkkkkkkkkkkkkkkk............
  .............kkrkkkkrkkkkrkkkkrkkkk.............
  ............WWWWkkkkkkkkkkkkkkkkWWWW............
  ...........WWWWWWkkkkkkkkkkkkkkWWWWWW...........
  ..........WWWWWWWWkkkkkkkkkkkkWWWWWWWW..........
  ..........WWWOOWWWkkkkkkkkkkkkWWWOOWWW..........
  ..........WWWOOWWWkkkkkkkkkkkkWWWOOWWW..........
  .........kWWWWWWWWkkkkkkkkkkkkWWWWWWWWk.........
  ........kkDWWWWWWkkkkkkkkkkkkkkWWWWWWkkk........
  .......kkDDkWWWWkkkkkkkkkkkkkkkkWWWWkkkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ...kkDDXXWXXXXWXXXXWXXXXWXXXXWXXXXWXXXXXkkkkk...
  ...kkDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkkkkk...
  ...kDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkkkk...
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkrrkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkrrDkDkDkDkDkDkDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgkkkGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  ........kkkkkkkkGGGGGGkkkkkkkkkkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkggggggkkkGGGGGGkkggggggg........
  .......gggggggkkggggggkkkggggggkkggggggg........
  .......ggggggg..ggggggkkkgggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  ................................................
`);

// attack f0: eyes narrow to angry slits, the grin cracks halfway open.
const ATTACK_0 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............rGGGGGGGGGGGGGGGGGGGGG.............
  ............rrGGGGGGGGGGGGRRRGGGGGGG............
  ...........GGGGGGGGGGGGGGGRRRGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........ggggggggggggggggggggggggggggg..........
  ...........kkkkkkkkkkkkkkkkkkkkkkkkkk...........
  ............kkkkkkkkkkkkkkkkkkkkkkkk............
  .............kkkkkkkkkkkkkkkkkkkkkk.............
  ............WWWWkkkkkkkkkkkkkkkkWWWW............
  ...........WWWWWWkkkRkkkRkkkRkkWWWWWW...........
  ..........WWWWWWWWkkkkkkkkkkkkWWWWWWWW..........
  ..........WOOOOOOWkkkkkkkkkkkkWOOOOOOW..........
  ..........WOOOOOOWkkkkkkkkkkkkWOOOOOOW..........
  .........kWWWWWWWWkkkkkkkkkkkkWWWWWWWWk.........
  ........kkDWWWWWWkkkkkkkkkkkkkkWWWWWWkkk........
  .......kkDDkWWWWkkkkkkkkkkkkkkkkWWWWkkkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkk.....
  ....kkDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk....
  ....kDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkk....
  ...kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk...
  ...kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk...
  ...kDXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkk...
  ..kkDXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkrrkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkrrDkDkDkDkDkDkDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgkkkGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  .......GGGGGGGkkkkkkkkkkkGGGGGGkkkkkkkkk........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......gggggggkkGGGGGGkkkggggggkkGGGGGGG........
  .......gggggggkkggggggkkkggggggkkggggggg........
  .......ggggggg..ggggggkkkgggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  ................................................
`);

// attack f1: the maw gapes at full width, a jagged corrupted tongue (Data
// Lick) lashes out below it -- the telegraphed lunge, played on "player-hit".
const ATTACK_1 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGrrGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGrrGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGrrGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........ggggggggggggggggggggggggggggg..........
  ...........krkkkrkkkrkkkrkkkrkkkrkkkr...........
  ............kkkkkkkkkkkkkkkkkkkkkkkk............
  .............kkkkkkkkkkkkkkkkkkkkkk.............
  ............WWWWkkkkkkkkkkkkkkkkWWWW............
  ...........WWWWWWkkkkkkkkkkkkkkWWWWWW...........
  ..........WWWWWWWWkkkkkkkkkkkkWWWWWWWW..........
  ..........WOOOOOOWkkkkkkkkkkkkWOOOOOOW..........
  ..........WOOOOOOWkkkkkkkkkkkkWOOOOOOW..........
  .........kWWWWWWWWkkkkkkkkkkkkWWWWWWWWk.........
  ........kkDWWWWWWkkkkkkkkkkkkkkWWWWWWkkk........
  .......kkDDkWWWWkkkkkkkkkkkkkkkkWWWWkkkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkk.....
  ....kkDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk....
  ....kDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkk....
  ...kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk...
  ...kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk...
  ...kDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkk...
  ..kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk..
  ..kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk..
  ..kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk..
  ..kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk..
  ..kDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkk..
  ..kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk..
  ..kkDXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk..
  ..kkDXXXWXXWXXRRRWXXWXXWXXWXXWXXWXXWXXWXXXkkkk..
  ..kkDDkkkkkkkkRRRkkkkkkkrRRrRkkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkkkkkkkRRrRRkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkDkDkrRRrRkDkrrDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkkkkkkkkRRrRRkkkrrkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkkkkkkkkkRRrRRkkkkkkkkkkkkkkk....
  ....kkDDkkkkkkkkkkkkkkkkRrRRrkkkkkkkkkkkkkkk....
  .....kDDkkkkkkkkkkkkkrRRrRRrkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkRRrRRrRkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgrRRGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  ........kkkkkkkkGGGGGGkkkkkkkkkkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkggggggkkkGGGGGGkkggggggg........
  .......gggggggkkggggggkkkggggggkkggggggg........
  .......ggggggg..ggggggkkkgggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  ................................................
`);

// hurt: a scatter of bright flash pixels flare across the shell, eyes go wide
// and startled, red cracks web the cap/body -- the "boss-hit" reaction.
const HURT_0 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........ggggggggggRggggggggggggggggggg.........
  ........ggggggggggggRggggggggggggggggggg........
  ........gggggggggggggRgggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........gggRggggggggggggggggggggggggg..........
  ...........kkRkkkkkkkkkkkkdkkkkkkkkkk...........
  ............kkkkkkkkkkkkkdkkkkkdkkkk............
  .............kkdkkkkkkkkkkkkkkkkkRk.............
  ............WWWWkkkkkkkkkkkkkkkkWWRW............
  ...........WWWWWWkkkkkkkkkkkkkkWWWWWW...........
  ..........WWWOWWWWkkkkkkkkkkkkWWWOWWWW..........
  ..........WWWOWWWWkkkkkkkkkkkkWWWOWWWW..........
  ..........WWWWWWWWkkkkkkkkkkkkWWWWWWWW..........
  .........kWWWWWWWWkkkkkkkkkkkkWWWWWWWWk.........
  ........kkDWWWWWWkkkdkkkkkkkkkkWWWWWWkkk........
  .......kkDDkWWWWkkkkdkkkkkkkkkkkWWWWkkkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkk.....
  ....kkDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk....
  ....kDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkk....
  ...kdDXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXXkkkk...
  ...kkDXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXXkkkk...
  ...kDDkkkkkkkkkkkkkkkkkkkdkkkkkkkkkkkkkkkkkkk...
  ..kkDDkkdkkkkkkkkkkkkkdkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkdkkkkkkkkkkkkkkkkkkkkkkkkdkkkkkkkdkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkdkkkkkkkkkkkkkkdkkkk..
  ..kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDdkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkRkdkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkkkkkdkkkkkRkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkDkDkDkDkDkDRDkDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkRkkkkkkkkkkkkkkkdkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkRkkkkkkkkkkkkkkkkkkkkkkkkkkd....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkd....
  .....kDDkkkkkkkkdkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgkkkGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  .......GGGGGGGkkkkkkkkkkkGGGGGGkkkkkkkkk........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......gggggggkkGGGGGGkkkggggggkkGGGGGGG........
  .......gggggggkkggggggkkkggggggkkggggggg........
  .......ggggggg..ggggggkkkgggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  ................................................
`);

// defeat f0: eyes go X, cracks web the shell, the outer leg pair buckles --
// the toad still mostly whole, but visibly failing.
const DEFEAT_0 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........ggggggggggXggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........gggXggggggggggggggggggggggggg..........
  ...........kkkkkkkkkkkkkkkkkkkkkkkkkk...........
  ............kkkkkkkkkkkkkkkkkkkkkkkk............
  .............kkkkkkkkkkkkkkkkkkkkXk.............
  ..........X....kkXkkkkkkkkkkkkXkk....X..........
  ...........X....XkkkkkkkkkkkkkkX....X...........
  ............X.kXkkkkkkkkkkkkkkkkXk.X............
  ............kXXDkkkkkkkkkkkkkkkkkXXk............
  ...........kDXXkkkkkkkkkkkkkkkkkkXXkk...........
  .........kkDXkkXkkkkkkkkkkkkkkkkXkkXkkk.........
  ........kkDXkkkkXkkkkkkkkkkkkkkXkkkkXkkk........
  .......kkDXkkkkkkXkkkkkkkkkkkkXkkkkkkXkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkXkkkkkkkkkkkkkkkkk......
  .....kDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkk.....
  ....kkDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk....
  ....kDXXXXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXXkkk....
  ...kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkXkkkkkkkkk..
  ..kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkXkkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkDkDkDkDkDkDkDkDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkXkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgkkkGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  .............GkkkkkkkkkkkGGGGGGkkk..............
  .............GkkGGGGGGkkkGGGGGGkkG..............
  .............GkkGGGGGGkkkGGGGGGkkG..............
  .............gkkGGGGGGkkkggggggkkG..............
  .............gkkggggggkkkggggggkkg..............
  .............g..ggggggkkkgggggg..g..............
  .............g..gggggg...gggggg..g..............
  .............g..gggggg...gggggg..g..............
  ................................................
`);

// defeat f1: legs and underbelly gone outright, the chest crumbles into
// scattered glitch motes -- the corruption is consuming it.
const DEFEAT_1 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........ggggggggggggggggggggggggggggg..........
  ...........kkkkkkkkkkkkkkkkkkkkkkkkkk...........
  ............kkkkkkkkkkkkkkkkkkkkkkkk............
  .............kkkkkkkkkkkkkkkkkkkkkk.............
  ..........X....kkXkkkkkkkkkkkkXkk....X..........
  ...........X....XkkkkkkkkkkkkkkX....X...........
  ............X.kXkkkkkkkkkkkkkkkkXk.X............
  ............kXXDkkkkkkkkkkkkkkkkkXXk............
  ...........kDXXkkkkkkkkkkkkkkkkkkXXkk...........
  .........kkDXkkXkkkkkkkkkkkkkkkkXkkXkkk.........
  ........kkDXkkkkXkkkkkkkkkkkkkkXkkkkXkkk........
  .......kkDXkkkkkkXkkkkkkkkkkkkXkkkkkkXkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .......D.k..kkkX.kk....kRkrk.rk.kkkkkk.k.r......
  .....RDDXk...kX.k..k.kkR.k.k.kXk......Rk..k.....
  ....k.D..k.R.kkkrk.kr.kkkk.k.kk....k..k.........
  .....DD.k.k.....rkk.k...k.Rkkk.k...kk.k.kk......
  ....RDDkk....k.kk...krkkkrR..krkkk.kk...r.k.....
  ...kR.....kkkkr.kk.Xkkk.k.k.....k.kkk.kkkrkX....
  ....XD..Xkk.k.R.k.k.k.kk..k.rkk.kkk..k.kk.k.k...
  ..k.XDk.k.kk.kk.r...k....k.X.......Rk..kkkk.....
  ...r..kkkk..kk.k.Rk.Xk.kXk.k..k..k.rk..kk.k.k...
  ..kk.Dkkkkkk.kk..k...kk.k..kk.kkkRRR.kk....kkr..
  ..r.D.kkkRk.k..kkkk.kr.kk..k.kkkkkkkkk..kR..kk..
  .....k.XX..Xkkk.kk.k.k....k..k.k.kk...k.k.kkXk..
  ...k.Dk.kX..kkkkkk...k.k.k.kkkk.Xk.kk...kk.k....
  .....D.rk.k.kkXr.k..kkkkRXkRkk.k.rk......k..kk..
  ..k.D...kr.k..krk.k..k..k....kk.kkRkkk..kk..kk..
  ...kD.kRXkk.kXR....r..k.kkk.k.k....k.kk.Rrkk....
  ...kDDk..k.kkX..k.kXR.kkkkkk.kkkkkk.k..kkX.k....
  ...kD.D...DXDRrR..Dk.k....D.D.DkrRDkD..k....X...
  ....k..kk..k.kkkkXk..k......Rrk.kk.k.r.Xkk......
  ....R.R.k..k..k.k.kkkk.kk.kRkrkXk.k.k.k..k......
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
`);

// defeat f2 (held): only the cap and hollow X eyes remain, trailing a thin
// scatter of fading motes -- CombatBackdropScene holds this frame after the
// dissolve anim finishes, so it stays crisp and legible under the victory panel.
const DEFEAT_2 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........Rg.g....ggggg..gggg...gg...gg..........
  ...........k.rkkkk.kkkk..kkkkk..kkkkk...........
  ............k.k..r.k.kkkrkkk.kkkkXkk............
  ..............kkkk.kkkkkkkkRkXk.kkk.............
  ..........X....kkXkkkkkkkkkkkkXkk....X..........
  ...........X....XkkkkkkkkkkkkkkX....X...........
  ............X.kXkkkkkkkkkkkkkkkkXk.X............
  ............kXXDkkkkkkkkkkkkkkkkkXXk............
  ...........kDXXkkkkkkkkkkkkkkkkkkXXkk...........
  .........kkDXkkXkkkkkkkkkkkkkkkkXkkXkkk.........
  ........kkDXkkkkXkkkkkkkkkkkkkkXkkkkXkkk........
  .......kkDXkkkkkkXkkkkkkkkkkkkXkkkkkkXkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkRkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkrkkkkkkkkkk....
  ................................................
  ................................................
  ....................R...........................
  ...............................r................
  ................................................
  ..........................r.....................
  ................................................
  ................................................
  .................R..............................
  ................................................
  ................................................
  .......................R........................
  ................................................
  ................................................
  .............................r..................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
`);

export const GLITCH_TOAD_SPRITES: SpriteDef = {
  key: "boss-glitch-toad",
  w: 48,
  h: 64,
  frames: [IDLE_0, IDLE_1, ATTACK_0, ATTACK_1, HURT_0, DEFEAT_0, DEFEAT_1, DEFEAT_2],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 3, repeat: -1 },
    { key: "attack", frames: [2, 3], frameRate: 8, repeat: 0 },
    { key: "hurt", frames: [4], frameRate: 1, repeat: 0 },
    { key: "defeat", frames: [5, 6, 7], frameRate: 6, repeat: 0 },
  ],
};

// Task: Captain Spoof, 48x64 -- a phishing pirate captain. Tricorne hat (K/y/Y),
// a smug grin (H/W) under harbor-teal coat (t/T) over a ruffled W/C shirt,
// and a gold hook hand (Y/y) standing in for the "phishing hook". Same size
// class as the Glitch Toad, filling most of the 48x64 canvas.

// Captain Spoof idle f0: standing smug, hook resting at his side.
const SPOOF_IDLE_0 = frame(`
  ................................................
  ................................................
  ......................yyyy......................
  .....................yKKKKy.....................
  ....................yKKKKKKy....................
  ...................yKKKKKKKKy...................
  ..................yyyyyyyyyyyy..................
  .................YYYYYYYYYYYYYY.................
  ..............yyyyyyyyyyyyyyyyyyyy..............
  ........yyyyyyKKKKKKKKKKKKKKKKKKKKyyyyyy........
  ....yyyyKKKKKKKKKKKKKKyyyyKKKKKKKKKKKKKKyyyy....
  ...yKKKKKKKKKKKKKKKKKyYYYYyKKKKKKKKKKKKKKKKKy...
  ....yyyKKKKKKKKKKKKKKyYyyYyKKKKKKKKKKKKKKyyy....
  .......yyyyyKKKKKKKKKKyyyyKKKKKKKKKKyyyyy.......
  ............yyyyyyyyyyyyyyyyyyyyyyyy............
  ...............ssssssssssssssssss...............
  ...............ssssssssssssssssss...............
  ...............ssssssssssssssssss...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............sSSKKKKSSSSKKKKSSs...............
  ...............sSSSSSSSSSSSSSSHss...............
  ...............sSHWWWWWWWWWWWWHSs...............
  ...............sSHHHHHHHHHHHHHHSs...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............ssssssssssssssssss...............
  .................ssssssssssssss.................
  ................................................
  .........YYYYttttttttttttttttttttttYYYY.........
  .........YYYYttttttttttttttttttttttYtttttt......
  .........ttTTTttttttWCCCCCCWttttttTTtttttt......
  .......TTttTTTttttttWCCCCCCWttttttTTtttttt......
  .......TTttTTTttttttWCCCCCCWttttttTTtttttt......
  .......TTttTTTttttttWCCCCCCWttttttTTTtTTT.......
  .......TTttTTTttttttWCCCCCCWttttttTTTtTTT.......
  .......TTttTTTtYWWYtWCCCCCCWttttttTTTtTTT.......
  .......TTttTTTtWyyWtWCCCCCCWttttttTTTtTTT.......
  .......TTttTTTtWWWWtWCCCCCCWttttttTTTtTTT.......
  .......TTttTTTttttttWCCCCCCWttttttTTTtTTT.......
  ......ttttttTTttttttWCCCCCCWttttttTTTtTTT.......
  ......tsssstTTttttttWCCCCCCWttttttTTTtTTT.......
  ......tsssstTTttttttWCCCCCCWttttttTTTtTTT.......
  ......tsssstTTttttttWCCCCCCWttttttTTTtTTT.......
  ......ttttttTTttttttWCCCCCCWttttttTTTtTTT.......
  ......ttttttTTttttttWCCCCCCWttttttTTTWWWW.......
  ..........tTTTttttttWCCCCCCWttttttTTTWWWW.......
  ..........tTTTttttttttttttttttttttTTTWWWW.......
  .........TTTttttttttttttttttttttttttTYTy........
  .........TTTttttttttttttttttttttttttTTY.y.......
  .........TTTttttttttt......tttttttttTTTY........
  .........TTTttttttttt......tttttttttTTT.........
  .........tttttttttttt......tttttttttttt.........
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  .............kkkkkkkkkk..kkkkkkkkkk.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
`);

// idle f1: a breathing/sway shift -- coat leans a hair, hook hand bobs, smirk widens.
const SPOOF_IDLE_1 = frame(`
  ................................................
  ................................................
  ......................yyyy......................
  .....................yKKKKy.....................
  ....................yKKKKKKy....................
  ...................yKKKKKKKKy...................
  ..................yyyyyyyyyyyy..................
  .................YYYYYYYYYYYYYY.................
  ..............yyyyyyyyyyyyyyyyyyyy..............
  ........yyyyyyKKKKKKKKKKKKKKKKKKKKyyyyyy........
  ....yyyyKKKKKKKKKKKKKKyyyyKKKKKKKKKKKKKKyyyy....
  ...yKKKKKKKKKKKKKKKKKyYYYYyKKKKKKKKKKKKKKKKKy...
  ....yyyKKKKKKKKKKKKKKyYyyYyKKKKKKKKKKKKKKyyy....
  .......yyyyyKKKKKKKKKKyyyyKKKKKKKKKKyyyyy.......
  ............yyyyyyyyyyyyyyyyyyyyyyyy............
  ...............ssssssssssssssssss...............
  ...............ssssssssssssssssss...............
  ...............ssssssssssssssssss...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............sSSKKKKSSSSKKKKSSs...............
  ...............sSSKKKKSSSSKKKKSSs...............
  ...............sSSSSSSSSSSSSSSHHs...............
  ...............sSHWWWWWWWWWWWWHSs...............
  ...............sSHHHHHHHHHHHHHHSs...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............ssssssssssssssssss...............
  .................ssssssssssssss.................
  ....................................tttttt......
  ..........YYYYtttttttttttttttttttttttttttt......
  ..........YYYYtttttttttttttttttttttttttttt......
  ..........ttTTTttttttWCCCCCCWttttttTtttttt......
  .......TTtttTTTttttttWCCCCCCWttttttTTtTTT.......
  .......TTtttTTTttttttWCCCCCCWttttttTTtTTT.......
  .......TTtttTTTttttttWCCCCCCWttttttTTtTTT.......
  .......TTtttTTTttttttWCCCCCCWttttttTTtTTT.......
  .......TTtttTTTtYWWYtWCCCCCCWttttttTTtTTT.......
  .......TTtttTTTtWyyWtWCCCCCCWttttttTTtTTT.......
  .......TTtttTTTtWWWWtWCCCCCCWttttttTTtTTT.......
  .......TTtttTTTttttttWCCCCCCWttttttTTtTTT.......
  ......ttttttTTTttttttWCCCCCCWttttttTTtTTT.......
  ......tsssstTTTttttttWCCCCCCWttttttTTtTTT.......
  ......tsssstTTTttttttWCCCCCCWttttttTTtTTT.......
  ......tsssstTTTttttttWCCCCCCWttttttTTWWWW.......
  ......ttttttTTTttttttWCCCCCCWttttttTTWWWW.......
  ......ttttttTTTttttttWCCCCCCWttttttTTWWWW.......
  ...........tTTTttttttWCCCCCCWttttttTTYty........
  ...........tTTTttttttttttttttttttttTTTY.y.......
  ..........TTTttttttttttttttttttttttttTTY........
  ..........TTTttttttttttttttttttttttttTTT........
  ..........TTTttttttttt......tttttttttTTT........
  ..........TTTttttttttt......tttttttttTTT........
  ..........tttttttttttt......tttttttttttt........
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  .............kkkkkkkkkk..kkkkkkkkkk.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
`);

// attack f0: windup -- lunges forward, hook starts rising, grin cracking open.
const SPOOF_ATTACK_0 = frame(`
  ................................................
  ................................................
  .......................yyyy.....................
  ......................yKKKKy....................
  .....................yKKKKKKy...................
  ....................yKKKKKKKKy..................
  ...................yyyyyyyyyyyy.................
  ..................YYYYYYYYYYYYYY................
  ...............yyyyyyyyyyyyyyyyyyyy.............
  .........yyyyyyKKKKKKKKKKKKKKKKKKKKyyyyyy.......
  .....yyyyKKKKKKKKKKKKKKyyyyKKKKKKKKKKKYKKyyyy...
  ....yKKKKKKKKKKKKKKKKKyYYYYyKKKKKKKKKyKKKKKKKy..
  .....yyyKKKKKKKKKKKKKKyYyyYyKKKKKKKKKKYYKKyyy...
  ........yyyyyKKKKKKKKKKyyyyKKKKKKKKKKyyyYy......
  .............yyyyyyyyyyyyyyyyyyyyyyyy....Y......
  ...............ssssssssssssssssss...WWWWWy......
  ...............ssssssssssssssssss...WWWWy.......
  ...............ssssssssssssssssss...WWWWW.......
  ...............sSSSSSSSSSSSSSSSSs...WWWWW.......
  ...............sSSKKKKSSSSKKKKSSs...ttTTT.......
  ...............sSSKKKKSSSSKKKKSSHs..ttTTT.......
  ...............HWWWWWWWWWWWWWWHWH...ttTTT.......
  ...............HWWWWWWWWWWWWWWWWH...ttTTT.......
  ...............HHHWWHWWHWWHWWHHHH...ttTTT.......
  ...............HHHHHHHHHHHHHHHHHH...ttTTT.......
  ...............sSSSSSSSSSSSSSSSSs...ttTTT.......
  ...............ssssssssssssssssss...ttTTT.......
  .................ssssssssssssss.....ttTTT.......
  ....................................ttTTT.......
  ........YYYYttttttttttttttttttttttYYttTTT.......
  ........YYYYttttttttttttttttttttttYYttTTT.......
  ........ttTTTttttttWCCCCCCWttttttTTTttTTT.......
  .......TTttTTttttttWCCCCCCWttttttTTttttttt......
  .......TTttTTttttttWCCCCCCWttttttTTttttttt......
  .......TTttTTttttttWCCCCCCWttttttTTttttttt......
  .......TTttTTttttttWCCCCCCWttttttTTttttttt......
  .......TTttTTtYWWYtWCCCCCCWttttttTTttttttt......
  .......TTttTTtWyyWtWCCCCCCWttttttTTTt...........
  .......TTttTTtWWWWtWCCCCCCWttttttTTTt...........
  .......TTttTTttttttWCCCCCCWttttttTTTt...........
  ......ttttttTttttttWCCCCCCWttttttTTTt...........
  ......tsssstTttttttWCCCCCCWttttttTTTt...........
  ......tsssstTttttttWCCCCCCWttttttTTTt...........
  ......tsssstTttttttWCCCCCCWttttttTTTt...........
  ......ttttttTttttttWCCCCCCWttttttTTTt...........
  ......ttttttTttttttWCCCCCCWttttttTTTt...........
  .........tTTTttttttWCCCCCCWttttttTTTt...........
  .........tTTTttttttttttttttttttttTTTt...........
  ........TTTttttttttttttttttttttttttTTT..........
  ........TTTttttttttttttttttttttttttTTT..........
  ........TTTttttttttt......tttttttttTTT..........
  ........TTTttttttttt......ttkkkkkkKKTT..........
  ........tttttttttttt......ttkkkkkkKKtt..........
  ............KKkkkkk.........kkkkkkKK............
  ............KKkkkkk.........kkkkkkKK............
  ............KKkkkkk.........kkkkkkKK............
  ............KKkkkkk.........kkkkkkKK............
  ............KKkkkkk.........kkkkkkKK............
  ..........kkkkkkkkkkk......kkkkkkkkkkkkk........
  ..........KKKKKKKKKKK......KKKKKKKKKKKKK........
  ..........KKKKKKKKKKK......KKKKKKKKKKKKK........
  ..........KKKKKKKKKKK......KKKKKKKKKKKKK........
  ..........KKKKKKKKKKK......KKKKKKKKKKKKK........
  ..........KKKKKKKKKKK......KKKKKKKKKKKKK........
`);

// attack f1: full lunge -- hook raised high, grin widest, a gold "phish" glint off the tip.
const SPOOF_ATTACK_1 = frame(`
  ................................................
  ................................................
  ........................yyyy....................
  .......................yKKKKy...................
  ......................yKKKKKKy..................
  .....................yKKKKKKKKy......Y..........
  ....................yyyyyyyyyyyy....y...........
  ...................YYYYYYYYYYYYYY....YY.........
  ................yyyyyyyyyyyyyyyyyyyy...Y........
  ..........yyyyyyKKKKKKKKKKKKKKKKKKKKyyyyYy......
  ......yyyyKKKKKKKKKKKKKKyyyyKKKKKKKWWWWWyKyyyy..
  .....yKKKKKKKKKKKKKKKKKyYYYYyKKKKKKWWWWyKKKKKKy.
  ......yyyKKKKKKKKKKKKKKyYyyYyKKKKKKWWWWWKKKyYW..
  .........yyyyyKKKKKKKKKKyyyyKKKKKKKWWWWWyyy.....
  ..............yyyyyyyyyyyyyyyyyyyyyttTTT........
  ...............ssssssssssssssssss..ttTTT........
  ...............ssssssssssssssssss..ttTTT........
  ...............ssssssssssssssssss..ttTTT........
  ...............sSSSSSSSSSSSSSSSSs..ttTTT........
  ...............sSSKKKKSSSSKKKKSSs..ttTTT........
  ...............sSSKKKKSSSSKKKKSSHs.ttTTT........
  ...............HWWWWWWWWWWWWWWHWH..ttTTT........
  ...............HWWWWWWWWWWWWWWWWH..ttTTT........
  ...............HHHWWHWWHWWHWWHHHH..ttTTT........
  ...............HHHHHHHHHHHHHHHHHH..ttTTT........
  ...............sSSSSSSSSSSSSSSSSs..ttTTT........
  ...............ssssssssssssssssss..ttTTT........
  .................ssssssssssssss....ttTTT........
  ...................................ttTTT........
  .......YYYYttttttttttttttttttttttYYttTTT........
  .......YYYYttttttttttttttttttttttYYttTTT........
  .......ttTTTttttttWCCCCCCWttttttTTTttTTT........
  .......TTttTttttttWCCCCCCWttttttTTttttttt.......
  .......TTttTttttttWCCCCCCWttttttTTttttttt.......
  .......TTttTttttttWCCCCCCWttttttTTttttttt.......
  .......TTttTttttttWCCCCCCWttttttTTttttttt.......
  .......TTttTtYWWYtWCCCCCCWttttttTTttttttt.......
  .......TTttTtWyyWtWCCCCCCWttttttTTTt............
  .......TTttTtWWWWtWCCCCCCWttttttTTTt............
  .......TTttTttttttWCCCCCCWttttttTTTt............
  ......ttttttttttttWCCCCCCWttttttTTTt............
  ......tsssstttttttWCCCCCCWttttttTTTt............
  ......tsssstttttttWCCCCCCWttttttTTTt............
  ......tsssstttttttWCCCCCCWttttttTTTt............
  ......ttttttttttttWCCCCCCWttttttTTTt............
  ......ttttttttttttWCCCCCCWttttttTTTt............
  ........tTTTttttttWCCCCCCWttttttTTTt............
  ........tTTTttttttttttttttttttttTTTt............
  .......TTTttttttttttttttttttttttttTTT...........
  .......TTTttttttttttttttttttttttttTTT...........
  .......TTTttttttttt......tttttttttTTT...........
  .......TTTttttttttt......tttkkkkkkKKT...........
  .......tttttttttttt......tttkkkkkkKKt...........
  ............KKkkkkk.........kkkkkkKK............
  ............KKkkkkk.........kkkkkkKK............
  ............KKkkkkk.........kkkkkkKK............
  ............KKkkkkk.........kkkkkkKK............
  ............KKkkkkk.........kkkkkkKK............
  ..........kkkkkkkkkkk......kkkkkkkkkkkkk........
  ..........KKKKKKKKKKK......KKKKKKKKKKKKK........
  ..........KKKKKKKKKKK......KKKKKKKKKKKKK........
  ..........KKKKKKKKKKK......KKKKKKKKKKKKK........
  ..........KKKKKKKKKKK......KKKKKKKKKKKKK........
  ..........KKKKKKKKKKK......KKKKKKKKKKKKK........
`);

// hurt: recoils back, eyes clenched shut, hook arm flung out wide.
const SPOOF_HURT_0 = frame(`
  ................................................
  ................................................
  .......................yyyy.....................
  ......................yKKKKy....................
  .....................yKKKKKKy...................
  ....................yKKKKKKKKy..................
  ...................yyyyyyyyyyyy.................
  ..................YYYYYYYYYYYYYY................
  ...............yyyyyyyyyyyyyyyyyyyy.............
  .........yyyyyyKKKKKKKKKKKKKKKKKKKKyyyyyy.......
  .....yyyyKKKKKKKKKKKKKKyyyyKKKKKKKKKKKKKKyyyy...
  ....yKKKKKKKKKKKKKKKKKyYYYYyKKKKKKKKKKKKKKKKKy..
  .....yyyKKKKKKKKKKKKKKyYyyYyKKKKKKKKKKKKKKyyy...
  ........yyyyyKKKKKKKKKKyyyyKKKKKKKKKKyyyyy......
  .............yyyyyyyyyyyyyyyyyyyyyyyy...........
  ...............ssssssssssssssssss...............
  ...............ssssssssssssssssss...............
  ...............ssssssssssssssssss...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............sSSXXXXSSSSXXXXSSs...............
  ...............sSSXXXXSSSSXXXXSSs...............
  ...............sSSSSSSSSSSSSSSHss...............
  ...............sSHWWWWWWWWWWWWHSs...............
  ...............sSHHHHHHHHHHHHHHSs...............
  ...............sSSSSSSSSsSSSSSSSs...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............ssssssssssssssssss...............
  .................ssssssssssssss.................
  ................................................
  ...........YYYYttttttttttttttttttttttYYYY.......
  ...........YYYYttttttttttttttttttttttYYYY.......
  ...........ttTTTttttttWCCCCCCWttttttTTTtt.......
  .......TTttttTTTttttttWCCCCCCWttttttTTTtt.......
  .......TTtt.tTTTttttttWCCCCCCWttttttTTTttttTTT..
  .......TTtt.tTTTttttttWCCCCCCWttttttTTTttttTTT..
  .......TTtt.tTTTttttttWCCCCCCWttttttTTTttttTTT..
  .......TTtt.tTTTtYWWYtWCCCCCCWttttttTTTttttTTT..
  .......TTtt.tTTTtWyyWtWCCCCCCWttttttTTTtttttttt.
  .......TTtt.tTTTtWWWWtWCCCCCCWttttttTTTtttttttt.
  .......TTtt.tTTTttttttWCCCCCCWttttttTTTtttttttt.
  ......tttttttTTTttttttWCCCCCCWttttttTTTtttttWWWW
  ......tssssttTTTttttttWCCCCCCWttttttTTTtttttWWWW
  ......tssssttTTTttttttWCCCCCCWttttttTTTt....WWWY
  ......tssssttTTTttttttWCCCCCCWttttttTTTt....WWYY
  ......tttttttTTTttttttWCCCCCCWttttttTTTt....WWWy
  ......tttttttTTTttttttWCCCCCCWttttttTTTt......y.
  ............tTTTttttttWCCCCCCWttttttTTTt........
  ............tTTTttttttttttttttttttttTTTt........
  ...........TTTttttttttttttttttttttttttTTT.......
  ...........TTTttttttttttttttttttttttttTTT.......
  ...........TTTttttttttt......tttttttttTTT.......
  ...........TTTttttttttt......tttttttttTTT.......
  ...........tttttttttttt......tttttttttttt.......
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  ...............KKkkkkk....kkkkkKK...............
  .............kkkkkkkkkk..kkkkkkkkkk.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
  .............KKKKKKKKKK..KKKKKKKKKK.............
`);

// defeat f0: buckling -- hat knocked askew, knees giving out, cracks web the coat.
const SPOOF_DEFEAT_0 = frame(`
  ................................................
  ................................................
  ....................yyyy........................
  ...................yKKKKy.......................
  ..................yKKKKKKy......................
  .................yKKKKKKKKy.....................
  ................yyyyyyyyyyyy....................
  ...............YYYYYYYYYYYYYY...................
  ............yyyyyyyyyyyyyyyyyyyy................
  ......yyyyyyKKKKKKKKKKKKKKKKKKKKyyyyyy..........
  ..yyyyKKKKKKKKKKKKKKyyyyKKKKKKKKKKKKKKyyyy......
  .yKKKKKKKKKKKKKKKKKyYYYYyKKKKKKKKKKKKKKKKKy.....
  ..yyyKKKKKKKKKKKKKKyYyyYyKKKKKKKKKKKKKKyyy......
  .....yyyyyKKKKKKKKKKyyyyKKKKKKKKKKyyyyy.........
  ..........yyyyyyyyyyyyyyyyyyyyyyyy..............
  ...............ssssssssssssssssss...............
  ...............ssssssssssssssssss...............
  ...............ssssssssssssssssss...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............sSSXXXXSSSSXXXXSSs...............
  ...............sSSXXXXSSSSXXXXSSs...............
  ...............sSSSSSSSSSSSSSSHss...............
  ...............sSHWWWWWWWWWWWWHSs...............
  ...............sSHHHHHHHHHHHHHHSs...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............sSSSSSSSSSSSSSSSSs...............
  ...............ssssssssssssssssss...............
  .................ssssssssssssss.................
  ................................................
  ..........YYYYttttttttttttttttttttttYYYY........
  ..........YYYYttttttttttttttttttttttYYYY........
  ..........ttTTTttttttWCCCCCCWttttttTTTtt........
  .......TTtttTTTttttttWCCCCCCWttttttTtttttt......
  .......TTtttTTXttttttWCCCCCCWttttttTtttttt......
  .......TTtttTTTttttttWCCCCCCWttttttTtttttt......
  .......TTtttTTTttttttWCCCCCCWttttXtTtttttt......
  .......TTtttTTTtYWWYtWCCCCCCWttttttTTtTTT.......
  .......TTtttTTTtWyyWtWCCCCCCWttttttTTtTTT.......
  .......TTtttTTTtWWWWtWCCCCCCWttttttTTtTTT.......
  .......TTtttTTTttttttWCCCCCCWttttttTTtTTT.......
  ......ttttttTTTttttttWCCCCCCWttttttTTXTTT.......
  ......tsssstTTTtttXttWCCCCCCWttttttTTtTTT.......
  ......tsssstTTTttttttWCCCCCCWttttttTTtTTT.......
  ......tsssstTTTttttttWCCCCCCWttttttTTtTTT.......
  ......ttttttTTTttttttWCCCCCCWXtttttTTtTTT.......
  ......ttttttXTTttttttWCCCCCCWttttttTTtTTT.......
  ...........tTTTttttttWCCCCCCWttttttTTtTTT.......
  ...........tTTTtttttttXttttttttttttTTWWWW.......
  ..........TTTttttttttttttttttttttttttWWWW.......
  ..........TTTttttttttttttttttttttttttWWWW.......
  ..........TTTttttttttt......tttttttttYTy........
  ..........TTTttttttttt......tttttttttTYTy.......
  ..........tttttttttttt......tttttttttttY........
  ................KKkkkkk..kkkkkKK................
  ................KKkkkkk..kkkkkKK................
  .............KKKKKKKKKKKKkkkkkKK................
  .............KKKKKKKKKKKKkkkkkKK................
  .............KKKKKKKKKKKKKKKKKKKKKK.............
  .............KKKKKKKKKKKKKKKKKKKKKK.............
  .............KKKKKKKKKKKKKKKKKKKKKK.............
  ........................KKKKKKKKKKK.............
  ........................KKKKKKKKKKK.............
  ................................................
  ................................................
`);

// defeat f1: crumbling -- the coat and legs dissolve into scattered motes.
const SPOOF_DEFEAT_1 = frame(`
  ................................................
  ................................................
  ......................yy........................
  ...................yKKKKy.......................
  ..................yKKKKKKy......................
  .................yKKKKKKKKy.....................
  .................yyyyyyyy.yy....................
  ...............Y.YYYYYYYYYYYY...................
  ............yyyyy.yyyyyyyyyyyyyy................
  ......yyy.yyKKKKKKKKKKKK..KKK.KKyyyyyy..........
  ..yyyyKKKKKKKKKKKKKKyyyyKKKKKKKKK.K.KKy.yy......
  .yKKKKKKKKKKKKKKKKKyYYYYyKKKKKKKKKKKKKKKKKy.....
  ..yyyKKKKKKKKKKK.KKyYyyYyKKKKKKKKKKKKKKyyy......
  .....yyyyyKKKKKKKKKKyyyy.KKKKKKKKKy.yyy.........
  ..........yyyyyyyyyyyyyyy.yyyyyyyy..............
  ...............sssss.sssssssss..s...............
  ...............ssssss.sss.ss.ssss...............
  ...............ssssssssssssssssss...............
  ...............sSSSSSSSSSSSS.SSSs...............
  ...............sSS.XXXSSSSXXXXS.s...............
  ...............sS.XXXXSSSSXXXXSSs...............
  ...............sSSSSSSSSSSSSSSHss...............
  ...............sSH.WWWWWWWWWWWHSs...............
  ...............sS.H.HHHHHHHHHHHSs...............
  ...............sS.SSSSSSSSSSSS.Ss...............
  ...............sSSSS..SSS.SSSSSSs...............
  ...............ssssssssssss.sssss...............
  .................ss.ss..sssssss.................
  ................................................
  ..........Y..Y..t..tttt..t......t..tY..Y........
  ..........Y..Y.ttttt.t.tt.t.t.t.ttttY.Y.........
  ..........tt...ttttttWCC....Wttttt.TTTt.........
  ........T..t..Ttt.tt..CC...CW..tt..Ttt..........
  .......TTtttTTTtt...t....C...ttttt.Tttt..t......
  ........Tttt..T...tttWCC.CCC.t..tttT..tt........
  .......TT.ttTTTt.t...W.C.CC.Wttt.ttTtttt.t......
  .......T.tttTT.t.W...W.C....Wt...ttTTtT.........
  .......T.tttT.Tt.y.W.WCC.C.CWttttt.TT..TT.......
  .......T.t.t.TTtW.W.tWCCCCCC.t.t.t..Tt..........
  ........T..tT..t...t..CCCCCCW.tttttT....T.......
  ........ttt.T..tttttt.CCCCCCWtt.tt.TTt..T.......
  ......tss.s.TTT....tt..CC.CCWt.tt...Tt..T.......
  ......t.ss.tTT.tttt.tWC..CCCW.tt.tt.T..TT.......
  ........s.s...Ttt.tttW....CCW.tt..tTTtTT........
  ......t.t..tTTT.t.ttt.CCCCCCWt..t...T.TTT.......
  ......ttt.t.TTT.t.tttW...CC..t..tttT..TTT.......
  ...........tTT.t..ttt.....CC..t.tttTT...T.......
  ...........tTTTttttttttttt.ttttt...TTW.WW.......
  ..........TT.t.ttttt.tttttt...tttt.tt.WWW.......
  ..........T.T..ttt.tt..tt.t.tt..t.t..W.WW.......
  ..........TTTtt..t..tt......tt..tttt.YT.........
  ..........TTTtt.tt.ttt......t.t...tt.TY.y.......
  ..........t.ttttt.t..t......t.t..t.t..tY........
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
`);

// defeat f2 (held): only the hat and hollow-eyed face remain, trailing a sparse scatter of fading gold/teal embers.
const SPOOF_DEFEAT_2 = frame(`
  ................................................
  ................................................
  ....................yy..........................
  ......................KKy.......................
  ..................yKK.KKKy......................
  ..................KKKK.KK.y.....................
  ..................yyyyyyyy.y....................
  ................YY..YY..Y..YY...................
  ............yy.y.y.y.yyyyyyyyyyy................
  ......yyyyyyKKKK..K.KKKKK.K.KKK.yyyyyy..........
  ....yyKKKKKK.KK...K.y.y.KKKKKK.KKK.KKK.yyy......
  .yK.KKKKKKKKKKKKKK..YY.Y.KKKK.KKKKKK.KK..Ky.....
  ..yyyKKKKKKKKKKKKKK.YyyY.K.KKK.KKKKK.KKyyy......
  .....yy.y..KK.KKKK.K.yyyKK.KKKKKKKyyyyy.........
  ...........yy.yyy..yyyyyyyyyyy.yy...............
  ...............ssssssss..sss..sss...............
  ...............sssss.sssss.ssssss...............
  ...............s.sssssssssssss.ss...............
  ...............sSSSS.SS...SSSSSSs...............
  ...............sSS.XXXS..SXXXXSSs...............
  ...............sS.XX.XSSSSXX.XSSs...............
  ...............sS.SSSSS.SSSSSSSSs...............
  ................SSSSSSS.S.SSS.SS................
  ...............sSSSSS.SSSSSSSS.S................
  ...............sSSSSSSSS.SSS.S.Ss...............
  ...............sSSSS.SS...SSSSSSs...............
  ...............sss..sss..ssssssss...............
  .................ssss.ssssssss..................
  ................................................
  ................................................
  .....................Y..........................
  ................................................
  ................................................
  ..............................T.................
  ................................................
  ................................................
  ................t...............................
  ................................................
  ..................................y.............
  ................................................
  ................................................
  ........................Y.......................
  ................................................
  ................................................
  ................................................
  ...................T............................
  ................................................
  ................................................
  .............................t..................
  ................................................
  ................................................
  ................................................
  ......................y.........................
  ................................................
  ................................................
  ................................................
  ..........................T.....................
  ................................................
  ..................Y.............................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
`);

export const CAPTAIN_SPOOF_SPRITES: SpriteDef = {
  key: "boss-captain-spoof",
  w: 48,
  h: 64,
  frames: [SPOOF_IDLE_0, SPOOF_IDLE_1, SPOOF_ATTACK_0, SPOOF_ATTACK_1, SPOOF_HURT_0, SPOOF_DEFEAT_0, SPOOF_DEFEAT_1, SPOOF_DEFEAT_2],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 3, repeat: -1 },
    { key: "attack", frames: [2, 3], frameRate: 8, repeat: 0 },
    { key: "hurt", frames: [4], frameRate: 1, repeat: 0 },
    { key: "defeat", frames: [5, 6, 7], frameRate: 6, repeat: 0 },
  ],
};

// Task: The Warden, 48x64 -- a massive armored gate-guardian. A towering iron
// sentinel guarding a fortress gate: heavy D/d steel plate armor over a blocky
// golem silhouette, a crenellated battlement crown, a single glowing B cyber-blue
// visor slit for its eye, and M/m/L molten seams glowing like cracks of lava
// between the plates. Heavier and more armored than the toad and the pirate -- a
// hulking firewall knight-king filling the 48x64 canvas.
//
// Anims: idle (2f, slow breathing -- visor and molten seams flicker/shift),
// attack (2f, raises a huge gauntlet then strikes -- visor flares, seams surge),
// hurt (1f, armor flashes with W/R pixels as cracks widen), defeat (3f, a
// collapse: plates buckle -> armor shatters with molten spilling -> a slumped
// dark husk that CombatBackdropScene holds on the last frame after victory).

const WARDEN_IDLE_0 = frame(`
  ................................................
  ................................................
  ................................................
  ...............dd..dd..dd..dd..dd...............
  ..............dddddddddddddddddddd..............
  ..............DDDDDDDDDDDDDDDDDDDD..............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dkkkkkkkkkkkkkkkkd...............
  ...............dDKKKKKKKKKKKKKKDd...............
  ...............dDKbbbbbbbbbbbbKDd...............
  ...............dDKKBBBBBBBBBBKKDd...............
  ...............dDKKKKKKKKKKKKKKDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............kkkdkkkkkkkkkkdkkk...............
  .....dddddddddd...dkkkkkkkkkkd...dddddddddd.....
  .....dDDDmDDDDddddddddddddddddddddDDDDmDDDd.....
  .....dDDDmDDDDdDDDDDDDDDDDDDDDDDDdDDDDmDDDd.....
  .....dDDDMDDDDdDDDDDDDDLmDDDDDDDDdDDDDMDDDd.....
  .....dkkkmkkkkdDDDDDDDDMmDDDDDDDDdkkkkmkkkd.....
  .....dDDDmDDDDdDDDDDDDDmmDDDDDDDDdDDDDmDDDd.....
  .....dDDDMDDDDdDDDDDDDDmMDDDDDDDDdDDDDMDDDd.....
  .....dDDDmDDDDdKKKKKKKmmmmKKKKKKKdDDDDmDDDd.....
  .....dDDDmDDDDdDDDDDDDDMmDDDDDDDDdDDDDmDDDd.....
  .....DDDDDDDDDdDDDDDDDDLmDDDDDDDDdDDDDDDDDD.....
  .......dDDDDDDdDDDDDDDDmMDDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDDmmDDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDDMmDDDDDDDDdDDDDDDd.......
  .......dkkkkkkdDDDDDDDDmmDDDDDDDDdkkkkkkd.......
  .......dDDDDDDdKKKKKKKmmMmKKKKKKKdDDDDDDd.......
  .......dDDDDDDdDDDDDDDDLmDDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDDMmDDDDDDDDdDDDDDDd.......
  .......dkkkkkkdDDDDDDDDmmDDDDDDDDdkkkkkkd.......
  .......dDDDDDDdDDDDDDDDmMDDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDDmmDDDDDDDDdDDDDDDd.......
  .......dDDDDDDdKKKKKKKmMmmKKKKKKKdDDDDDDd.......
  .....ddddddddddDDDDDDDDLmDDDDDDDDdddddddddd.....
  .....DDkDDkDDkDDDDDDDDDmMDDDDDDDDDkDDkDDkDD.....
  .....DDkDDkDDkddddddddddddddddddddkDDkDDkDD.....
  .....DDkDDkDDkkkkkkkkkMMMMkkkkkkkkkDDkDDkDD.....
  .....DDDDDDDDDkkkdkkdkMLLMdkkdkkkkDDDDDDDDD.....
  .....DDDDDDDDDkkkkkkkkMMMMkkkkkkkkDDDDDDDDD.....
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDdDDDDDDDDD.....
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDdDDDDDDDDD.....
  .....KKKKKKKKKdDDDDDDDkOOkDDDDDDDdKKKKKKKKK.....
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dddddddddOOddddddddd..............
  ..............kkkkkkkkkOOkkkkkkkkk..............
  ..............dDDDmDDDkOOkDDDmDDDd..............
  ..............dDDDmDDDkOOkDDDmDDDd..............
  ..............dDDDMDDDkOOkDDDmDDDd..............
  ..............dDDDmDDDkOOkDDDMDDDd..............
  ..............dDDDmDDDkOOkDDDmDDDd..............
  ..............dDDDmDDDkOOkDDDmDDDd..............
  ..............dDDDmDDDkOOkDDDmDDDd..............
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........KKKKKKKKKKKKKKKKKKKKKKKKKK...........
  .........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........
  ................................................
`);

const WARDEN_IDLE_1 = frame(`
  ................................................
  ................................................
  ................................................
  ...............dd..dd..dd..dd..dd...............
  ..............dddddddddddddddddddd..............
  ..............DDDDDDDDDDDDDDDDDDDD..............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dkkkkkkkkkkkkkkkkd...............
  ...............dDKKKKKKKKKKKKKKDd...............
  ...............dDKBBBBBBBBBBBBKDd...............
  ...............dDKKbbbbbbbbbbKKDd...............
  ...............dDKKKKKKKKKKKKKKDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............kkkdkkkkkkkkkkdkkk...............
  .....dddddddddd...dkkkkkkkkkkd...dddddddddd.....
  .....dDDDMDDDDddddddddddddddddddddDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDDDDDDDDDDDDdDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDDmLDDDDDDDDdDDDDMDDDd.....
  .....dkkkMkkkkdDDDDDDDDmMDDDDDDDDdkkkkMkkkd.....
  .....dDDDMDDDDdDDDDDDDDmmDDDDDDDDdDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDDMmDDDDDDDDdDDDDMDDDd.....
  .....dDDDMDDDDdKKKKKKKmmmmKKKKKKKdDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDDmMDDDDDDDDdDDDDMDDDd.....
  .....DDDDDDDDDdDDDDDDDDmLDDDDDDDDdDDDDDDDDD.....
  .......dDDDDDDdDDDDDDDDMmDDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDDmmDDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDDmMDDDDDDDDdDDDDDDd.......
  .......dkkkkkkdDDDDDDDDmmDDDDDDDDdkkkkkkd.......
  .......dDDDDDDdKKKKKKKmMmmKKKKKKKdDDDDDDd.......
  .......dDDDDDDdDDDDDDDDmLDDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDDmMDDDDDDDDdDDDDDDd.......
  .......dkkkkkkdDDDDDDDDmmDDDDDDDDdkkkkkkd.......
  .......dDDDDDDdDDDDDDDDMmDDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDDmmDDDDDDDDdDDDDDDd.......
  .......dDDDDDDdKKKKKKKmmMmKKKKKKKdDDDDDDd.......
  .....ddddddddddDDDDDDDDmLDDDDDDDDdddddddddd.....
  .....DDkDDkDDkDDDDDDDDDMmDDDDDDDDDkDDkDDkDD.....
  .....DDkDDkDDkddddddddddddddddddddkDDkDDkDD.....
  .....DDkDDkDDkkkkkkkkkmmmmkkkkkkkkkDDkDDkDD.....
  .....DDDDDDDDDkkkdkkdkmLLmdkkdkkkkDDDDDDDDD.....
  .....DDDDDDDDDkkkkkkkkmmmmkkkkkkkkDDDDDDDDD.....
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDdDDDDDDDDD.....
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDdDDDDDDDDD.....
  .....KKKKKKKKKdDDDDDDDkOOkDDDDDDDdKKKKKKKKK.....
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dddddddddOOddddddddd..............
  ..............kkkkkkkkkOOkkkkkkkkk..............
  ..............dDDDLDDDkOOkDDDLDDDd..............
  ..............dDDDLDDDkOOkDDDLDDDd..............
  ..............dDDDMDDDkOOkDDDLDDDd..............
  ..............dDDDLDDDkOOkDDDMDDDd..............
  ..............dDDDLDDDkOOkDDDLDDDd..............
  ..............dDDDLDDDkOOkDDDLDDDd..............
  ..............dDDDLDDDkOOkDDDLDDDd..............
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........KKKKKKKKKKKKKKKKKKKKKKKKKK...........
  .........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........
  ................................................
`);

const WARDEN_ATTACK_0 = frame(`
  ................................................
  ................................................
  ................................................
  ...............dd..dd..dd..dd..dd...............
  ..............dddddddddddddddddddd..............
  ..............DDDDDDDDDDDDDDDDDDDD..............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd.........M.....
  ...............dkkkkkkkkkkkkkkkkd......dddddddd.
  ...............dDKKKbbbbbbbbKKKDd......DkDDkDmk.
  ...............dDbbbbbbbbbbbbbKDd......DkDDkDDk.
  ...............dDKKBBBBBBBBBBKbDd......DkDDkDDk.
  ...............dDKKKKKKBBKKKKKKDd......DDMDDDDD.
  ...............dDDDDDDDDDDDDDDDDd......DDDDDDDD.
  ...............dDDDDDDDDDDDDDDDDd......DDDDDDDD.
  ...............dDDDDDDDDDDDDDDDDd......DDDDDDDD.
  ...............kkkdkkkkkkkkkkdkkk......DDDDDDDD.
  .....dddddddddd...dkkkkkkkkkkd...ddddddDDDDDDDD.
  .....dDDDMDDDDddddddddddddddddddddDDDDMKKKKKKKK.
  .....dDDDMDDDDdDDDDDDDDDDDDDDDDDDdDDDDMDkDDDd...
  .....dDDDMDDDDdDDDDDDDmLmmDDDDDDDdDDDDMDkDDDd...
  .....dkkkMkkkkdDDDDDDDMMmMDDDDDDDdkkkkMkkDDDd...
  .....dDDDMDDDDdDDDDDDDmmmmDDDDDDDdDDDDMDkDDDd...
  .....dDDDMDDDDdDDDDDDDmmMmDDDDDDDdDDDDMDkDDDd...
  .....dDDDMDDDDdKKKKKLMmmmmMLKKKKKdDDDDMDkDDDd...
  .....dDDDMDDDDdDDDDDDDMMmMDDDDDDDdDDDDMDkDDDd...
  .....DDDDDDDDDdDDDDDDDmLmmDDDDDDDdDDDDDDkDDDd...
  .......dDDDDDDdDDDDDDDmmMmDDDDDDDd......kDDDd...
  .......dDDDDDDdDDDDDDDmmmmDDDDDDDd......kDDDd...
  .......dDDDDDDdDDDDDDDMMmMDDDDDDDd......kDDDd...
  .......dkkkkkkdDDDDDDDmmmmDDDDDDDd......DDDDD...
  .......dDDDDDDdKKKKKLMmmMmMLKKKKKd..............
  .......dDDDDDDdDDDDDDDmLmmDDDDDDDd..............
  .......dDDDDDDdDDDDDDDMMmMDDDDDDDd..............
  .......dkkkkkkdDDDDDDDmmmmDDDDDDDd..............
  .......dDDDDDDdDDDDDDDmmMmDDDDDDDd..............
  .......dDDDDDDdDDDDDDDmmmmDDDDDDDd..............
  .......dDDDDDDdKKKKKLMMMmMMLKKKKKd..............
  .....ddddddddddDDDDDDDmLmmDDDDDDDd..............
  .....DDkDDkDDkDDDDDDDDmmMmDDDDDDDd..............
  .....DDkDDkDDkdddddddddddddddddddd..............
  .....DDkDDkDDkkkkkkkkkMMMMkkkkkkkk..............
  .....DDDDDDDDDkkkdkkdkMLLMdkkdkkkk..............
  .....DDDDDDDDDkkkkkkkkMMMMkkkkkkkk..............
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDd..............
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDd..............
  .....KKKKKKKKKdDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dddddddddOOddddddddd..............
  ..............kkkkkkkkkOOkkkkkkkkk..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........KKKKKKKKKKKKKKKKKKKKKKKKKK...........
  .........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........
  ................................................
`);

const WARDEN_ATTACK_1 = frame(`
  ................................................
  ................................................
  ................................................
  ...............dd..dd..dd..dd..dd...............
  ..............dddddddddddddddddddd..............
  ..............DDDDDDDDDDDDDDDDDDDD..............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dkkkkkkkkkkkkkkkkd...............
  ...............dDKKKBBBBBBBBKKKDd...............
  ...............dDBBBBBBBBBBBBBKDd...............
  ...............dDKKBBBBBBBBBBKBDd...............
  ...............dDKKKKKKBBKKKKKKDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............kkkdkkkkkkkkkkdkkk...............
  .....dddddddddd...dkkkkkkkkkkd...dddddddddd.....
  .....dDDDMDDDDddddddddddddddddddddDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDDDDDDDDDDDDdDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDmmLmDDDDDDDdDDDDMDDDd...m.
  .....dkkkMkkkkdDDDDDDDMmMMDDDDDDDdkkkkMkkkdM....
  .....dDDDMDDDDdDDDDDDDmmmmDDDDDDDdDDDDMDkddddddd
  .....dDDDMDDDDdDDDDDDDmMmmDDDDDDDdDDDDMDkDDDDDDD
  .....dDDDMDDDDdKKKKKLMmmmmMLKKKKKdddddddkkDDkDDk
  .....dDDDMDDDDdDDDDDDDMmMMDDDDDDDdDDDDDDkkDDkDDk
  .....DDDDDDDDDdDDDDDDDmmLmDDDDDDDdDDDDDDkkDDkDDk
  .......dDDDDDDdDDDDDDDmMmmDDDDDDDdDDDDDDkkDDkDDk
  .......dDDDDDDdDDDDDDDmmmmDDDDDDDdDDDDDDkDDDDDDD
  .......dDDDDDDdDDDDDDDMmMMDDDDDDDdDDDDDDkDDDDDDD
  .......dkkkkkkdDDDDDDDmmmmDDDDDDDdkkkkkkkDDDDDDD
  .......dDDDDDDdKKKKKLMmMmmMLKKKKKd......kDDDDDDD
  .......dDDDDDDdDDDDDDDmmLmDDDDDDDd......kDDDDDDD
  .......dDDDDDDdDDDDDDDMmMMDDDDDDDd......kDDDDDDD
  .......dkkkkkkdDDDDDDDmmmmDDDDDDDd......kKKKKKKK
  .......dDDDDDDdDDDDDDDmMmmDDDDDDDd........M.....
  .......dDDDDDDdDDDDDDDmmmmDDDDDDDd...........m..
  .......dDDDDDDdKKKKKLMMmMMMLKKKKKd..............
  .....ddddddddddDDDDDDDmmLmDDDDDDDd..............
  .....DDkDDkDDkDDDDDDDDmMmmDDDDDDDd..............
  .....DDkDDkDDkdddddddddddddddddddd..............
  .....DDkDDkDDkkkkkkkkkMMMMkkkkkkkk..............
  .....DDDDDDDDDkkkdkkdkMLLMdkkdkkkk..............
  .....DDDDDDDDDkkkkkkkkMMMMkkkkkkkk..............
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDd..............
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDd..............
  .....KKKKKKKKKdDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dddddddddOOddddddddd..............
  ..............kkkkkkkkkOOkkkkkkkkk..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........KKKKKKKKKKKKKKKKKKKKKKKKKK...........
  .........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........
  ................................................
`);

const WARDEN_HURT_0 = frame(`
  ................................................
  ................................................
  ................................................
  ...............dd..dd..dd..dd..dd...............
  ..............dddddddddddddddddddd..............
  ..............DDDDDDDDDDDDDDDDDDDD..............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dkkkkkkkkkkkkkkkkd...............
  ...............dDKKKKKKKKKKKKKKDd...............
  ...............dDKrrrrrrrrrrrrKDd...............
  ...............dDKKRRRRRRRRRRKKDd...............
  ...............dDKKKKKKKKKKKKKKDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............kkkdkkkkkkkkkkdkkk...............
  .....dddddddddd...dkkkkkkkkkkd...dddddddddd.....
  .....dDDDMDDDDddddddddddddddddddddDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDDDDDDDDDRDDdDDDDMDDDd.....
  .....dDDDXDDDDdDDDDDDDmWmmDDDDDDDdDDDDXDDDd.....
  .....dkkkMrWkkdDDDDDDDMMmMDDDDDDDdkkkkMrkkd.....
  .....dDDDMDDDDdDDDDXDDmmmmDDXDDDDdDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDrDmmMmDDDrDDDdDDDDMDDDd.....
  .....dDDDMDDDDdKKKKKLMmmmmMLKKKKKdDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDMMmMDDDDDDDdRDDDMDDDd.....
  .....DDDDDDDDDdDDDDDDDmLmmDDDDDDDdDDDDDDDDD.....
  .......dDDDDDWdDDDDDWDmmMmDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDmmmmDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDMMmMDDDDDDDdDDDDDDd.......
  .......dkkkkXkdDDDDDDDmmmmDDRDDDDdkkkXkkd.......
  .......dDDDDDrdKKKKKLMmmMmMLKKKKKdDDDDrDd.......
  .......dDDDDDDdDDDDDDDmLmmDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDWDDDMMRMDDDDDDDdDDDDDDd.......
  .......dkkkkkkdDDXDDDDmmmmDDDDXDDdkkkkkkd.......
  .......dDDDDDDdDDDrDDDmmMmDDDDDrDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDmmmmDDDRDDDdDDDDDDd.......
  .......dDDDDDDdKKKKKLMMMmMMLKKKKKdDDDDDDd.......
  .....ddddddddddDDDDDDDmLmmDDDDDDDdddddddddd.....
  .....DDkDDkDDkDDDDDDDDmmMmDDDDDDDDkDDkDDkDD.....
  .....DDkWDkDDkddddddddddddddddddddkDDkDDkDD.....
  .....DDkDDkDDkkkkkkkkkmmmmkkkkkkkkkDDkDRkDD.....
  .....DDDDDDDDDkkkdkkdkmLLmdkkdkkkkDDDDDDDDD.....
  .....DDDDDDDDDkkkkkkkkmmmmkkkkkkkkDDDDDDDDD.....
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDdDDDDDDDDD.....
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDdDDDDDDDDD.....
  .....KKKKKKKKKdDDDDDDDkOOkDDDDDDDdKKKKKKKKK.....
  ..............dDWDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDXDkOOkDXDDDDDd..............
  ..............dDDDDDDrkOOkDDrDDWDd..............
  ..............dddddddddOOddddddddd..............
  ..............kkkkkkkkkOOkkkkkkkkk..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDXDMDDDkOOkDDDMDXDd..............
  ............R.dDDrMDDDkOOkDDDMDDrd..............
  ..............dDDDMDDDkOOkDDDMDDDd.W............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........KKKKKKKKKKKKKKKKKKKKKKKKKK...........
  .........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........
  ................................................
`);

const WARDEN_DEFEAT_0 = frame(`
  ................................................
  ................................................
  ................................................
  ...............dd..dd..dd..dd..dd...............
  ..............dddddddddddddddddddd..............
  ..............DDDDDDDDDDDDDDDDDDDD..............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dkkkkkkkkkkkkkkkkd...............
  ...............dDKKKKKKKKKKKKKKDd...............
  ...............dDKNNNNNNNNNNNNKDd...............
  ...............dDKKbbbbbbbbbbKKDd...............
  ...............dDKKKKKKKKKKKKKKDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............dDDDDDDDDDDDDDDDDd...............
  ...............kkkdkkkkkkkkkkdkkk...............
  .....dddddddddd...dkkkkkkkkkkd...dddddddddd.....
  .....dDDDMDDDDddddddddddddddddddddDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDDDDDDDDDDDDdDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDmmLmDDDDDDDdDDDDMDDDd.....
  .....dkkkMkkkkdDDDKDDDMmMMDDDDDDDdkkkkMkkkd.....
  .....dDDDMD..DdDDDmkDDmmmmKDDDDDDdDD..MDDDd.....
  .....dKKKKKKKKdDDDDDDDmMmmDkDDDDDdKKKKKKKKd.....
  .....dDDDMDDDDdKKKKKLMmmmmMLKKKKKdDDDDMDDDd.....
  .....dDDDMDDDDdDDDDDDDMmMMDDDDKDDdDDDDMDDDd.....
  .....DDDDDDDDDdDDDDDDDmmLmDDDDmkDdDDDDDDDDD.....
  .......dDDDDDDdDKDKDKDKMKmKDKDKDKdDDDDDDd.......
  .......dDDDDDDdDDDDDDDmmmmDDDDDDDdDDDDDDd.......
  .......dDDDDDKdDDDDDDDMmMMDDDDDDDdDDDDDDd.......
  .......dkkkkkkkDDDDDDDmmmmDDDDDDDdkkkkkkd.......
  .......dDDDDDDdKKKKKLMmMmmMLKKKKKdDDDDDDd.......
  .......dDDDDDDdDDDDDDDmmLmDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDDDMmMMDDDDDDDdKDDDDDd.......
  .......dkkkkkkdDDDDDDDmmmmDDDDDDDdkkkkkkd.......
  .......dDDDDDDdDDDDKDDmMmmDDDDDDDdDDDDDDd.......
  .......dDDDDDDdDDDDDMDmmmmDDDDDDDdDDDDDDd.......
  .......dDDDDDDdKKKKKLMMmMMMLKKKKKdDDDDDDd.......
  .....ddddddddddDDDDDDDmmLmDDKDDDDdddddddddd.....
  .....DDkDDkDDkD.DDDDDDmMmmDmDkDD.DkDDkDDkDD.....
  .....DDkDDkDDkddddddddddddddddddddkDDkDDkDD.....
  .....DDkDDkDDkkkkkkkkkmmmmkkkkkkkkkDDkDDkDD.....
  .....DDDDDDDDDkkkdkkdkmLLmdkkdkkkkDDDDDDDDD.....
  .....DDDDDDDDDkkkkkkkkmmmmkkkkkkkkDDDDDDDDD.....
  .....DDDDDDDDDdDDDDDDDkOOkDDDDDDDdDDDDDDDDD.....
  .....DDDDDDDDDdDKDDDDDkOOkDDDDDDDdDDDDDDDDD.....
  .....KKKKKKKKKdDDkDDDDkOOkDDDDDKDdKKKKKKKKK.....
  ..............dDDDDDDDkOOkDDDDDDkd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dddddddddOOddddddddd..............
  ..............kkkkkkkkkOOkkkkkkkkk..............
  ..............dDDDMDKDkOOkDDDMDDDd..............
  ..............dDDDMDDkkOOkDKDMDDDd..............
  ..............dDDDMDDDkOOkDDkMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........KKKKKKKKKKKKKKKKKKKKKKKKKK...........
  .........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........
  ................................................
`);

const WARDEN_DEFEAT_1 = frame(`
  ................................................
  ................................................
  ................................................
  ...............dd..dd..dd..dd..dd...............
  ..............dddddddddddddddddddd..............
  ..............DDDDDDDDDDDDDDDDDDDD..............
  ...............d.DDDD.DDDD.DDDD.d...............
  ...............dD.DDKD.DDDD.DDDD................
  .........D.....dkk.kkkk.kkkk.kkkdk..............
  ...............dDKK.KKKK.KKDK.KDd...............
  ..............d.DKKK.KKKKbKKKK.Dd...............
  ...............d.KKKKMNKKK.KKKK.d...............
  ...........M...dD.KKKK.KKKK.KKKM................
  ...............dDD.DDDD.DDDD.DDDd...............
  ...............dDDD.DDDD.DmDD.DDd.......k.......
  .......k........mDDD.DDDD.DDDD.Dd...............
  ...............k.kdkk.kkkk.kkdd.k...............
  .....dd.dddd.dd...dkkk.kkkk.kd...dddd.dddd......
  .....dDD.DDDD.dddd.dddd.dddd.dddd.DDDD.DDDd.....
  .....dDDD.DDDD.DDDD.DDDD.DDDD.DDDd.DDDD.DDd.....
  ......DDDD.DDMd.DDDD.DmLm.DDDD.DDdD.DDDD.Dd.....
  .....d.kkkk.kkdD.DDDD.MMMM.DDDD.Ddkk.kkkk.d.....
  .....dD.DDDD.DdDDkDDDD.mmmD.DDDD.dMDD.DDDD......
  .....dDD.DDDD.dDDD.DDDm.MmDD.dDDD.DDDD.DDDd.....
  .....dDDD.DDDD.KKKKmLMmm.mMLK.KKKd.DDDD.DDd.....
  ......DDDD.DDDd.DDDD.DMMm.DDDDmDDdD.DDDD.Dd.....
  .....D.DDDD.DDdD.DDDD.mDmm.DDDD.DdDD.DDDD.D.....
  ........DDDD.DdDD.DDDD.mMmD.DDDD.dDKD.DDd.......
  .......d.mDDD.dDDD.DDDmmmmDD.DDDD.DDDD.Dd.......
  .......dD.DDDD.DDDD.DDMM.MDDD.DDDm.DDDD.d.......
  .......dkk.kkkd.DMDD.Dmmm.DDDD.DDdk.kkkk........
  .......ddDD.DDdK.KKKL.mmMm.MKKK.KdDD.DDDd.......
  ........DDDD.DdDD.DDDDkLmmD.DDDD.dDDD.DDd.......
  .......d.DDDD.dDDD.DDDM.mMDD.DDDD.dDDD.Dd.......
  .......dk.kkkk.DDDD.DDmm.mDDD.DDDd.kkkk.d.......
  .......dDD.DDDd.DDDD.DmmM.DDDD.DDdD.DDDD........
  .......dDDD.DDdD.DDDD.mmmm.DDDD.DdDD.DDDd.......
  ........DDDD.DMKK.KKLM.MmMM.KKKK.dDDD.DDd.......
  .....ddd.dddd.dDDD.DDDm.mmmD.DDDD.dddd.dddd.....
  .....DDkD.kDDk.DDDD.MDmm.mDDD.DDDD.DDkD.kDD.....
  .....DDkDDkDDkdddddddddddddddddMddkDDkDDkDD.....
  .....DDkDDkDDkkkkkkkkkMMMMkkkkkkkkkDDkDDkDD.....
  .....DDDDDDDDDkkkdmkdkMLLMdkkdkkkkDDDDDDDDD.....
  .....DDDDDDDDDkkkkkkkkMMMMkkkkkkkkDMDDDDDDD.....
  .....DDDDDDDMDdDDDDDDDkOOkDDDDDDDdDDDDDDDDD.....
  .....DDDDDDDDDdDDDDDDDkMOkDDDDDDDdDDDDDDDDD.....
  .....KKKKKKKKKdDDDDDDDkOOkDDDDDDDdKKKKKKKKK.....
  ..............dDmDDDDDkOOkDDDDDDDd..............
  ..............dDDDDDDDkOOkDDDDMDDd..............
  ..............dDDDDDDDkOOkDDDDDDDd..............
  ..............dddddddddOOddddddddd..............
  ..............kkkkkkkkkOOkkkkkkkkk..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ..............dDDDMDDDkOOkDDDMDDDd..............
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........DDDDDDDDDDDDDDDDDDDDDDDDDD...........
  ...........KKKKKKKKKKKKKKKKKKKKKKKKKK...........
  .........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........
  ................................................
`);

const WARDEN_DEFEAT_2 = frame(`
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  .......................r........................
  ................r...............................
  ................................................
  ..............................r.................
  ................................................
  ...................r............................
  .................................r..............
  ................................................
  ....................KKKKKKKK....................
  ....................kkkkkkkk....................
  ....................kkkBNkkk....................
  ...................KkkkkkkkkK...................
  ...................KkkkkkkkkK...................
  ...................KKKKKKKLKK...................
  ................kkkKKKKKKKKKKkkk................
  ................kkkkmkkkkkkkkkkk................
  ................kkkkkkkkkkkkkkkk................
  .............OKKkkkkkkkkkkkkkkkkKKO.............
  .............OkkkkkkkkkkkkkkkkkkkkO.............
  .........KKKKOKkkrkkkkkkkkkkkkkkkKOKKKK.........
  .........kkkkOkkkkkkkkkkkkkkmkkkkkOkkkk.........
  .........kkkkOkkkkkkkkLkkkkkkkkkkkOkkkk.........
  .........kkkrOkOkkOkkOkkOkkOkkOkkkOrkkk.........
  .........kkkkOkkkkkkkkkkkkkkkkkrkkOkkkk.........
  .........kkkkOkLkkkkkkkkkkkkkkkkkkOkkkk.........
  .........kkkkOkOkkOkkOkkOrkOkkOkkkOkkkk.........
  .............OkkkkkkkkkkkkkkkkkkkkO.............
  .............OkkkkkkkkkLkkkkkrkkkkO.............
  ............OOOOOOOOOOOOOOOOOOOOOOOO............
  ..........kkkkkkkkkkkkkkkkkkkkkkkkkkkk..........
  ................................................
`);

export const WARDEN_SPRITES: SpriteDef = {
  key: "boss-warden",
  w: 48,
  h: 64,
  frames: [WARDEN_IDLE_0, WARDEN_IDLE_1, WARDEN_ATTACK_0, WARDEN_ATTACK_1, WARDEN_HURT_0, WARDEN_DEFEAT_0, WARDEN_DEFEAT_1, WARDEN_DEFEAT_2],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 3, repeat: -1 },
    { key: "attack", frames: [2, 3], frameRate: 8, repeat: 0 },
    { key: "hurt", frames: [4], frameRate: 1, repeat: 0 },
    { key: "defeat", frames: [5, 6, 7], frameRate: 6, repeat: 0 },
  ],
};

// Task 20 — The Blank Page, 48x64. A featureless white humanoid (W body / C
// soft shade) with ragged ink-drip O edges. Its FACE appears ONLY in the defeat
// frames — idle/attack/hurt are deliberately blank, selling "I am every chapter
// you never started." Built by a deterministic generator (like the parallax
// layers) so every frame is provably 48x64 and palette-clean; the sprite-sheet
// integrity test still guards it. Anims: idle (2f, a quiet breathing shimmer),
// attack (2f, arms reach out into ink-drip hands — the telegraphed grasp), hurt
// (1f, a ripple crosses the sheet), defeat (3f: eyes open -> a small smile ->
// a dissolve into falling pages, the held final frame CombatBackdropScene keeps
// under the victory panel).
const BP_W = 48;
const BP_H = 64;
const BP_CX = 24;

function bpHalf(y: number): number {
  if (y < 4 || y > 60) return 0;
  if (y <= 18) {
    const dy = y - 11;
    const r = 8;
    const v = r * r - dy * dy;
    return v > 0 ? Math.round(Math.sqrt(v)) : 0; // rounded head
  }
  if (y <= 22) return 5; // neck
  if (y <= 30) return 9 + (y - 22); // shoulders widen 9 -> 17
  if (y <= 52) return 17; // torso
  return Math.max(7, 17 - (y - 52) * 2); // taper to base
}

function bpHash(x: number, y: number): number {
  let h = (x * 374761393 + y * 668265263) >>> 0;
  h = (h ^ (h >>> 13)) >>> 0;
  return h;
}

interface BpOpts {
  shimmer: 0 | 1 | 2; // idle breathing phase
  reach: 0 | 1 | 2; // attack: 0 none, 1 windup, 2 full reach
  ripple: boolean; // hurt bands
  eyes: boolean; // defeat face
  smile: boolean; // defeat face
  dissolve: boolean; // defeat final: scatter into pages
}

function blankFrame(o: BpOpts): string[] {
  const g: string[][] = Array.from({ length: BP_H }, () => Array<string>(BP_W).fill("."));

  if (o.dissolve) {
    for (let y = 4; y < BP_H; y++) {
      const half = bpHalf(Math.min(y, 60));
      for (let x = BP_CX - half; x <= BP_CX + half; x++) {
        if (x < 0 || x >= BP_W) continue;
        const keep = bpHash(x, y) % 5;
        if (keep === 0) g[y][x] = "W";
        else if (keep === 1) g[y][x] = "C";
      }
    }
    const flakes: [number, number][] = [[10, 40], [30, 46], [18, 54], [34, 58], [8, 60], [24, 50]];
    for (const [fx, fy] of flakes)
      for (let yy = 0; yy < 3; yy++)
        for (let xx = 0; xx < 4; xx++) {
          const px = fx + xx;
          const py = fy + yy;
          if (px < BP_W && py < BP_H) g[py][px] = yy === 0 ? "W" : "C";
        }
    return g.map((r) => r.join(""));
  }

  for (let y = 4; y <= 60; y++) {
    const half = bpHalf(y);
    if (half <= 0) continue;
    const left = BP_CX - half;
    const right = BP_CX + half;
    for (let x = left; x <= right; x++) {
      if (x < 0 || x >= BP_W) continue;
      if (x === left || x === right) g[y][x] = "O"; // ink-drip outline
      else if (x > BP_CX + half * 0.35) g[y][x] = "C"; // soft shade
      else g[y][x] = "W";
    }
    if (o.shimmer && y % 6 === (o.shimmer === 1 ? 2 : 4) && half > 6) {
      g[y][BP_CX + (o.shimmer === 1 ? -3 : 3)] = "C"; // breathing fleck
    }
  }

  // Base ink drips.
  for (const dx of [18, 24, 30])
    for (let y = 61; y <= 61 + (bpHash(dx, 7) % 2); y++) if (y < BP_H) g[y][dx] = "O";

  if (o.reach > 0) {
    const armY = o.reach === 2 ? 30 : 26;
    const extent = o.reach === 2 ? 20 : 13;
    for (let dy = 0; dy < 4; dy++) {
      const y = armY + dy;
      for (let d = 0; d <= extent; d++) {
        const xs = [BP_CX - 17 - d, BP_CX + 17 + d];
        for (const x of xs) {
          if (x < 0 || x >= BP_W) continue;
          g[y][x] = d === extent ? "O" : dy === 0 ? "W" : "C";
        }
      }
    }
  }

  if (o.ripple) {
    for (let y = 12; y <= 56; y += 6) {
      const half = bpHalf(y);
      for (let x = BP_CX - half + 1; x < BP_CX + half; x++) {
        if (x >= 0 && x < BP_W && g[y][x] === "W") g[y][x] = "C";
      }
    }
  }

  if (o.eyes) {
    for (let dy = 0; dy < 2; dy++)
      for (let dx = 0; dx < 2; dx++) {
        g[10 + dy][20 + dx] = "O";
        g[10 + dy][27 + dx] = "O";
      }
  }
  if (o.smile) {
    const smile: [number, number][] = [
      [18, 15], [19, 16], [20, 16], [21, 16], [22, 16], [23, 16],
      [24, 16], [25, 16], [26, 16], [27, 16], [28, 15],
    ];
    for (const [x, y] of smile) g[y][x] = "O";
  }

  return g.map((r) => r.join(""));
}

const BLANK_IDLE_0 = blankFrame({ shimmer: 1, reach: 0, ripple: false, eyes: false, smile: false, dissolve: false });
const BLANK_IDLE_1 = blankFrame({ shimmer: 2, reach: 0, ripple: false, eyes: false, smile: false, dissolve: false });
const BLANK_ATTACK_0 = blankFrame({ shimmer: 0, reach: 1, ripple: false, eyes: false, smile: false, dissolve: false });
const BLANK_ATTACK_1 = blankFrame({ shimmer: 0, reach: 2, ripple: false, eyes: false, smile: false, dissolve: false });
const BLANK_HURT_0 = blankFrame({ shimmer: 0, reach: 0, ripple: true, eyes: false, smile: false, dissolve: false });
const BLANK_DEFEAT_0 = blankFrame({ shimmer: 0, reach: 0, ripple: false, eyes: true, smile: false, dissolve: false });
const BLANK_DEFEAT_1 = blankFrame({ shimmer: 0, reach: 0, ripple: false, eyes: true, smile: true, dissolve: false });
const BLANK_DEFEAT_2 = blankFrame({ shimmer: 0, reach: 0, ripple: false, eyes: false, smile: false, dissolve: true });

export const BLANK_PAGE_SPRITES: SpriteDef = {
  key: "boss-blank-page",
  w: 48,
  h: 64,
  frames: [BLANK_IDLE_0, BLANK_IDLE_1, BLANK_ATTACK_0, BLANK_ATTACK_1, BLANK_HURT_0, BLANK_DEFEAT_0, BLANK_DEFEAT_1, BLANK_DEFEAT_2],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 2, repeat: -1 },
    { key: "attack", frames: [2, 3], frameRate: 8, repeat: 0 },
    { key: "hurt", frames: [4], frameRate: 1, repeat: 0 },
    { key: "defeat", frames: [5, 6, 7], frameRate: 4, repeat: 0 },
  ],
};

export const BOSS_SPRITES: SpriteDef[] = [GLITCH_TOAD_SPRITES, CAPTAIN_SPOOF_SPRITES, WARDEN_SPRITES, BLANK_PAGE_SPRITES];

// bossId -> its SpriteDef, for CombatBackdropScene to look up (mirrors
// tilesetFor's theme -> tile-sprite lookup in tiles-fields.ts). Bosses without
// an authored sprite yet fall through to undefined, and the scene keeps
// rendering the placeholder anchor ring instead.
export const BOSS_SPRITE_BY_ID: Partial<Record<BossId, SpriteDef>> = {
  "glitch-toad": GLITCH_TOAD_SPRITES,
  "captain-spoof": CAPTAIN_SPOOF_SPRITES,
  "warden": WARDEN_SPRITES,
  "blank-page": BLANK_PAGE_SPRITES,
};
