import { frame } from "../grid";
import type { SpriteDef } from "../textures";

// THE HOLLOW GIANT — World 1-2 boss art (owner-directed rework). A colossal
// sandstone guardian buried to the chest in the arena floor: weathered x-stone
// body with A rim-light and u/k cracks, a helm-dome head with ember M/Y eyes
// in a dark visor slit, and a hollow CHEST CAVITY (deep-blue n gloom ringed
// with mauve f/i dead-flesh and broken rib teeth) where the heart sprite
// pulses. The arms slope down and OUT of the frame into the sand — the slam
// hands rise from the ground as separate sprites, so nothing "adjoints".
//
// The torso is GENERATED (same precedent as the parallax backdrops): one
// composition + per-mode recolors (idle breathe / hurt flare / defeat dark),
// deterministic and integrity-tested like any authored frame.

const TW = 128;
const TH = 136;

function hash(x: number, y: number): number {
  let h = (x * 73856093) ^ (y * 19349663);
  h = (h ^ (h >>> 13)) >>> 0;
  return h;
}

function buildTorsoBase(): string[][] {
  const g: string[][] = Array.from({ length: TH }, () => Array<string>(TW).fill("."));
  const px = (x: number, y: number, ch: string) => {
    if (x >= 0 && x < TW && y >= 0 && y < TH) g[y][x] = ch;
  };
  const ell = (cx: number, cy: number, rx: number, ry: number, ch: string) => {
    for (let y = Math.floor(cy - ry); y <= cy + ry; y++)
      for (let x = Math.floor(cx - rx); x <= cx + rx; x++) {
        const dx = (x - cx) / rx;
        const dy = (y - cy) / ry;
        if (dx * dx + dy * dy <= 1) px(x, y, ch);
      }
  };
  const rect = (x0: number, y0: number, x1: number, y1: number, ch: string) => {
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) px(x, y, ch);
  };

  // Arms: sloping stone slabs from the shoulders down out of frame — they
  // read as burying into the sand at the arena floor.
  for (let t = 0; t <= 10; t++) {
    const f = t / 10;
    ell(30 - 24 * f, 54 + 74 * f, 13 - 3 * f, 12 - 3 * f, "x");
    ell(97 + 24 * f, 54 + 74 * f, 13 - 3 * f, 12 - 3 * f, "x");
  }
  // Shoulders + torso core down to the ground line.
  ell(32, 52, 21, 15, "x");
  ell(95, 52, 21, 15, "x");
  ell(64, 80, 35, 44, "x");
  rect(32, 96, 95, TH - 1, "x");
  // Head: helm dome + jaw, visor slit with ember eyes.
  ell(64, 26, 17, 15, "x");
  rect(49, 32, 78, 44, "x");
  rect(50, 23, 77, 29, "k"); // visor slit
  rect(54, 24, 57, 28, "M");
  rect(55, 25, 56, 27, "Y"); // left ember eye
  rect(70, 24, 73, 28, "M");
  rect(71, 25, 72, 27, "Y"); // right ember eye
  // Jaw seam.
  for (let x = 52; x <= 75; x += 3) px(x, 40, "u");

  // Chest cavity: gloom ringed by dead-flesh and broken rib teeth.
  ell(64, 52, 17, 16, "u"); // outer broken rim
  ell(64, 52, 15, 14, "i"); // flesh ring
  ell(64, 52, 12, 11, "n"); // the hollow
  for (let a = 0; a < 12; a++) {
    // rib teeth biting inward around the rim
    const ang = (a / 12) * Math.PI * 2;
    const tx = Math.round(64 + Math.cos(ang) * 14);
    const ty = Math.round(52 + Math.sin(ang) * 13);
    px(tx, ty, "x");
    px(tx + (tx > 64 ? -1 : 1), ty, "u");
  }
  // Faint flesh flecks drifting in the gloom.
  for (let y = 42; y <= 62; y++)
    for (let x = 52; x <= 76; x++)
      if (g[y][x] === "n" && hash(x * 3, y * 5) % 17 === 0) px(x, y, "f");

  // Shading pass: A rim-light on top edges, u shade on bottom edges, cracks.
  for (let y = 0; y < TH; y++)
    for (let x = 0; x < TW; x++) {
      if (g[y][x] !== "x") continue;
      const above = y === 0 ? "." : g[y - 1][x];
      const below = y === TH - 1 ? "x" : g[y + 1][x];
      if (above === ".") g[y][x] = "A";
      else if (below === ".") g[y][x] = "u";
      else if (hash(x, y) % 89 === 0) g[y][x] = "u";
      else if (hash(x * 7, y * 3) % 131 === 0) g[y][x] = "k";
    }
  // Long cracks running down from the cavity (the hollowing spreads).
  for (const [sx, len] of [
    [48, 26],
    [82, 22],
    [64, 30],
  ] as const) {
    let cx = sx;
    for (let d = 0; d < len; d++) {
      const y = 66 + d;
      if (g[y]?.[cx] === "x") g[y][cx] = "k";
      cx += hash(cx, y) % 3 === 0 ? 1 : hash(cx, y) % 3 === 1 ? -1 : 0;
    }
  }
  // Rubble skirt: the base widens and crumbles into the arena floor.
  for (let y = 124; y < TH; y++) {
    const spread = (y - 124) * 2;
    for (let x = 32 - spread; x <= 95 + spread; x++) {
      if (x < 0 || x >= TW) continue;
      const h2 = hash(x * 5, y * 7) % 10;
      if (g[y][x] === "." && h2 < 6) px(x, y, h2 < 2 ? "u" : "x");
    }
  }
  return g;
}

/** Per-mode recolors over the shared composition. */
function torsoFrame(mode: "idle0" | "idle1" | "hurt" | "defeat"): string[] {
  const g = buildTorsoBase();
  for (let y = 0; y < TH; y++)
    for (let x = 0; x < TW; x++) {
      const ch = g[y][x];
      if (mode === "idle1") {
        // breathe: embers dim a step, the flesh ring stirs
        if (ch === "Y") g[y][x] = "M";
        else if (ch === "f") g[y][x] = "i";
        else if (ch === "i" && hash(x, y) % 11 === 0) g[y][x] = "f";
      } else if (mode === "hurt") {
        if (ch === "Y" || ch === "M") g[y][x] = "W"; // eyes flare white
        else if (ch === "i" && hash(x, y) % 5 === 0) g[y][x] = "R"; // flesh flushes
        else if (ch === "f") g[y][x] = "R";
      } else if (mode === "defeat") {
        if (ch === "Y" || ch === "M") g[y][x] = "k"; // embers die
        else if (ch === "n") g[y][x] = "K"; // the hollow goes black
        else if (ch === "f" || ch === "i") g[y][x] = "u";
        else if (ch === "x" && hash(x * 3, y * 7) % 19 === 0) g[y][x] = "k"; // shatter cracks
      }
    }
  return g.map((r) => r.join(""));
}

export const HOLLOW_GIANT_TORSO: SpriteDef = {
  key: "hollow-giant",
  w: TW,
  h: TH,
  frames: [torsoFrame("idle0"), torsoFrame("idle1"), torsoFrame("hurt"), torsoFrame("defeat")],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 1.6, repeat: -1 },
    { key: "hurt", frames: [2], frameRate: 1, repeat: 0 },
    { key: "defeat", frames: [3], frameRate: 1, repeat: 0 },
  ],
};

// ── Hands — single clean pieces (no separate forearm to mis-join) ────────────
// 40x24. Frame 0 "open": the flat-topped upturned PALM the player rides —
// finger ridges with A rim light, a thumb nub, u understone. Frame 1 "fist":
// the knuckle block that only hurts.

const HAND_OPEN = frame(`
  ........................................
  ........................................
  ........................................
  ........................................
  ..AAAA.AAAA.AAAA.AAAA...................
  ..xxxx.xxxx.xxxx.xxxx......AAA..........
  ..xxxxxxxxxxxxxxxxxxxx....Axxx..........
  ..xxxxxxxxxxxxxxxxxxxxx..Axxxx..........
  ..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..........
  .uxxxxxxxxxxxxxxxxxxxxxxxxxxxxu.........
  .uxxxxxxxxxxxkxxxxxxxxxxxxxxxxu.........
  .uuxxxxxxxxxxxxxxxxxxxkxxxxxxuu.........
  ..uuxxxxxxxxxxxxxxxxxxxxxxxxuu..........
  ...uuuuuuuuuuuuuuuuuuuuuuuuuu...........
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
`);

const HAND_FIST = frame(`
  ..............AAAAAAAA..................
  ..............xxxxxxxx..................
  ..............xxxxxxxx..................
  ............AAxxxxxxxxAA................
  ..........AAxxxxxxxxxxxxAA..............
  .........AxxxxxxxxxxxxxxxxA.............
  ........AxxxxxxxxxxxxxxxxxxA............
  ........xxxxkxxxxxxxxxkxxxxx............
  ........xxxxxxxxxxxxxxxxxxxx............
  ........xxxxxxxxxxxxxxxxxxxx............
  .......uxxxxxxxxxkxxxxxxxxxxu...........
  .......uxxxxxxxxxxxxxxxxxxxxu...........
  .......uxAAxxAAxxAAxxAAxxxxxu...........
  .......uxxxxxxxxxxxxxxxxxxxxu...........
  ........uuuuuuuuuuuuuuuuuuuu............
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
`);

export const HOLLOW_GIANT_HAND: SpriteDef = {
  key: "hollow-giant-hand",
  w: 40,
  h: 24,
  frames: [HAND_OPEN, HAND_FIST],
  anims: [
    { key: "open", frames: [0], frameRate: 1, repeat: 0 },
    { key: "fist", frames: [1], frameRate: 1, repeat: 0 },
  ],
};

// ── The heart (unchanged art): whole → crack1 → crack2 → shatter ─────────────

export const HOLLOW_GIANT_HEART: SpriteDef = {
  key: "hollow-giant-heart",
  w: 20,
  h: 20,
  frames: [
frame(`
....................
....................
....................
.......X..r..X......
......XrX...XrX.....
.....XrrrX.XrrrX....
....XrrRRMXMRRrrX...
....XrrRMMMMMRrrX...
...XrrRMMYYYMMRrrX..
...XrrRMYYYYYMRrrX..
....XrRMYYYYYMRrX...
.....XRMYYYYYMRX....
......XMMYYYMMX.....
.......XMMMMMX......
.......XRMMMRX......
........XRRRX.......
.........XrX........
..........X.........
....................
....................
`),
frame(`
....................
....................
......XXX...XXX.....
....XXXXXXrXXXXXX...
...XXXrrrXXXrrrXXX..
...XXrrRRRMRRRrrXX..
..XXrrRRMMMMMRRrrXX.
.XXrrrRMMYYYMMRrrrXX
.XXrrRRMYWWWYMRRrrXX
..XXrRMMYWWWYMMRrXX.
...XXRMMYWWWYMMRXX..
....XXRMYWWWYMRXX...
....XXRMMYYYMMRXX...
.....XXRMMMMMRXX....
......XXRRMRRXX.....
......XXrRRRrXX.....
.......XXrrrXX......
........XXrXX.......
.........XXX........
..........X.........
`),
frame(`
....................
....................
....................
.......X..r..X......
......XrX...XrX.....
.....XrrrO.XrrrX....
....XrrRRMOKRRrrX...
....XrrRMOKMMRrrX...
...XrrRMMOKYMMRrrX..
...XrrRMYYYOKMRrrX..
....XrRMYYYOKMRrX...
.....XRMYYYOKMRX....
......XMMYYOKMX.....
.......XMMMMOK......
.......XRMMMOK......
........XRRRX.......
.........XrX........
..........X.........
....................
....................
`),
frame(`
....................
....................
......XXX...XXX.....
....XXXXXXrXXXXXX...
...XXXrrrXXXrrrXXX..
...XXrrRROKRRRrrXX..
..XXrrRRMMOKMRRrrXX.
.XXrrrRMMOKYMMRrrrXX
.XXrrRRMYOKWYMRRrrXX
..XXrRMMYWWOKMMRrXX.
...XXRMMYWWOKMMRXX..
....XXRMYWWOKMRXX...
....XXRMMYYOKMRXX...
.....XXRMMMMOKXX....
......XXRRMROKX.....
......XXrRRRrXX.....
.......XXrrrXX......
........XXrXX.......
.........XXX........
..........X.........
`),
frame(`
....................
....................
....................
.......X..r..X......
......XrX...XrX.....
.....XrrrO.XrOKX....
....XrrRROKMRRrrX...
....XrOKMOKOKKrrX...
...XrrOKMYYYMMRrrX..
...XrrROKYOKOKRrrX..
....XrRMOKYOKMRrX...
.....XRMYYOKKMRX....
......XMOOKOKMX.....
.......XOKMOKX......
.......XRMOKOK......
........XROKX.......
.........XOK........
..........X.........
....................
....................
`),
frame(`
....................
....................
......XXX...XXX.....
....XXXXXXrXXXXXX...
...XXXrrrXXXrrrXXX..
...XXrrRROKRROKrXX..
..XXrrRRMOKMMRRrrXX.
.XXrrrOKMOKOKKRrrrXX
.XXrrROKYWWWYMRRrrXX
..XXrRMOKWOKOKMRrXX.
...XXRMMOKWOKMMRXX..
....XXRMYWOKKMRXX...
....XXRMOOKOKMRXX...
.....XXROKMOKRXX....
......XXRROKOKX.....
......XXrROKrXX.....
.......XXrOKXX......
........XXrXX.......
.........XXX........
..........X.........
`),
frame(`
....................
....................
....................
.......X.Mr..X......
......XOK...MrX.....
....Y.rrOK.Xr.rX..M.
....XrrRROKMR.KrX...
....OKOKOKKMOK.rX...
...XrO.OKOKKMMRrrX..
...XrrRO.OOKKMRrrX..
....XrRO.MMOOOKOK...
.....XRMOO.KMMRX....
......XMMOOKKMX.....
.......XOO.OKX......
.......XOOOOKO......
........XROKX....M..
.........XOO........
..........X.........
....................
...............M....
`),
frame(`
.......Y............
....................
......XXX...XXX.....
....XXXXXXrXX.MXX...
...XXXrOKXXX.M..XX..
...XXrrROKMRRRrr.X..
..XXr.RRMOKMM.KrrYX.
.MXr.KOKOKKYOKR.rr.X
.XXY.OKOKOKKYMRRrrXX
..X.rRM.KOOKKMMRrXX.
...XXRMOK.WOOO.OKX..
....XXRM.OKKYMRXO...
..M.XXRMMO.KKMRXX...
.....XXROOKOKRXX....
.....MXXOOOO.OK.....
......XXrROKrXX.....
.......XXrOOKX......
........XMrOK.......
.........X.X........
..........X.........
`)
  ],
  anims: [
    {key:"whole",frames:[0,1],frameRate:4,repeat:-1},
    {key:"crack1",frames:[2,3],frameRate:5,repeat:-1},
    {key:"crack2",frames:[4,5],frameRate:6,repeat:-1},
    {key:"shatter",frames:[6,7],frameRate:9,repeat:0}
  ],
};

export const HOLLOW_GIANT_SPRITES: SpriteDef[] = [
  HOLLOW_GIANT_TORSO,
  HOLLOW_GIANT_HAND,
  HOLLOW_GIANT_HEART,
];
