// NOTE: kit char `Q` (neon magenta) remapped → `o` (repo hot-pink; Q = desert
// crystal). Sprite key normalized to the RtBossId. Art pixels only.
import { frame } from "../grid";
import type { SpriteDef } from "../textures";

// THE ONE-EYED DEALER — World 1-3 boss kit (24x40 figure + 10x12 mask +
// bullets + muzzle flash). Slim, elegant, unnaturally fast masked gunman:
// porcelain face-plate (C/W/c) on a dark void head (K/O), ONE magenta LED eye
// (Q) with a devil trident glyph, purple suit (V/v/U violet ramp), white shirt
// + black tie, gunmetal pistol (D/d). Masked = invulnerable; parry a glowing
// (white-gold) bullet to break a clasp; three clasps drop the mask -> the void
// head with only the LED eye is exposed and vulnerable. Proposed palette char:
//   Q #ff3d9a  neon magenta (LED eye, devil glyph, casino neon)
// See NOTES.md for the anim-state -> in-game-use map.

// ---------- figure frames (24x40) ----------
const DEALER_IDLE_0 = frame(`
  ........................
  ........C......C........
  .......kCCCCCCCCk.......
  .......kKCCCCCCKk.......
  .......kKCcoWcCKk.......
  .......kKCcoocCKk.......
  .......kKCCCCCCKk.......
  .......kKCCcocCKk.......
  .......kKCoooooKk.......
  .......kKCococoKk.......
  ........kKCCCCKk........
  .........kKCCKk.........
  ........vCWWWWCv........
  ......UvvCWWWWCvvU......
  .....UvvvCWKKWCvvvU.....
  .....UvvvCWKKWCvvvU.....
  .....UvvvvCKKCvvvvU.....
  .....UvvvvvKKvvvvvU.....
  ......UvvvvKvvvvvU......
  ......CvvvvKvvvvvC......
  ......UvvvvvvvvvvU......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........KKK..KKK........
  .......KKKK..KKKK.......
  ........................
`);

const DEALER_IDLE_1 = frame(`
  ........................
  ........C......C........
  .......kCCCCCCCCk.......
  .......kKCCCCCCKk.......
  .......kKCcoocCKk.......
  .......kKCcoocCKk.......
  .......kKCCCCCCKk.......
  .......kKCCcocCKk.......
  .......kKCoooooKk.......
  .......kKCococoKk.......
  ........kKCCCCKk........
  .........kKCCKk.........
  ........vCWWWWCv........
  ......UvvCWWWWCvvU......
  .....UvvvCWKKWCvvvU.....
  .....UvvvCWKKWCvvvU.....
  .....UvvvvCKKCvvvvU.....
  .....UvvvvvKKvvvvvU.....
  ......UvvvvKvvvvvU......
  ......CvvvvKvvvvvC......
  ......UvvvvvvvvvvU......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........KKK..KKK........
  .......KKKK..KKKK.......
  ........................
`);

const DEALER_MOVE_0 = frame(`
  ........................
  ........C......C........
  .......kCCCCCCCCk.......
  .......kKCCCCCCKk.......
  .......kKCcoWcCKk.......
  .......kKCcoocCKk.......
  .......kKCCCCCCKk.......
  .......kKCCcocCKk.......
  .......kKCoooooKk.......
  .......kKCococoKk.......
  ........kKCCCCKk........
  .........kKCCKk.........
  ........vCWWWWCv........
  ......UvvCWWWWCvvU......
  .....UvvvCWKKWCvvvU.....
  .....UvvvCWKKWCvvvU.....
  .....UvvvvCKKCvvvvU.....
  .....UvvvvvKKvvvvvU.....
  ......UvvvvKvvvvvU......
  ......CvvvvKvvvvvC......
  ......UvvvvvvvvvvU......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  ........vvvvvvvv........
  ........vvvvvvvv........
  .........vvvvvv.........
  .........UvvvvU.........
  ..........vvvv..........
  ..........UvvU..........
  ...........vv...........
  ........................
  .......v...vv...v.......
  ......v..v....v..v......
  .....v..........v......v
  ...v................v...
  ........................
`);

const DEALER_MOVE_1 = frame(`
  ........................
  ........C......C........
  .......kCCCCCCCCk.......
  .......kKCCCCCCKk.......
  .......kKCcoWcCKk.......
  .......kKCcoocCKk.......
  .......kKCCCCCCKk.......
  .......kKCCcocCKk.......
  .......kKCoooooKk.......
  .......kKCococoKk.......
  ........kKCCCCKk........
  .........kKCCKk.........
  ........vCWWWWCv........
  ......UvvCWWWWCvvU......
  .....UvvvCWKKWCvvvU.....
  .....UvvvCWKKWCvvvU.....
  .....UvvvvCKKCvvvvU.....
  .....UvvvvvKKvvvvvU.....
  ......UvvvvKvvvvvU......
  ......CvvvvKvvvvvC......
  ......UvvvvvvvvvvU......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  ........vvvvvvvv........
  ........vvvvvvvv........
  .........vvvvvv.........
  .........UvvvvU.........
  ..........vvvv..........
  ..........UvvU..........
  ...........vv...........
  ........................
  ......v...vv...v........
  .v...v..v....v..v.......
  v...v..........v...v....
  ..v................v...v
  ........................
`);

const DEALER_AIM = frame(`
  ........................
  ........C......C........
  .......kCCCCCCCCk.......
  .......kKCCCCCCKk.......
  .......kKCcoWcCKk.......
  .......kKCcoocCKk.......
  .......kKCCCCCCKk.......
  .......kKCCcocCKk.......
  .......kKCoooooKk.......
  .......kKCococoKk.......
  ........kKCCCCKk........
  .........kKCCKk.........
  ........vCWWWWCv........
  ......UvvCWWWWCvvU......
  .....UvvvCWKKWCvvvU.....
  .....UvvvCWKKWCvvvCddDKB
  .....UvvvvCKKCvvvvU.DD..
  .....UvvvvvKKvvvvvU.....
  ......UvvvvKvvvvvU......
  ......CvvvvKvvvvvC......
  ......UvvvvvvvvvvU......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........KKK..KKK........
  .......KKKK..KKKK.......
  ........................
`);

const DEALER_FIRE = frame(`
  ........................
  ........C......C........
  .......kCCCCCCCCk.......
  .......kKCCCCCCKk.......
  .......kKCcoWcCKk.......
  .......kKCcoocCKk.......
  .......kKCCCCCCKk.......
  .......kKCCcocCKk.......
  .......kKCoooooKk.......
  .......kKCococoKk.......
  ........kKCCCCKk........
  .........kKCCKk.........
  ........vCWWWWCv........
  ......UvvCWWWWCvvU......
  .....UvvvCWKKWCvvvU.....
  .....UvvvCWKKWCvvvCddDWY
  .....UvvvvCKKCvvvvU.DD..
  .....UvvvvvKKvvvvvU.....
  ......UvvvvKvvvvvU......
  ......CvvvvKvvvvvC......
  ......UvvvvvvvvvvU......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........KKK..KKK........
  .......KKKK..KKKK.......
  ........................
`);

const DEALER_TELE_0 = frame(`
  ........k......k........
  ........kK.KK.Kk........
  .......k.CC.CC.Kk.......
  .......kK.C.C.CKk.......
  .......k.C.c.c.Kk.......
  .......kKC.oW.CKk.......
  .......k.Cco.cCk.......v
  ......v.KC.coCC.k.......
  .......kK.o.ocoKk.......
  ......v..kC.CCk.........
  .v.......kK.CKk...v.....
  ....v...vC.WW.Cv........
  ......Uv.CW.WCv.U.....v.
  .v..U.vvC.WWWCvv.U......
  ....Uvvv.WKK.Cv.vU..v...
  ..v..Uvv.CK.Cvvv.U......
  .....Uv.vvKKvv.vU....v..
  ...v..Uvvv.v.vvvU.......
  ......C.vv.Kv.vvC..v....
  .v.....U.vvvv.vU........
  ...v....Uvv.vvvU....v...
  .......Uv.vvvv.U........
  ..v.....v.vvvv.U...v....
  .v......U.vvvvU.........
  ........v.vvvv..v.......
  .......U.vvvvvvU...v....
  ..v.....v.vvvv.v........
  .......v.vU..Uv.v.......
  .v.......vU..Uv....v....
  ....v...vvU..Uvv........
  .......v.vU..Uv.....v...
  ..v......vU..Uv.v.......
  .......v.vU..Uvv........
  .v....v..vU..Uv....v....
  ........vvU..Uv.v.......
  .....v..vvU..Uvv...v....
  ..v.....KKK..KKK........
  .v....v.KKK..KKK...v....
  ........................
  ........................
`);

const DEALER_TELE_1 = frame(`
  ........................
  ........v......v........
  .........v...v.........v
  ..v.......v.v...........
  .v.........o............
  ......v...oW....v.......
  ...........v......v.....
  .v....v.......v.........
  ........v..v.......v....
  ..v.......v....v........
  .....v.......v.....v....
  .v.......v.......v......
  ....v.......v..........v
  .v....v.......v...v.....
  ........v.v.......v.....
  ..v.......v....v........
  .....v.v.......v...v....
  .v.......v.v.....v......
  ....v.......v.....v....v
  .v....v.......v.........
  ..v.....v.v.......v.....
  .....v.......v.....v....
  .v.......v.v.....v......
  ....v.......v.....v....v
  .v....v.......v....v....
  ........v.v.......v.....
  ..v.......v....v........
  .....v.v.......v...v....
  .v.......v.v.....v......
  ....v.......v.....v....v
  .v....v.......v....v....
  ........v.v.......v.....
  ..v.......v....v........
  .....v.v.......v...v....
  .v.......v.v.....v......
  ....v.......v.....v....v
  .v....v.......v....v....
  ........v.v.......v.....
  ........................
  ........................
`);

const DEALER_REAPPEAR = frame(`
  ........v......v........
  ......v.kVVVVVVk.v......
  .....v.kVCCCCCCVk.v.....
  .v....VkVCCCCCCVkV....v.
  ...v...kVCVVVVCVk...v...
  ......vkVCcoWcCVkv......
  .v.....kVCcoocCVk....v..
  ...v...kVCCcoCCVk...v...
  ......v.kVococoVk.v.....
  .v......VkVCCCVk.v...v..
  ...v.....vkVCVkv........
  ......V..vVCWWCVv..V....
  .v...VvvVCWWWWCvVvV.....
  ...VUvvvCWKKWCvvvUV..v..
  ....UvvvvCKKCvvvvU......
  .v...UvvvvvKKvvvvvU..v..
  ......UvvvvKvvvvvU......
  .v....CvvvvKvvvvvC...v..
  ...V..UvvvvvvvvvvU..V...
  .v.....UvvvvvvvvU....v..
  ...v...UvvvvvvvvU...v...
  .v.....UvvvvvvvvU....v..
  ...V...UvvvvvvvvU..V....
  .v.....UvvvvvvvvU....v..
  ...v...UvvvvvvvvU...v...
  .v.....UvvvvvvvvU....v..
  .......UvvvvvvvvU.......
  .v.....UvvvvvvvvU....v..
  .......vvU..Uvv.........
  .v.....vvU..Uvv.....v...
  .......vvU..Uvv.........
  .v.....vvU..Uvv.....v...
  .......vvU..Uvv.........
  .......vvU..Uvv.........
  .......vvU..Uvv.........
  .......vvU..Uvv.........
  .......KKK..KKK.........
  ......KKKK..KKKK........
  ........................
  ........................
`);

const DEALER_STRIKE = frame(`
  ........................
  ........C......C........
  .......kCCCCCCCCk.......
  .......kKCCCCCCKk.......
  .......kKCcoWcCKk.......
  .......kKCcoocCKk.......
  .......kKCCCCCCKk.......
  .......kKCCcocCKk.......
  .......kKCoooooKk.......
  .......kKCococoKk.......
  ........kKCCCCKk........
  .........kKCCKk.........
  ........vCWWWWCv........
  ......UvvCWWWWCvvU......
  .....UvvvCWKKWCvvvU.....
  ..DdCvvvCWKKWCvvvvU.....
  .WY.CvvvvCKKCvvvvU......
  ..B.UvvvvvKKvvvvvU......
  ......UvvvvKvvvvvU......
  ......CvvvvvvvvvvC......
  ......UvvvvvvvvvvU......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........KKK..KKK........
  .......KKKK..KKKK.......
  ........................
`);

const DEALER_FROZEN = frame(`
  ........................
  ........k......k........
  .......kKKKKKKKKk.......
  .......kOOOOOOOOk.......
  .......kOOOoWOOOk.......
  .......kOOOooOOOk.......
  .......kOOOOOOOOk.......
  .......kOOOOOOOOk.......
  .......kOOOOOOOOk.......
  .......kOOOOOOOOk.......
  ........kOOOOOOk........
  .........kOOOOk.........
  ........vCWWWWCv........
  ......UvvCWWWWCvvU......
  .....UvvvCWKKWCvvvU.....
  .....UvvvCWKKWCvvvU.....
  .....UvvvvCKKCvvvvU.....
  .....UvvvvvKKvvvvvU.....
  ......UvvvvKvvvvvU......
  ......CvvvvKvvvvvC......
  ......UvvvvvvvvvvU......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........KKK..KKK........
  .......KKKK..KKKK.......
  ........................
`);

const DEALER_MASKGRAB = frame(`
  ........................
  ........................
  ........................
  ...k......k.............
  ..kKKKKKKKKk............
  ..kOOOOOOOOk............
  ..kOOOoWOOOk............
  ..kOOOooOOOk............
  ..kOOOOOOOOk............
  ..UkOOOOOOkU............
  .UvvkOOOOkvvvU..........
  .UvvvvvvvvvvvvU.........
  UvvvvvKKvvvvvvvvC.......
  UvvvvvKKvvvvvvC.C.......
  .UvvvvvvvvvvC.C.........
  .UvvvvvvvvC.C...........
  ..UvvvvvvC.C............
  ..vUvvvvvvvvvC..........
  ...vUvvvvvvvC.C.........
  ...vvUvvvvvvvvC.........
  ....vvvU..UvvvvC.C......
  ...vvvU.....Uvvv........
  ..vvU........UvvC.C.....
  .vvU..........Uvv.......
  .vU............Uv.......
  KKK............vvC......
  KKKK...........KKK......
  ...............KKKK.....
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
`);

const DEALER_DAMAGE = frame(`
  ........................
  ..........k......k......
  ..........kKKKKKKk......
  .........kKKKKKKKKk.....
  ...o.....kKOOOOOOKk.....
  .........kKOOoWOOKk..o..
  .......o.kKOOooOOKk.....
  .........kKOOOOOOKk.....
  ..o......kKOOOOOOKk...o.
  ..........kKOOOOKk......
  ...........kKOOKk.......
  .........vCWWWWCv.......
  .o.....UvvCWWWWCvvU...o.
  ......UvvvCWKKWCvvvU....
  .....UvvvCWKKWCvvvU..o..
  .o...UvvvvCKKCvvvvU.....
  .....UvvvvvKKvvvvvU.o...
  ......UvvvvKvvvvvU......
  ......CvvvvKvvvvvC......
  ......UvvvvvvvvvvU......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  .......UvvvvvvvvU.......
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........vvU..Uvv........
  ........KKK..KKK........
  .......KKKK..KKKK.......
  ........................
  ........................
`);

const DEALER_DEFEAT_0 = frame(`
  ........................
  ........................
  ........................
  ........k......k........
  ........kKKKKKKk........
  .......kKKKKKKKKk.......
  .......kKOOOOOOKk.......
  .......kKOOoWOOKk.......
  .......kKOOOOOOKk.......
  ......UkKOOOOKkU........
  .....UvvkKOOKkvvU.......
  ....UvvvvCWWCvvvvU......
  ....UvvvvCWWCvvvvU......
  ...UvvvvvvKKvvvvvvU.....
  ...CvvvvvvKKvvvvvvC.....
  ...UvvvvvvvvvvvvvvU.....
  ...UvvvvvvvvvvvvvvU.....
  ....Uvvvvvvvvvvvvv......
  ....vUvvvvvvvvvvvU......
  .....vUvvvvvvvvUv.......
  ......vvUvvvvUvv........
  .......vvvvvvvv.........
  ......vvU......Uvv......
  .....vvU........Uvv.....
  ....KKK..........KKK....
  ...KKKK..........KKKK...
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
`);

const DEALER_DEFEAT_1 = frame(`
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ..v.....k......k.....v..
  ........kKKKKKKk........
  .v.....kKKKKKKKKk....v..
  .......kKOOOOOOKk.......
  ...v...kKOOOvWOOKk..v...
  .......kKOOOOOOKk.......
  ..v...UvkKOOOOKkvU..v...
  .....Uvvvvvvvvvvvvv.....
  ..v.Uvvvvvvvvvvvvvvv.v..
  ...UvvvvvvKKvvvvvvvvU...
  ..vvvvvvvvKKvvvvvvvvvv..
  .vUvvvvvvvvvvvvvvvvvUv..
  vvvUvvvvvvvvvvvvvvUvvv.v
  .v.vUvvvvvvvvvvvvUv.v...
  ..v..vvUvvvvvvUvv..v....
  .v.v...vvvvvvvv...v.v...
  ..v..v..v.vv.v..v...v...
  .v..v..v......v..v..v...
  ..v...v..v..v..v...v....
  .v..v...v....v...v..v...
  ..v..v.....v.....v..v...
  .v....v.v.....v.v...v...
  ..v.v.....v.v.....v.v...
  .v.....v.....v.....v....
  ..v..v.....v.....v..v...
  .v.....v.v.....v.v...v..
  ..v.v.....v.v.....v.v...
  .v.....v.....v.....v....
  ..v..v.....v.....v..v...
  .v.....v.v.....v.v...v..
  ........v.....v.........
  ........................
  ........................
  ........................
`);

// ---------- separate mask object (10x12) ----------
const MASK_WORN_0 = frame(`
  ..C....C..
  .kCCCCCCk.
  .kKCCCCKk.
  .kKcoWcKk.
  .kKcoocKk.
  .kKCCCCKk.
  .kKCoCCKk.
  .kKooooKk.
  .kKococKk.
  ..kKCCKk..
  ...kKKk...
  ...kkkk...
`);

const MASK_WORN_1 = frame(`
  ..C....C..
  .kCCCCCCk.
  .kWCCCCKk.
  .kWcoWcKk.
  .kWcoocKk.
  .kCWCCCKk.
  .kKCoCCKk.
  .kKooooKk.
  .kKococKk.
  ..kKCCKk..
  ...kKKk...
  ...kkkk...
`);

const MASK_FALLEN = frame(`
  ..........
  ..........
  ..........
  ...CCCC...
  ..CccccC..
  .CcccoccC.
  .CccoWcCk.
  .CcccoccC.
  ..CccccC..
  ...CCCC...
  ..dddddd..
  ...dddd...
`);

const MASK_SPIN_0 = frame(`
  ....kk....
  ...kCCk...
  ...kCCk...
  ...kCok...
  ...kCCk...
  ...kCCk...
  ...kWCk...
  ...kCCk...
  ...kCCk...
  ...kCCk...
  ...kCCk...
  ....kk....
`);

const MASK_SPIN_1 = frame(`
  ..kkkk....
  .kKCCCk...
  .kCccCk...
  .kCcoCk...
  .kCcoCk...
  .kCCcCk...
  .kCocCk...
  .kCccCk...
  .kKCCk....
  ..kCCk....
  ..kKk.....
  ..kk......
`);

// ---------- projectiles + muzzle flash ----------
const PARRY_BULLET_0 = frame(`
  ..YY..
  .YWWY.
  YWWWWY
  YWWWWY
  .YWWY.
  ..YY..
`);

const PARRY_BULLET_1 = frame(`
  .VYYV.
  VYWWYV
  YWWWWY
  YWWWWY
  VYWWYV
  .VYYV.
`);

const NORMAL_BULLET = frame(`
  .cc.
  cDDc
  cDDc
  .dd.
`);

const MUZZLE_FLASH = frame(`
  ...MM...
  ..MWWM..
  .MWYYWM.
  MWYWWYWM
  MWYWWYWM
  .MWYYWM.
  ..MWWM..
  ...MM...
`);

export const ONE_EYED_DEALER_SPRITES: SpriteDef = {
  key: "one-eyed-dealer",
  w: 24,
  h: 40,
  frames: [
    DEALER_IDLE_0, DEALER_IDLE_1, DEALER_MOVE_0, DEALER_MOVE_1, DEALER_AIM,
    DEALER_FIRE, DEALER_TELE_0, DEALER_TELE_1, DEALER_REAPPEAR, DEALER_STRIKE,
    DEALER_FROZEN, DEALER_MASKGRAB, DEALER_DAMAGE, DEALER_DEFEAT_0, DEALER_DEFEAT_1,
  ],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 3, repeat: -1 },
    { key: "move", frames: [2, 3], frameRate: 8, repeat: -1 },
    { key: "aim", frames: [4], frameRate: 1, repeat: 0 },
    { key: "fire", frames: [5], frameRate: 1, repeat: 0 },
    { key: "teleport", frames: [6, 7], frameRate: 10, repeat: 0 },
    { key: "reappear", frames: [8], frameRate: 1, repeat: 0 },
    { key: "strike", frames: [9], frameRate: 1, repeat: 0 },
    { key: "frozen", frames: [10], frameRate: 1, repeat: 0 },
    { key: "maskgrab", frames: [11], frameRate: 1, repeat: 0 },
    { key: "damage", frames: [12], frameRate: 1, repeat: 0 },
    { key: "defeat", frames: [13, 14], frameRate: 4, repeat: 0 },
  ],
};

export const DEALER_MASK_SPRITES: SpriteDef = {
  key: "boss-one-eyed-dealer-mask",
  w: 10,
  h: 12,
  frames: [MASK_WORN_0, MASK_WORN_1, MASK_FALLEN, MASK_SPIN_0, MASK_SPIN_1],
  anims: [
    { key: "worn", frames: [0, 1], frameRate: 3, repeat: -1 },
    { key: "fallen", frames: [2], frameRate: 1, repeat: 0 },
    { key: "spin", frames: [3, 4], frameRate: 12, repeat: -1 },
  ],
};

export const DEALER_PARRY_BULLET_SPRITES: SpriteDef = {
  key: "boss-one-eyed-dealer-pbullet",
  w: 6,
  h: 6,
  frames: [PARRY_BULLET_0, PARRY_BULLET_1],
  anims: [{ key: "glow", frames: [0, 1], frameRate: 10, repeat: -1 }],
};

export const DEALER_BULLET_SPRITES: SpriteDef = {
  key: "boss-one-eyed-dealer-bullet",
  w: 4,
  h: 4,
  frames: [NORMAL_BULLET],
};

export const DEALER_MUZZLE_SPRITES: SpriteDef = {
  key: "boss-one-eyed-dealer-muzzle",
  w: 8,
  h: 8,
  frames: [MUZZLE_FLASH],
};

export const ONE_EYED_DEALER_KIT: SpriteDef[] = [
  ONE_EYED_DEALER_SPRITES,
  DEALER_MASK_SPRITES,
  DEALER_PARRY_BULLET_SPRITES,
  DEALER_BULLET_SPRITES,
  DEALER_MUZZLE_SPRITES,
];
