import { frame } from "../grid";
import type { SpriteDef } from "../textures";
import type { BossId } from "../../ids";

// Task 14 — The Glitch Toad, 48x64. A giant corrupted toad-beetle-mushroom:
// a green mushroom cap (G outer dome / g gill underside) sits on its back like
// a shell, over a bloated dark beetle body (k, with a D shell-seam for volume
// and a dotted thorax line above the legs). Two big white eyes (W/O) read cute
// at rest; the closed mouth is a thin toothy grin (X/W) until it cracks open
// into a corrupted X/R/W maw for its attacks — cute-menacing, matching the
// Bugling's mushroom-cap-beetle motif (art/sprites/enemies1.ts) scaled up to
// boss size. R/r glitch patches fleck the cap and belly, plus a thin
// mid-frame glitch slice line, selling the "corrupted" theme. Four stubby
// G/g legs plant it on the arena floor.
//
// Anims: idle (2f, breathing/glitch-shift), attack (2f, maw cracks open wide
// with a jagged corrupted tongue -- the lunge telegraphed by "player-hit" fx),
// hurt (1f, wide eyes + cracks -- "boss-hit" fx), defeat (3f, a dissolve from
// buckling legs -> crumbling body -> a sparse fading remnant that CombatBackdropScene
// holds on the last frame after "combat:over" victory).

const IDLE_0 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGrrGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGrrGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGrrGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........ggggggggggggggggggggggggggggg..........
  ...........kkkkkkkkkkkkkkkkkkkkkkkkkk...........
  ............kkkRkkkkRkkkkRkkkkRkkkkR............
  .............kkkkkkkkkkkkkkkkkkkkkk.............
  ............WWWWkkkkkkkkkkkkkkkkWWWW............
  ...........WWWWWWkkkkkkkkkkkkkkWWWWWW...........
  ..........WWWWWWWWkkkkkkkkkkkkWWWWWWWW..........
  ..........WWWOOWWWkkkkkkkkkkkkWWWOOWWW..........
  ..........WWWOOWWWkkkkkkkkkkkkWWWOOWWW..........
  .........kWWWWWWWWkkkkkkkkkkkkWWWWWWWWk.........
  ........kkDWWWWWWkkkkkkkkkkkkkkWWWWWWkkk........
  .......kkDDkWWWWkkkkkkkkkkkkkkkkWWWWkkkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kDDXXWXXXWXXXWXXXWXXXWXXXWXXXWXXXWXXkkkk....
  ...kkDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkkkkk...
  ...kkDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkkkkk...
  ...kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkRRRkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkRRRkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkDkDkDkDkDkDkrrDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkkkkkkkkkkkkkkkkrrkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgkkkGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  .......GGGGGGGkkkkkkkkkkkGGGGGGkkkkkkkkk........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......gggggggkkGGGGGGkkkggggggkkGGGGGGG........
  .......gggggggkkggggggkkkggggggkkggggggg........
  .......ggggggg..ggggggkkkgggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  ................................................
`);

// idle f1: cap flecks drift, teeth-grin narrows a hair, legs shift weight,
// a fresh pair of belly flecks -- the quiet "breathing" glitch-shift.
const IDLE_1 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............rGGGGGGGGGGGGGGGGGGGGG.............
  ............rrGGGGGGGGGGGGRRRGGGGGGG............
  ...........GGGGGGGGGGGGGGGRRRGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........ggggggggggggggggggggggggggggg..........
  ...........kkkkkkkkkkkkkkkkkkkkkkkkkk...........
  ............kkkkkkkkkkkkkkkkkkkkkkkk............
  .............kkrkkkkrkkkkrkkkkrkkkk.............
  ............WWWWkkkkkkkkkkkkkkkkWWWW............
  ...........WWWWWWkkkkkkkkkkkkkkWWWWWW...........
  ..........WWWWWWWWkkkkkkkkkkkkWWWWWWWW..........
  ..........WWWOOWWWkkkkkkkkkkkkWWWOOWWW..........
  ..........WWWOOWWWkkkkkkkkkkkkWWWOOWWW..........
  .........kWWWWWWWWkkkkkkkkkkkkWWWWWWWWk.........
  ........kkDWWWWWWkkkkkkkkkkkkkkWWWWWWkkk........
  .......kkDDkWWWWkkkkkkkkkkkkkkkkWWWWkkkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ...kkDDXXWXXXXWXXXXWXXXXWXXXXWXXXXWXXXXXkkkkk...
  ...kkDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkkkkk...
  ...kDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkkkk...
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkrrkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkrrDkDkDkDkDkDkDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgkkkGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  ........kkkkkkkkGGGGGGkkkkkkkkkkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkggggggkkkGGGGGGkkggggggg........
  .......gggggggkkggggggkkkggggggkkggggggg........
  .......ggggggg..ggggggkkkgggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  ................................................
`);

// attack f0: eyes narrow to angry slits, the grin cracks halfway open.
const ATTACK_0 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............rGGGGGGGGGGGGGGGGGGGGG.............
  ............rrGGGGGGGGGGGGRRRGGGGGGG............
  ...........GGGGGGGGGGGGGGGRRRGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........ggggggggggggggggggggggggggggg..........
  ...........kkkkkkkkkkkkkkkkkkkkkkkkkk...........
  ............kkkkkkkkkkkkkkkkkkkkkkkk............
  .............kkkkkkkkkkkkkkkkkkkkkk.............
  ............WWWWkkkkkkkkkkkkkkkkWWWW............
  ...........WWWWWWkkkRkkkRkkkRkkWWWWWW...........
  ..........WWWWWWWWkkkkkkkkkkkkWWWWWWWW..........
  ..........WOOOOOOWkkkkkkkkkkkkWOOOOOOW..........
  ..........WOOOOOOWkkkkkkkkkkkkWOOOOOOW..........
  .........kWWWWWWWWkkkkkkkkkkkkWWWWWWWWk.........
  ........kkDWWWWWWkkkkkkkkkkkkkkWWWWWWkkk........
  .......kkDDkWWWWkkkkkkkkkkkkkkkkWWWWkkkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkk.....
  ....kkDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk....
  ....kDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkk....
  ...kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk...
  ...kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk...
  ...kDXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkk...
  ..kkDXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkrrkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkrrDkDkDkDkDkDkDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgkkkGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  .......GGGGGGGkkkkkkkkkkkGGGGGGkkkkkkkkk........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......gggggggkkGGGGGGkkkggggggkkGGGGGGG........
  .......gggggggkkggggggkkkggggggkkggggggg........
  .......ggggggg..ggggggkkkgggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  ................................................
`);

// attack f1: the maw gapes at full width, a jagged corrupted tongue (Data
// Lick) lashes out below it -- the telegraphed lunge, played on "player-hit".
const ATTACK_1 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGrrGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGrrGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGrrGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........ggggggggggggggggggggggggggggg..........
  ...........krkkkrkkkrkkkrkkkrkkkrkkkr...........
  ............kkkkkkkkkkkkkkkkkkkkkkkk............
  .............kkkkkkkkkkkkkkkkkkkkkk.............
  ............WWWWkkkkkkkkkkkkkkkkWWWW............
  ...........WWWWWWkkkkkkkkkkkkkkWWWWWW...........
  ..........WWWWWWWWkkkkkkkkkkkkWWWWWWWW..........
  ..........WOOOOOOWkkkkkkkkkkkkWOOOOOOW..........
  ..........WOOOOOOWkkkkkkkkkkkkWOOOOOOW..........
  .........kWWWWWWWWkkkkkkkkkkkkWWWWWWWWk.........
  ........kkDWWWWWWkkkkkkkkkkkkkkWWWWWWkkk........
  .......kkDDkWWWWkkkkkkkkkkkkkkkkWWWWkkkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkk.....
  ....kkDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk....
  ....kDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkk....
  ...kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk...
  ...kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk...
  ...kDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkk...
  ..kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk..
  ..kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk..
  ..kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk..
  ..kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk..
  ..kDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkk..
  ..kkDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkkk..
  ..kkDXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk..
  ..kkDXXXWXXWXXRRRWXXWXXWXXWXXWXXWXXWXXWXXXkkkk..
  ..kkDDkkkkkkkkRRRkkkkkkkrRRrRkkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkkkkkkkRRrRRkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkDkDkrRRrRkDkrrDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkkkkkkkkRRrRRkkkrrkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkkkkkkkkkRRrRRkkkkkkkkkkkkkkk....
  ....kkDDkkkkkkkkkkkkkkkkRrRRrkkkkkkkkkkkkkkk....
  .....kDDkkkkkkkkkkkkkrRRrRRrkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkRRrRRrRkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgrRRGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  ........kkkkkkkkGGGGGGkkkkkkkkkkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkggggggkkkGGGGGGkkggggggg........
  .......gggggggkkggggggkkkggggggkkggggggg........
  .......ggggggg..ggggggkkkgggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  ................................................
`);

// hurt: a scatter of bright flash pixels flare across the shell, eyes go wide
// and startled, red cracks web the cap/body -- the "boss-hit" reaction.
const HURT_0 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........ggggggggggRggggggggggggggggggg.........
  ........ggggggggggggRggggggggggggggggggg........
  ........gggggggggggggRgggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........gggRggggggggggggggggggggggggg..........
  ...........kkRkkkkkkkkkkkkdkkkkkkkkkk...........
  ............kkkkkkkkkkkkkdkkkkkdkkkk............
  .............kkdkkkkkkkkkkkkkkkkkRk.............
  ............WWWWkkkkkkkkkkkkkkkkWWRW............
  ...........WWWWWWkkkkkkkkkkkkkkWWWWWW...........
  ..........WWWOWWWWkkkkkkkkkkkkWWWOWWWW..........
  ..........WWWOWWWWkkkkkkkkkkkkWWWOWWWW..........
  ..........WWWWWWWWkkkkkkkkkkkkWWWWWWWW..........
  .........kWWWWWWWWkkkkkkkkkkkkWWWWWWWWk.........
  ........kkDWWWWWWkkkdkkkkkkkkkkWWWWWWkkk........
  .......kkDDkWWWWkkkkdkkkkkkkkkkkWWWWkkkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkk.....
  ....kkDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk....
  ....kDXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXkkk....
  ...kdDXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXXkkkk...
  ...kkDXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXXkkkk...
  ...kDDkkkkkkkkkkkkkkkkkkkdkkkkkkkkkkkkkkkkkkk...
  ..kkDDkkdkkkkkkkkkkkkkdkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkdkkkkkkkkkkkkkkkkkkkkkkkkdkkkkkkkdkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkdkkkkkkkkkkkkkkdkkkk..
  ..kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDdkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkRkdkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkkkkkdkkkkkRkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkDkDkDkDkDkDRDkDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkRkkkkkkkkkkkkkkkdkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkRkkkkkkkkkkkkkkkkkkkkkkkkkkd....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkd....
  .....kDDkkkkkkkkdkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgkkkGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  .......GGGGGGGkkkkkkkkkkkGGGGGGkkkkkkkkk........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......GGGGGGGkkGGGGGGkkkGGGGGGkkGGGGGGG........
  .......gggggggkkGGGGGGkkkggggggkkGGGGGGG........
  .......gggggggkkggggggkkkggggggkkggggggg........
  .......ggggggg..ggggggkkkgggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  .......ggggggg..gggggg...gggggg..ggggggg........
  ................................................
`);

// defeat f0: eyes go X, cracks web the shell, the outer leg pair buckles --
// the toad still mostly whole, but visibly failing.
const DEFEAT_0 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........ggggggggggXggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........gggXggggggggggggggggggggggggg..........
  ...........kkkkkkkkkkkkkkkkkkkkkkkkkk...........
  ............kkkkkkkkkkkkkkkkkkkkkkkk............
  .............kkkkkkkkkkkkkkkkkkkkXk.............
  ..........X....kkXkkkkkkkkkkkkXkk....X..........
  ...........X....XkkkkkkkkkkkkkkX....X...........
  ............X.kXkkkkkkkkkkkkkkkkXk.X............
  ............kXXDkkkkkkkkkkkkkkkkkXXk............
  ...........kDXXkkkkkkkkkkkkkkkkkkXXkk...........
  .........kkDXkkXkkkkkkkkkkkkkkkkXkkXkkk.........
  ........kkDXkkkkXkkkkkkkkkkkkkkXkkkkXkkk........
  .......kkDXkkkkkkXkkkkkkkkkkkkXkkkkkkXkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkkkkkkkkkkkXkkkkkkkkkkkkkkkkk......
  .....kDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkk.....
  ....kkDXXWXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXkkkk....
  ....kDXXXXXXWXXWXXWXXWXXWXXWXXWXXWXXWXXXXkkk....
  ...kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkXkkkkkkkkk..
  ..kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kkDDkkkkkkkkkkkkkkkkkkkkkkXkkkkkkkkkkkkkkkkk..
  ...kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ...kDDDkDkDkDkDkDkDkDkDkDkDkDkDkDkDkDkDkDkDkk...
  ...kkDDkkkkkkkkXkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kkGgkkkGgkkkGgkkkGgkkkGgkkkGgkkkGgkk......
  .......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......
  .............GkkkkkkkkkkkGGGGGGkkk..............
  .............GkkGGGGGGkkkGGGGGGkkG..............
  .............GkkGGGGGGkkkGGGGGGkkG..............
  .............gkkGGGGGGkkkggggggkkG..............
  .............gkkggggggkkkggggggkkg..............
  .............g..ggggggkkkgggggg..g..............
  .............g..gggggg...gggggg..g..............
  .............g..gggggg...gggggg..g..............
  ................................................
`);

// defeat f1: legs and underbelly gone outright, the chest crumbles into
// scattered glitch motes -- the corruption is consuming it.
const DEFEAT_1 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........ggggggggggggggggggggggggggggg..........
  ...........kkkkkkkkkkkkkkkkkkkkkkkkkk...........
  ............kkkkkkkkkkkkkkkkkkkkkkkk............
  .............kkkkkkkkkkkkkkkkkkkkkk.............
  ..........X....kkXkkkkkkkkkkkkXkk....X..........
  ...........X....XkkkkkkkkkkkkkkX....X...........
  ............X.kXkkkkkkkkkkkkkkkkXk.X............
  ............kXXDkkkkkkkkkkkkkkkkkXXk............
  ...........kDXXkkkkkkkkkkkkkkkkkkXXkk...........
  .........kkDXkkXkkkkkkkkkkkkkkkkXkkXkkk.........
  ........kkDXkkkkXkkkkkkkkkkkkkkXkkkkXkkk........
  .......kkDXkkkkkkXkkkkkkkkkkkkXkkkkkkXkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .......D.k..kkkX.kk....kRkrk.rk.kkkkkk.k.r......
  .....RDDXk...kX.k..k.kkR.k.k.kXk......Rk..k.....
  ....k.D..k.R.kkkrk.kr.kkkk.k.kk....k..k.........
  .....DD.k.k.....rkk.k...k.Rkkk.k...kk.k.kk......
  ....RDDkk....k.kk...krkkkrR..krkkk.kk...r.k.....
  ...kR.....kkkkr.kk.Xkkk.k.k.....k.kkk.kkkrkX....
  ....XD..Xkk.k.R.k.k.k.kk..k.rkk.kkk..k.kk.k.k...
  ..k.XDk.k.kk.kk.r...k....k.X.......Rk..kkkk.....
  ...r..kkkk..kk.k.Rk.Xk.kXk.k..k..k.rk..kk.k.k...
  ..kk.Dkkkkkk.kk..k...kk.k..kk.kkkRRR.kk....kkr..
  ..r.D.kkkRk.k..kkkk.kr.kk..k.kkkkkkkkk..kR..kk..
  .....k.XX..Xkkk.kk.k.k....k..k.k.kk...k.k.kkXk..
  ...k.Dk.kX..kkkkkk...k.k.k.kkkk.Xk.kk...kk.k....
  .....D.rk.k.kkXr.k..kkkkRXkRkk.k.rk......k..kk..
  ..k.D...kr.k..krk.k..k..k....kk.kkRkkk..kk..kk..
  ...kD.kRXkk.kXR....r..k.kkk.k.k....k.kk.Rrkk....
  ...kDDk..k.kkX..k.kXR.kkkkkk.kkkkkk.k..kkX.k....
  ...kD.D...DXDRrR..Dk.k....D.D.DkrRDkD..k....X...
  ....k..kk..k.kkkkXk..k......Rrk.kk.k.r.Xkk......
  ....R.R.k..k..k.k.kkkk.kk.kRkrkXk.k.k.k..k......
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
`);

// defeat f2 (held): only the cap and hollow X eyes remain, trailing a thin
// scatter of fading motes -- CombatBackdropScene holds this frame after the
// dissolve anim finishes, so it stays crisp and legible under the victory panel.
const DEFEAT_2 = frame(`
  ................................................
  ................................................
  .................GGGGGGGGGGGGGG.................
  ...............GGGGGGGGGGGGGGGGGG...............
  .............GGGGGGGGGGGGGGGGGGGGGG.............
  ............GGGGGGGGGGGGGGGGGGGGGGGG............
  ...........GGGGGGGGGGGGGGGGGGGGGGGGGG...........
  ..........GGGGGGGGGGGGGGGGGGGGGGGGGGGG..........
  .........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........
  .........gggggggggggggggggggggggggggggg.........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  ........gggggggggggggggggggggggggggggggg........
  .........gggggggggggggggggggggggggggggg.........
  .........gggggggggggggggggggggggggggggk.........
  .........Rg.g....ggggg..gggg...gg...gg..........
  ...........k.rkkkk.kkkk..kkkkk..kkkkk...........
  ............k.k..r.k.kkkrkkk.kkkkXkk............
  ..............kkkk.kkkkkkkkRkXk.kkk.............
  ..........X....kkXkkkkkkkkkkkkXkk....X..........
  ...........X....XkkkkkkkkkkkkkkX....X...........
  ............X.kXkkkkkkkkkkkkkkkkXk.X............
  ............kXXDkkkkkkkkkkkkkkkkkXXk............
  ...........kDXXkkkkkkkkkkkkkkkkkkXXkk...........
  .........kkDXkkXkkkkkkkkkkkkkkkkXkkXkkk.........
  ........kkDXkkkkXkkkkkkkkkkkkkkXkkkkXkkk........
  .......kkDXkkkkkkXkkkkkkkkkkkkXkkkkkkXkkk.......
  ......kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  ......kDDkkkkkRkkkkkkkkkkkkkkkkkkkkkkkkkkk......
  .....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....
  ....kkDDkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ....kDDkkkkkkkkkkkkkkkkkkkkkkkkkkrkkkkkkkkkk....
  ................................................
  ................................................
  ....................R...........................
  ...............................r................
  ................................................
  ..........................r.....................
  ................................................
  ................................................
  .................R..............................
  ................................................
  ................................................
  .......................R........................
  ................................................
  ................................................
  .............................r..................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
`);

export const GLITCH_TOAD_SPRITES: SpriteDef = {
  key: "boss-glitch-toad",
  w: 48,
  h: 64,
  frames: [IDLE_0, IDLE_1, ATTACK_0, ATTACK_1, HURT_0, DEFEAT_0, DEFEAT_1, DEFEAT_2],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 3, repeat: -1 },
    { key: "attack", frames: [2, 3], frameRate: 8, repeat: 0 },
    { key: "hurt", frames: [4], frameRate: 1, repeat: 0 },
    { key: "defeat", frames: [5, 6, 7], frameRate: 6, repeat: 0 },
  ],
};

export const BOSS_SPRITES: SpriteDef[] = [GLITCH_TOAD_SPRITES];

// bossId -> its SpriteDef, for CombatBackdropScene to look up (mirrors
// tilesetFor's theme -> tile-sprite lookup in tiles-fields.ts). Bosses without
// an authored sprite yet fall through to undefined, and the scene keeps
// rendering the placeholder anchor ring instead.
export const BOSS_SPRITE_BY_ID: Partial<Record<BossId, SpriteDef>> = {
  "glitch-toad": GLITCH_TOAD_SPRITES,
};
