// NOTE: kit char `I` (spectral halo white) remapped → `j` in-repo (I = wet
// slate, Task 40). Art pixels only.
import { frame } from "../grid";
import type { SpriteDef } from "../textures";

// THE VEILED ARCHER — World 1-4 boss (brief §"World 1-4 Boss: The Veiled Archer").
// Hooded woman, face hidden, longbow, weightless; pale silver/spectral arrows.
// Cloth silver ramp C/c/d/D, face cavity K, violet spectral v/V/U, cold bow B/b,
// spectral halo I (proposed). 20x32 per repo boss convention.

const IDLE0 = frame(`
  ....................
  ......dCd...........
  .....dCCCd..........
  ....dCCKKCd.........
  ....dCKKKKd.........
  ....dCKvKKd.........
  ....dCKKKKd.........
  ....dCCKscd.........
  ...dcCCCccd.........
  ...dcCCCCcd.....b...
  ..dcCCCCCCcd...c.B..
  ..dcCCCCCCcd..c..B..
  ..dcCCCCCCcd.c....B.
  ..dcCCCCCCcd.c....B.
  ..dcCCCCCCvdc.....B.
  ...dcCCCCCcWWWWWWjB.
  ...dcCCCCCvCcCCc..B.
  ...dcCCCCCcd.c.c..B.
  ...dcCCCCccd.c....B.
  ...dcCCCCcd...c..B..
  ...dcCCCCcd....c.B..
  ...dcCCCccd.....b...
  ..dcCCCCccd.........
  ..dcCCCCcd..........
  ...dcCCCcd..........
  ...dcCCccd..........
  ...dccCcd...........
  ..dccd.dd...........
  ..dcd...v...........
  .vcd................
  v..d.............v..
  ....v...............
`);
const IDLE1 = frame(`
  ....................
  ......dCd...........
  .....dCCCd..........
  ....dCCKKCd.........
  ....dCKKKKd.........
  ....dCKVKKd.........
  ....dCKKKKd.........
  ....dCCKscd.........
  ...dcCCCccd.........
  ...dcCCCCcd.....b...
  ..dcCCCCCCcd...c.B..
  ..dcCCCCCCcd..c..B..
  ..dcCCCCCCcd.c....B.
  ..dcCCCCCCcd.c....B.
  ..dcCCCCCCvdc.....B.
  ...dcCCCCCcWWWWWWjB.
  ...dcCCCCCvCcCCc..B.
  ...dcCCCCCcd.c.c..B.
  ...dcCCCCccd.c....B.
  ...dcCCCCcd...c..B..
  ...dcCCCCcd....c.B..
  ...dcCCCccd.....b...
  ..dcCCCCccd.........
  ..dcCCCCcd..........
  ...dcCCCcd..........
  ...dcCCccd..........
  ...dccCcd...........
  ..dccd.dv...........
  ..dcd...............
  .vcd.............v..
  v..d................
  ...vv...........v...
`);
const AIM = frame(`
  ....................
  ......dCd...........
  .....dCCCd..........
  ....dCCKKCd.........
  ....dCvKKKd.........
  ....dCKVKKd.........
  ....dCKKKKd.........
  ....dCCKscd.........
  ...dcCCCccd.........
  ...dcCCCCcd.....b...
  ..dcCCCCCCcd...c.B..
  ..dcCCCCCCcd..c..B..
  ..dcCCCCCCcd.c.j..B.
  ..dcCCCCCCcd.c....B.
  ..dcCCCCvCcdc.....B.
  ...dcCCCCjjjjjjjjjBj
  ...dcCCCvCcCcCCc..B.
  ...dcCCCCCcd.c.c..B.
  ...dcCCCCccd.c.j..B.
  ...dcCCCCcd...c..B..
  ...dcCCCCcd....c.B..
  ...dcCCCccd.....b...
  ..dcCCCCccd.........
  ..dcCCCCcd..........
  ...dcCCCcd..........
  ...dcCCccd..........
  ...dccCcd...........
  ..dccd.dd...........
  ..dcd...v...........
  .vcd................
  v..d.............v..
  ....v...............
`);
const RELEASE = frame(`
  ....................
  ......dCd...........
  .....dCCCd..........
  ....dCCKKCd.........
  ....dCKKKKd.........
  ....dCKvKKd.........
  ....dCKKKKd.........
  ....dCCKscd.........
  ...dcCCCccd.........
  ...dcCCCCcd.....B...
  ..dcCCCCCCcd....cB..
  ..dcCCCCCCcd....c.B.
  ..dcCCCCCCcd....c.B.
  ..dcCCCCCCcd....c.B.
  ..dcCCCCCCcdc...cjB.
  ...dcCCCCCcdc..jcvVj
  ...dcCCCCCcdc...cjB.
  ...dcCCCCCcd....c.B.
  ...dcCCCCccd....c.B.
  ...dcCCCCcd.....c.B.
  ...dcCCCCcd.....cB..
  ...dcCCCccd.....B...
  ..dcCCCCccd.........
  ..dcCCCCcd..........
  ...dcCCCcd..........
  ...dcCCccd..........
  ...dccCcd...........
  ..dccd.dd...........
  ..dcd...v...........
  .vcd................
  v..d.............v..
  ....v...............
`);
const BACKSTEP = frame(`
  ....................
  .....dCd............
  ....dCCCd...........
  ...dCCKKCd..........
  ...dCKKKKd..........
  ...dCKvvKd..........
  ...dCKKKKd..........
  ...dCCKscd..........
  ..dcCCCccd......b...
  ..dcCCCCcd.....c.B..
  .dcCCCCCCcd...c..B..
  .dcCCCCCCcd..c....B.
  .dcCCCCCCcd..c....B.
  .dcCCCCCCcv.c.....B.
  .dcCCCCCCcdWWWWWWjB.
  ..dcCCCCCcvCcCCc..B.
  ..dcCCCCCcd..c.c..B.
  ..dcCCCCCcd..c....B.
  ..dcCCCCccdd..c..B..
  ..dcCCCCcdd....c.B..
  ..dcCCCCcddd....b...
  ..dcCCCccdd.........
  vdcCCCCccddd........
  .dcCCCCcd.d.........
  .vdcCCCcd.dd........
  ..dcCCccd.d.........
  ..dccCcd..dd.v......
  .dccd.dd..d.........
  .dcd...v......v.....
  vcd.................
  ..d.............v...
  ...v................
`);
const VOLLEY0 = frame(`
  ....................
  ......dCd...........
  .....dCCCd..........
  ....dCCKKCd.........
  ....dCKKKKd..BB.....
  ....dCKvKKd....B....
  ....dCKKKKd.....WWj.
  ....dCCKscd..W.WB...
  ...dcCCCccdWW....B..
  ...dcCCCCcd......B..
  ..dcCCCCCCcd....B...
  ..dcCCCCCCcWW.WWW.Wj
  ..dcCCCCCCcd........
  ..dcCCCCCCcd........
  ..dcCCCCCCcW........
  ...dcCCCCCcdWW......
  ...dcCCCCCcd...WW...
  ...dcCCCCCcd.....Wj.
  ...dcCCCCccd........
  ...dcCCCCcd.........
  ...dcCCCCcd.........
  ...dcCCCccd.........
  ..dcCCCCccd.........
  ..dcCCCCcd..........
  ...dcCCCcd..........
  ...dcCCccd..........
  ...dccCcd...........
  ..dccd.dd...........
  ..dcd...v...........
  .vcd................
  v..d.............v..
  ....v...............
`);
const VOLLEY1 = frame(`
  ....................
  ......dCd...........
  .....dCCCd..........
  ....dCCKKCd.........
  ....dCKKKKd.........
  ....dCKVKKd.........
  ....dCKKKKd.........
  ....dCCKscd.........
  ...dcCCCccd.........
  ...dcCCCCcd.........
  ..dcCCCCCCcd........
  ..dcCCCCCCcd........
  ..dcCCCCCCcWW.WWW.Wj
  ..dcCCCCCCcd....B...
  ..dcCCCCCCcd.....B..
  ...dcCCCCCcW....B...
  ...dcCCCCCcdWW..B...
  ...dcCCCCCcd...WW...
  ...dcCCCCccW.BB..Wj.
  ...dcCCCCcd.W.......
  ...dcCCCCcd..W......
  ...dcCCCccd...W.....
  ..dcCCCCccd....W.W..
  ..dcCCCCcd........j.
  ...dcCCCcd..........
  ...dcCCccd..........
  ...dccCcd...........
  ..dccd.dd...........
  ..dcd...v...........
  .vcd................
  v..d.............v..
  ....v...............
`);
const VULN0 = frame(`
  ....................
  ...vd...............
  ..dCCd..............
  .dCCKCd.............
  .dCKKKCd............
  .dCKvvKd............
  .dCKKKcd............
  .dCCKscd............
  ..dCCCccd...........
  ..dcCCCCd...........
  ..dcCCCCcd..........
  .dcCCCCCCd..........
  .dcCCCCCCcd.........
  .dcCCCCCCcd.........
  .dcCCCCCCcd.........
  ..dcCCCCcd..........
  ..dcCCCCcd..........
  ..dcCCCCcd..........
  ..dcCCCccd..........
  .dcCCCCccd..........
  .dcCCCCcd...........
  .dcCCCccd..bBBBb....
  ..dcCCcd...bB..b....
  ..dcCccd...b........
  ..dccdcd............
  .dccd.dd............
  .dcd...v............
  vcd...v.............
  v.d.................
  .v..............v...
  ...v............v...
  ....................
`);
const VULN1 = frame(`
  ....................
  ...vd...............
  ..dCCd..............
  .dCCKCd.............
  .dCKKKCd............
  .dCKvvKv............
  .dCKKKcd............
  .dCCKscd............
  ..dCCCccd...........
  ..dcCCCCd...........
  ..dcCCCCcd..........
  .dcCCCCCCj..........
  .dcCCCCCCcj.........
  .dcCCCCCCcj.........
  .dcCCCCCCcd.........
  ..dcCCCCcd..........
  ..dcCCCCcd..........
  ..dcCCCCcj..........
  ..dcCCCccd..........
  .dcCCCCccd..........
  .dvCCCCcd...........
  .dcCCCccd..bBBBb....
  ..dcCCcd...bB..b....
  ..dcCccd...b........
  ..dccdcd............
  .dccd.dd....v.......
  .dcv...v............
  vcd...v.............
  v.d.............v...
  .v..............v...
  ...v............v...
  ....................
`);
const FLINCH = frame(`
  ....................
  .....dCd............
  ....dCCCd...........
  ...dCCKKCv..........
  ...dCKKKKdjv........
  ...dCKVKKd..........
  ...dCKKKKd...v......
  ...dCCKscd..v.......
  ..dcCCCccd..........
  ..dcCCCCcd..v.......
  .dcCCCCCCcd...j.....
  .dcCCCCCCcd...v.....
  .dcCCCCCCcd.........
  .dcCCCCCCcdv........
  .dcCCCCCCcd.........
  ..dcCCCCCcd..v......
  ..dcCCCCCcd.........
  ..dcCCCCCcd.v.......
  ..dcCCCCccd.........
  ..dcCCCCcd..........
  ..dcCCCCcdv.........
  ..dcCCCccd..........
  .dcCCCCccd..........
  .dcCCCCcd...........
  ..dcCCCcd...........
  ..dcCCccd...........
  ..dccCcd............
  .dccd.dd............
  .dcd...v............
  vcd.................
  ..d.............v...
  ...v................
`);
const VANISH0 = frame(`
  .......v............
  ......dCd...........
  .....dCvjd..........
  ....dCvKKCd.........
  ....dCKvKKd.........
  ....dCKvKKd.........
  ....dCKvKKd.........
  ....dCvKscd.........
  ...dvCCvvcd.........
  ...dcCjCCcd.........
  ..dcvCCvvCcd........
  ..dcCCvCCCvd........
  ..dcvCCCjCcd........
  ..dcCCvCCCvd........
  ..dcvCCCvCcd........
  ...dcCvCCCjd........
  ...djCCCvCcd........
  ...dcCvCCCvd........
  ...dvCCCvccd........
  ...dcCjCCcd.........
  ...dvCCCvcd.........
  ...dcCvCccd.........
  ..dcvCCCjcd.........
  ..dcCCvCcd..........
  ...dvCCCvd..........
  ...dcCvccd..........
  ...djcCcd...........
  ..dccd.dd...........
  ..dcd...v...........
  .vvd............v...
  v..d.............v..
  ...vv...............
`);
const VANISH1 = frame(`
  ....................
  ......v.............
  ......j.............
  ......vv............
  ......j.............
  ......v.........v...
  ......jv............
  ......v........v....
  ......j.............
  ......vv............
  ......j..........v..
  ......v.............
  ......jv............
  ......v.............
  ......j.............
  ......vv............
  ......j.............
  ......v.............
  ......jv............
  ......v.............
  ..v...j.............
  ......vv............
  ......j.............
  .v....v.............
  ......jv............
  ......v.............
  ..................v.
  ....................
  ....v...............
  ....................
  ..........v.........
  ....................
`);
const DEFEAT0 = frame(`
  ....................
  ......djd...........
  .....djCjd..........
  ....djCKKjd.........
  ....dCKKKKd.........
  ....djKjKKd.........
  ....dCKKKKd.........
  ....djCKsvd.........
  ...dvCjCvcd.........
  ...dcjCjCvd.........
  ..dcjCjCjCjd........
  ..dvCjCjCjcd........
  ..dcjCjCjCvd........
  ..dvCjCjCjcd........
  ..dcjCjCjjvd........
  ...dcjCjCjcd........
  ...dvCjCjCvd........
  ...dcjCjCjcd........
  ...dvCjCjcjd........
  ...dcjCjCvd.........
  ...dvCjCjcd.........
  ...dcjCjcvd.........
  ..dcjCjCvcd.........
  ..dvCjCjcd..........
  ...dvCjCvd..........
  ...dcjCvcd..........
  ...dvcjcd...........
  ..dvcd.dd...........
  ..dcd...v...........
  .vcd................
  v..d.............v..
  ....v...............
`);
const DEFEAT1 = frame(`
  ....................
  ......dCd...........
  .....dvvvd..........
  ....dvvKKvd.........
  ....dCKKKKd.........
  ....dvjvKKd.........
  ....dvKKKKd.........
  ....dCCKscd.........
  ...dvvvvvvd.........
  ...dvvjvvvd.........
  ..dcCCCCCCvd........
  ..dvvvvvvvvd........
  ..djvvvvjvvd........
  ..dcCCCCCCcd........
  ..dvvvvvvvvd........
  ...dvjvvvvjd........
  ...dcCCCCCcd........
  ....vvvvvvv.........
  ...vvvvjvvvv........
  .....v..v...........
  ....vvvvvvv.........
  ...vjvvvvj..........
  ..v..v..v...........
  ...vvvvvv...........
  ...vvvjvvv..........
  .....v..v...........
  ...vvvvv............
  ...jv...............
  ..v.....v.......v...
  .vv.................
  v..v.............v..
  ....v...............
`);
const DEFEAT2 = frame(`
  ....................
  ......dCd...........
  .....dvvvd..........
  ....dvvjKvdv........
  ....dCKKvKd.........
  ....dvKvKKd.........
  ....dvKKjKd.........
  ....dCCKsvd.........
  ....j.j.j.j.........
  ....................
  ...j.j.j.j.j........
  ....................
  ..j.j.j.j.j.........
  ....................
  ...j.j.j.j.j........
  ....................
  ....j.j.j.j.........
  ....................
  ...j.j.j.j.j........
  ....................
  ....j.j.j.j.........
  ....................
  ...j.j.j.j..........
  ....................
  ....j.j.j...........
  ....................
  ...j.j.j............
  ....................
  ..j.j...j...........
  ....................
  ...j.............j..
  ....................
`);
const DEFEAT3 = frame(`
  .........v..........
  .......v.j..........
  ......v...v.........
  ....v....v..........
  .......j.....v......
  ...........v........
  ..v.................
  .....v.......j......
  ........v...........
  ....................
  ...v......j.........
  ...............v....
  ......v.....v.......
  ....................
  .........j..........
  ..v...........j.....
  ...........j........
  ....v...............
  .......v........v...
  ....................
  .v..................
  ..........v.........
  ......v.............
  .............v......
  ....................
  ....................
  ...v................
  ....................
  ....................
  ....................
  ....................
  ....................
`);
const HOP0 = frame(`
  ....................
  ......dCd...........
  .....dCCCd..........
  ....dCCKKCd.........
  ....dCKKKKd.........
  ....dCKvKKd.........
  ....dCKKKKd.........
  ....dCCKscd.........
  ...dcCCCccd.........
  ...dcCCCCcd.........
  ..dcCCCCCCcd........
  ..dcCCCCCCcd........
  ..dcCCCCCCcd........
  ..dcCCCCCCcd........
  ..dcCCCCCCcd........
  ...dcCCCCCcd........
  ...dcCCCCCcdb.......
  ...dcCCCCCcd.B......
  ...dcCCCCccd..B.....
  ...dcCCCCcd....B....
  ...dcCCCCcd....B....
  ...dcCCCccd...B.....
  ..dcCCCCccd..b......
  ..dcCCCCcd..........
  ...dcCCCcd..........
  ...dcCCccd..........
  ..vdccCcd...........
  ..dccd.dd...........
  ..ddd...v.......v...
  .vcd.d....v.........
  v..dd..d.........v..
  ....v.d.............
`);
const HOP1 = frame(`
  .....dCCCd..........
  ....dCCKKCd.........
  ....dCKKKKd.........
  ....dCKVKKd.........
  ....dCKKKKd.........
  ....dCCKscd.........
  ...dcCCCccd.........
  ...dcCCCCcd.........
  ..dcCCCCCCcd........
  ..dcCCCCCCcdb.......
  ..dcCCCCCCcd.B......
  ..dcCCCCCCcd..B.....
  ..dcCCCCCCcd...B....
  ...dcCCCCCcd...B....
  ...dcCCCCCcd..B.....
  ...dcCCCCCcd.b......
  ...dcCCCCccd........
  ...dcCCCCcd.........
  ...dcCCCCcd.........
  ..cdcCCCccdc........
  .cdcCCCCccd.d.......
  ..dcCCCCcd..........
  ...dcCCCcd..........
  ..vdcCCccd..........
  ...dccCcd......v....
  ..dccd.dd.v.........
  ..dcd.d.v...........
  .vcd.d..............
  v..d...d.........v..
  ....d...............
  ........d...v.......
  ......d.............
`);

export const VEILED_ARCHER_KEY = "veiled-archer";

export const VEILED_ARCHER_SPRITE: SpriteDef = {
  key: VEILED_ARCHER_KEY,
  w: 20,
  h: 32,
  frames: [IDLE0, IDLE1, AIM, RELEASE, BACKSTEP, VOLLEY0, VOLLEY1, VULN0, VULN1, FLINCH, VANISH0, VANISH1, DEFEAT0, DEFEAT1, DEFEAT2, DEFEAT3, HOP0, HOP1],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 3, repeat: -1 },
    { key: "move", frames: [16, 17], frameRate: 8, repeat: -1 },
    { key: "hop", frames: [16, 17], frameRate: 9, repeat: 0 },
    { key: "aim", frames: [2], frameRate: 1, repeat: 0 },
    { key: "release", frames: [3], frameRate: 1, repeat: 0 },
    { key: "backstep", frames: [4], frameRate: 1, repeat: 0 },
    { key: "volley", frames: [5, 6], frameRate: 7, repeat: -1 },
    { key: "vulnerable", frames: [7, 8], frameRate: 4, repeat: -1 },
    { key: "hurt", frames: [9], frameRate: 1, repeat: 0 },
    { key: "vanish", frames: [10, 11], frameRate: 10, repeat: 0 },
    { key: "defeat", frames: [12, 13, 14, 15], frameRate: 6, repeat: 0 },
  ],
};

const VA_ARROW_0 = frame(`
  ..........B.
  kkCWWWWWCBBB
  kkCWWWWWCBBB
  ..........B.
`);
export const VA_ARROW_SPRITE: SpriteDef = {
  key: "va-arrow",
  w: 12,
  h: 4,
  frames: [VA_ARROW_0],
};

const VA_GLOW_ARROW_0 = frame(`
  ...vvvvvvjv.
  vUUVVjjVVVjV
  vUUVVjjVVVjV
  ...vvvvvvjv.
`);
export const VA_GLOW_ARROW_SPRITE: SpriteDef = {
  key: "va-glow-arrow",
  w: 12,
  h: 4,
  frames: [VA_GLOW_ARROW_0],
};

const VA_ARROW_PLATFORM_0 = frame(`
  jjjjjjjjjjjj
  VvVvVvVvVvVv
  NbBBBBBBBBbN
  .NbBBBBBBbN.
  ..NvUUUUvN..
  ...N....N...
`);
export const VA_ARROW_PLATFORM_SPRITE: SpriteDef = {
  key: "va-arrow-platform",
  w: 12,
  h: 6,
  frames: [VA_ARROW_PLATFORM_0],
};

const VA_TARGET_0 = frame(`
  ............
  ...vvvvvv...
  ..v......v..
  ..v..vv..v..
  ...v....v...
  ....vvvv....
`);
const VA_TARGET_1 = frame(`
  ...VVVVVV...
  .VVvvvvvvVV.
  Vv..jjjj..vV
  Vv..jjjj..vV
  .VVvvvvvvVV.
  ...VVVVVV...
`);
export const VA_TARGET_SPRITE: SpriteDef = {
  key: "va-target",
  w: 12,
  h: 6,
  frames: [VA_TARGET_0, VA_TARGET_1],
  anims: [{ key: "pulse", frames: [0, 1], frameRate: 3, repeat: -1 }],
};

export const VEILED_ARCHER_SPRITES: SpriteDef[] = [
  VEILED_ARCHER_SPRITE, VA_ARROW_SPRITE, VA_GLOW_ARROW_SPRITE, VA_ARROW_PLATFORM_SPRITE, VA_TARGET_SPRITE,
];
