import { frame } from "../grid";
import type { SpriteDef } from "../textures";

// Real-time rework boss sprites (amendment §4 "bosses2.ts"). The six real bosses
// land in their own tasks (35–45); Task 32 seeds this file with the debug-arena
// TRAINING DUMMY — a readable 24×32 wooden training post: a burlap-sack head
// with a painted face, a crossbeam, a bullseye torso on a stake + base. Original
// art, palette chars only (archive-sepia wood P/p, burlap C/c, red target R/r,
// dark rope/outline K/k, crack D/d).

const DUMMY_IDLE_0 = frame(`
  ........................
  .........kKKKk..........
  .......KCCCCCCK.........
  ......KCCCCCCCCK........
  ......KCcCCCCcCK........
  ......KCCRCCRCCK........
  ......KCcCCCCcCK........
  ......KCCCrrCCCK........
  .......KCCCCCCK.........
  ........KCCCCK..........
  .........kKKk...........
  ........pPPPPPPp........
  ..pPPPPPPPPPPPPPPPPPPp..
  ..pPPPPPPPPPPPPPPPPPPp..
  ........pPPPPPPp........
  ........pPRRRRPp........
  ........pPRccRPp........
  ........pPRccRPp........
  ........pPRRRRPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ..........pPPp..........
  ..........pPPp..........
  ..........pPPp..........
  ........kkkKKkkk........
  .......kKKKKKKKKk.......
  ........................
  ........................
  ........................
`);

// idle f1: head + neck sway one pixel right (the post wobbles on its stand);
// crossbeam, torso, stake and base stay planted.
const DUMMY_IDLE_1 = frame(`
  ........................
  ..........kKKKk.........
  ........KCCCCCCK........
  .......KCCCCCCCCK.......
  .......KCcCCCCcCK.......
  .......KCCRCCRCCK.......
  .......KCcCCCCcCK.......
  .......KCCCrrCCCK.......
  ........KCCCCCCK........
  .........KCCCCK.........
  ..........kKKk..........
  ........pPPPPPPp........
  ..pPPPPPPPPPPPPPPPPPPp..
  ..pPPPPPPPPPPPPPPPPPPp..
  ........pPPPPPPp........
  ........pPRRRRPp........
  ........pPRccRPp........
  ........pPRccRPp........
  ........pPRRRRPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ..........pPPp..........
  ..........pPPp..........
  ..........pPPp..........
  ........kkkKKkkk........
  .......kKKKKKKKKk.......
  ........................
  ........................
  ........................
`);

// hurt: head + neck recoil one pixel left, red splinter cracks flash on the
// torso (the scene also tints + flashes the sprite on a landed hit).
const DUMMY_HURT_0 = frame(`
  ........................
  ........kKKKk...........
  ......KCCCCCCK..........
  .....KCCCCCCCCK.........
  .....KCcCCCCcCK.........
  .....KCCRCCRCCK.........
  .....KCcCCCCcCK.........
  .....KCCCrrCCCK.........
  ......KCCCCCCK..........
  .......KCCCCK...........
  ........kKKk............
  ........pPPPPPPp........
  ..pPPPPPPPPPPPPPPPPPPp..
  ..pPPPPPPPPPPPPPPPPPPp..
  ........pPPPPPPp........
  ........pPRRRRPp........
  ........pPRccRPp........
  ........pPRccRPp........
  ........pPRRRRPp........
  ........pPPPPPPp........
  ........pPrPPrPp........
  ........pPPPPPPp........
  ........pPPrrPPp........
  ........pPPPPPPp........
  ..........pPPp..........
  ..........pPPp..........
  ..........pPPp..........
  ........kkkKKkkk........
  .......kKKKKKKKKk.......
  ........................
  ........................
  ........................
`);

// defeat: head knocked clean off (a burlap lump on the ground), the post
// riddled with dark cracks, the bullseye blown out to splinters.
const DUMMY_DEFEAT_0 = frame(`
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........pPPPPPPp........
  ..pPPPPPPPPPPPPPPPPPPp..
  ..pPPPPPPPPPPPPPPPPPPp..
  ........pPPPPPPp........
  ........pPdDDdPp........
  ........pDddddDp........
  ........pPdDDdPp........
  ........pPddddPp........
  ........pPPddPPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ........pPPPPPPp........
  ..........pPPp..........
  ..........pPPp..........
  ..........pPPp..........
  ........kkkKKkkk........
  .......kKKKKKKKKk.......
  ....kCCk................
  ....kCCk................
  ........................
`);

export const TRAINING_DUMMY_KEY = "training-dummy";

export const TRAINING_DUMMY_SPRITE: SpriteDef = {
  key: TRAINING_DUMMY_KEY,
  w: 24,
  h: 32,
  frames: [DUMMY_IDLE_0, DUMMY_IDLE_1, DUMMY_HURT_0, DUMMY_DEFEAT_0],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 2, repeat: -1 },
    { key: "hurt", frames: [2], frameRate: 1, repeat: 0 },
    { key: "defeat", frames: [3], frameRate: 1, repeat: 0 },
  ],
};

/** Every real-time boss sprite authored so far. Later boss tasks push their
 *  sprites here so the arena can register them by RtBossId. Big kits live in
 *  sibling bosses2-*.ts modules; this file is the registry barrel. */
import { BROKEN_KING_ALL } from "./bosses2-brokenKing";
import { HOLLOW_GIANT_SPRITES } from "./bosses2-hollowGiant";
import { ONE_EYED_DEALER_KIT } from "./bosses2-dealer";
import { SCYTHEBOUND_SPRITES, SCYTHE_PROJECTILE_SPRITES } from "./bosses2-scythebound";
import { VEILED_ARCHER_SPRITES } from "./bosses2-archer";
import { RIFT_SWORDSMAN_SPRITE } from "./bosses2-swordsman";
import { DEVIL_KING_SPRITE } from "./bosses2-devilKing";
export {
  BROKEN_KING_SPRITES,
  BROKEN_KING_SHOCKWAVE,
  BROKEN_KING_BLADE_ARC,
} from "./bosses2-brokenKing";
export {
  HOLLOW_GIANT_TORSO,
  HOLLOW_GIANT_HAND,
  HOLLOW_GIANT_HEART,
} from "./bosses2-hollowGiant";
export {
  ONE_EYED_DEALER_SPRITES,
  DEALER_MASK_SPRITES,
  DEALER_PARRY_BULLET_SPRITES,
  DEALER_BULLET_SPRITES,
  DEALER_MUZZLE_SPRITES,
} from "./bosses2-dealer";
export { SCYTHEBOUND_SPRITES, SCYTHE_PROJECTILE_SPRITES } from "./bosses2-scythebound";
export {
  VEILED_ARCHER_SPRITE,
  VA_ARROW_SPRITE,
  VA_GLOW_ARROW_SPRITE,
  VA_ARROW_PLATFORM_SPRITE,
  VA_TARGET_SPRITE,
} from "./bosses2-archer";
export { RIFT_SWORDSMAN_SPRITE } from "./bosses2-swordsman";
export { DEVIL_KING_SPRITE } from "./bosses2-devilKing";

export const BOSSES2_SPRITES: SpriteDef[] = [
  TRAINING_DUMMY_SPRITE,
  ...BROKEN_KING_ALL,
  ...HOLLOW_GIANT_SPRITES,
  ...ONE_EYED_DEALER_KIT,
  SCYTHEBOUND_SPRITES,
  SCYTHE_PROJECTILE_SPRITES,
  ...VEILED_ARCHER_SPRITES,
  RIFT_SWORDSMAN_SPRITE,
  DEVIL_KING_SPRITE,
];
