import { frame } from "../grid";
import type { SpriteDef } from "../textures";

const ARCHIVE_KEY = frame(`
  ....YYYY....
  ...YyyyyY...
  ..Yy....yY..
  ..Yy....yY..
  ...YyyyyY...
  ....YYYY....
  .....YY.....
  .....YY.....
  .....YYYY...
  .....YY.....
  .....YYYY...
  .....YY.....
  ............
  ............
  ............
  ............
`);

const CHEST_CLOSED = frame(`
  ........................
  ........................
  ........................
  ........................
  .......yyyyyyyyyy.......
  .....yyYYYYYYYYYYyy.....
  ....yYYyyyyyyyyyyYYy....
  ...yYYyPPPPPPPPPPyYYy...
  ...yYyPPPPPPPPPPPPyYy...
  ...yYPPPPPPPPPPPPPPYy...
  ...yYYYYYYYYYYYYYYYYy...
  ...yYYyyyyYYYYyyyyYYy...
  ...yYyPPPyYYYYyPPPyYy...
  ...yYyPPPyYOOYyPPPyYy...
  ...yYyPPPyYYYYyPPPyYy...
  ...yYyPPPPPPPPPPPPyYy...
  ...yYyPPPPPPPPPPPPyYy...
  ...yYyPPPPPPPPPPPPyYy...
  ...yYYyyyyyyyyyyyyYYy...
  ....yYYYYYYYYYYYYYYy....
  .....yyyyyyyyyyyyyy.....
  ........................
  ........................
  ........................
`);

const CHEST_OPEN = frame(`
  ........................
  ......YYYYYYYYYYYY......
  ....YYyyyyyyyyyyyyYY....
  ...YyyPPPPPPPPPPPPyyY...
  ..YyPPPPPPPPPPPPPPPPyY..
  ..YyPPPPPPPPPPPPPPPPyY..
  ...YyyPPPPPPPPPPPPyyY...
  ....YYyyyyyyyyyyyyYY....
  .....YYYYYYYYYYYYYY.....
  ........................
  ...yYYYYYYYYYYYYYYYYy...
  ...yYYyyyyYYYYyyyyYYy...
  ...yYyPPPyYYYYyPPPyYy...
  ...yYyPPPyYOOYyPPPyYy...
  ...yYyPPPyYYYYyPPPyYy...
  ...yYyPPPPPPPPPPPPyYy...
  ...yYyPPPPPPPPPPPPyYy...
  ...yYyPPPPPPPPPPPPyYy...
  ...yYYyyyyyyyyyyyyYYy...
  ....yYYYYYYYYYYYYYYy....
  .....yyyyyyyyyyyyyy.....
  ........................
  ........................
  ........................
`);

export const ARCHIVE_KEY_SPRITE: SpriteDef = {
  key: "ending-archive-key",
  w: 12,
  h: 16,
  frames: [ARCHIVE_KEY],
};

export const TREASURE_CHEST_SPRITE: SpriteDef = {
  key: "ending-treasure-chest",
  w: 24,
  h: 24,
  frames: [CHEST_CLOSED, CHEST_OPEN],
  anims: [
    { key: "closed", frames: [0], frameRate: 1, repeat: 0 },
    { key: "open", frames: [0, 1], frameRate: 4, repeat: 0 },
  ],
};

export const ENDING_SPRITES: SpriteDef[] = [ARCHIVE_KEY_SPRITE, TREASURE_CHEST_SPRITE];
