import { frame } from "../grid";
import type { SpriteDef } from "../textures";

// World-1-3 "Firewall Factory" enemies. Authored to schema; the permanent
// integrity test (art/grid.test.ts) parses every frame for palette membership,
// size, and per-anim non-duplicate frames.

// --- Brute Force Brute, 24x24 ------------------------------------------------
// A hulking furnace-golem: broad M/m orange chassis over a dark D/k steel frame,
// a heavy D visor band with a single B eye slit, and L molten vents in the belly.
// Two big d fists hang at the sides. charge f0/f1 swap the leg stance; the stun
// frame slumps it with r/R sparks popping off the cracked shell.

const BRUTE_CHARGE_0 = frame(`
  ........................
  .......kMMMMMMMMk.......
  ......kMMMMMMMMMMk......
  .....kMMDDDDDDDDMMk.....
  .....MMDBBBBBBBBDMM.....
  .....MMDBWBBBBWBDMM.....
  .....kMMDDDDDDDDMMk.....
  ....kMMMMMMMMMMMMMMk....
  ...kMMMmMMMMMMMMmMMMk...
  ..dMMMmmMLLLLLLMmmMMMd..
  ..dMMMmmMLLLLLLMmmMMMd..
  ..dMMMMmMMMMMMMMmMMMMd..
  ...kDMMMMMMMMMMMMMMDk...
  ...kDDDDDDDDDDDDDDDDk...
  ....kkDDDDDDDDDDDDkk....
  ....dd..dDDDDDDd..dd....
  ...ddd..dDDDDDDd..ddd...
  ...dCd..DDDDDDDD..dCd...
  ...ddd...DDDDDD...ddd...
  .......kDDDDDDDDk.......
  .......DDDD..DDDD.......
  ......dDDDd..dDDDd......
  ......kkkk....kkkk......
  ........................
`);

const BRUTE_CHARGE_1 = frame(`
  ........................
  .......kMMMMMMMMk.......
  ......kMMMMMMMMMMk......
  .....kMMDDDDDDDDMMk.....
  .....MMDBBBBBBBBDMM.....
  .....MMDBWBBBBWBDMM.....
  .....kMMDDDDDDDDMMk.....
  ....kMMMMMMMMMMMMMMk....
  ...kMMMmMMMMMMMMmMMMk...
  ..dMMMmmMLmMMmLMmmMMMd..
  ..dMMMmmMLmMMmLMmmMMMd..
  ..dMMMMmMMMMMMMMmMMMMd..
  ...kDMMMMMMMMMMMMMMDk...
  ...kDDDDDDDDDDDDDDDDk...
  ...dd.kkDDDDDDDDkk.dd...
  ..ddd..dDDDDDDDDd..ddd..
  ..dCd..dDDDDDDDDd..dCd..
  ..ddd..DDDDDDDDDD..ddd..
  .......DDDDDDDDDD.......
  ......kDDDDkkDDDDk......
  ......DDDD....DDDD......
  .....dDDDd....dDDDd.....
  .....kkkk......kkkk.....
  ........................
`);

const BRUTE_STUN = frame(`
  ........................
  ..r.....................
  ...R..R.................
  .......kMMMMMMMMk...r...
  ......kMMmmmmmmMMk......
  .....kMMDddddddDMMk..R..
  .....MMDdrXXXXrdDMM.....
  .....MMDXXXXXXXXDMM.....
  ....kMMmmMMMMMMmmMMk....
  ...kMMMmMLLrrLLMmMMMk...
  ..dMMMmmMLLrrLLMmmMMMd..
  ..dMMMMmMMMMMMMMmMMMMd..
  ...kDMmMMMMMMMMmMMDk....
  ...kDDDDDDDDDDDDDDDDk...
  ...dd.kkDDDDDDDDkk.dd...
  ..ddd..dDDDDDDDDd..ddd..
  ..dCd..dDDDDDDDDd..dCd..
  .rddd..DDDDDDDDDD..ddr..
  .......DDDDDDDDDD.......
  ......DDDDDDDDDDDD......
  .....dDDDd....dDDDd.....
  ....dDDDd......dDDDd....
  ....kkkk........kkkk....
  ........................
`);

export const BRUTE_SPRITES: SpriteDef = {
  key: "enemy-brute",
  w: 24,
  h: 24,
  frames: [BRUTE_CHARGE_0, BRUTE_CHARGE_1, BRUTE_STUN],
  anims: [
    { key: "charge", frames: [0, 1], frameRate: 6, repeat: -1 },
    { key: "stun", frames: [2], frameRate: 1, repeat: 0 },
  ],
};

// --- Firewall Knight, 24x24 --------------------------------------------------
// An armored sentinel behind a huge D/d tower shield edged in B cyber-blue.
// walk f0/f1 swap the stride; the brace frame plants the shield forward and
// flares the blue rim (the frame shown while its firewall barrier is up).

const KNIGHT_WALK_0 = frame(`
  ........................
  .........kDDDDk.........
  ........kDdddddk........
  ........DdBBBBdD........
  ........DdBWWBdD........
  ........DddddddD........
  .......kDDddddDDk.......
  ...BB..kkDDDDDDkk..BB...
  ..BdDB.kDdddddDk.BDdB...
  ..BdDB.DdddddddD.BDdB...
  ..BdDBkDddDDDDdDkBDdB...
  ..BdDBkDddDkkDdDkBDdB...
  ..BdDBkDddDkkDdDkBDdB...
  ..BdDBkDddDDDDdDkBDdB...
  ..BdDB.DddddddD..BDdB...
  ..BddB.kDddddDk..BddB...
  ..BBBB..kDDDDk...BBBB...
  ...cc...DDddDD...cc.....
  ........kDd..dDk........
  .......Dd....dD.........
  ......dDd....dDd........
  ......Dd......dD........
  ......kk......kk........
  ........................
`);

const KNIGHT_WALK_1 = frame(`
  ........................
  .........kDDDDk.........
  ........kDdddddk........
  ........DdBBBBdD........
  ........DdBWWBdD........
  ........DddddddD........
  .......kDDddddDDk.......
  ...BB..kkDDDDDDkk..BB...
  ..BdDB.kDdddddDk.BDdB...
  ..BdDB.DdddddddD.BDdB...
  ..BdDBkDddDDDDdDkBDdB...
  ..BdDBkDddDkkDdDkBDdB...
  ..BdDBkDddDkkDdDkBDdB...
  ..BdDBkDddDDDDdDkBDdB...
  ..BddB.DddddddD..BddB...
  ..BBBB.kDddddDk..BBBB...
  ...cc...DDddDD...cc.....
  ........kDd..dDk........
  .......dD......Dd.......
  ......dDd......dDd......
  ......Dd........dD......
  .....kk..........kk.....
  .....kk..........kk.....
  ........................
`);

const KNIGHT_BRACE = frame(`
  ........................
  .........kDDDDk.........
  ........kDdddddk........
  ........DdBBBBdD........
  ........DdBWWBdD........
  BB......DddddddD......BB
  BbB....kDDddddDDk....BbB
  BbBB...kkDDDDDDkk...BBbB
  BbbB...kDdddddDk...BbbB.
  BbbB...DdddddddD...BbbB.
  BbbBb.kDddDDDDdDk.bBbbB.
  BbbBb.kDddDkkDdDk.bBbbB.
  BbbBb.kDddDkkDdDk.bBbbB.
  BbbBb.kDddDDDDdDk.bBbbB.
  BbbB...DddddddD....BbbB.
  BbBB...kDddddDk....BBbB.
  BBB.....kDDDDk......BBB.
  ........DDddDD..........
  ........kDd..dDk........
  .......Dd....dD.........
  ......dDd....dDd........
  ......Dd......dD........
  ......kk......kk........
  ........................
`);

export const KNIGHT_SPRITES: SpriteDef = {
  key: "enemy-knight",
  w: 24,
  h: 24,
  frames: [KNIGHT_WALK_0, KNIGHT_WALK_1, KNIGHT_BRACE],
  anims: [
    { key: "walk", frames: [0, 1], frameRate: 4, repeat: -1 },
    { key: "brace", frames: [2], frameRate: 1, repeat: 0 },
  ],
};

// --- Firewall Barrier, 16x32 -------------------------------------------------
// The 16x32 firewall the Knight raises: a wall of orange/red energy (M/R/Y)
// striped with dark grid lines (k), flaring between the two frames.

const BARRIER_0 = frame(`
  MRMRMRMRMRMRMRMR
  RkRkRkRkRkRkRkRk
  MMMMMMMMMMMMMMMM
  MYMYMYMYMYMYMYMY
  RMRMRMRMRMRMRMRM
  kMkMkMkMkMkMkMkM
  MMMMMMMMMMMMMMMM
  RMRMRMRMRMRMRMRM
  MRMRMRMRMRMRMRMR
  RkRkRkRkRkRkRkRk
  MMMMMMMMMMMMMMMM
  MYMYMYMYMYMYMYMY
  RMRMRMRMRMRMRMRM
  kMkMkMkMkMkMkMkM
  MMMMMMMMMMMMMMMM
  RMRMRMRMRMRMRMRM
  MRMRMRMRMRMRMRMR
  RkRkRkRkRkRkRkRk
  MMMMMMMMMMMMMMMM
  MYMYMYMYMYMYMYMY
  RMRMRMRMRMRMRMRM
  kMkMkMkMkMkMkMkM
  MMMMMMMMMMMMMMMM
  RMRMRMRMRMRMRMRM
  MRMRMRMRMRMRMRMR
  RkRkRkRkRkRkRkRk
  MMMMMMMMMMMMMMMM
  MYMYMYMYMYMYMYMY
  RMRMRMRMRMRMRMRM
  kMkMkMkMkMkMkMkM
  MMMMMMMMMMMMMMMM
  RMRMRMRMRMRMRMRM
`);

const BARRIER_1 = frame(`
  RkRkRkRkRkRkRkRk
  MRMRMRMRMRMRMRMR
  MYMYMYMYMYMYMYMY
  MMMMMMMMMMMMMMMM
  kMkMkMkMkMkMkMkM
  RMRMRMRMRMRMRMRM
  RMRMRMRMRMRMRMRM
  MMMMMMMMMMMMMMMM
  RkRkRkRkRkRkRkRk
  MRMRMRMRMRMRMRMR
  MYMYMYMYMYMYMYMY
  MMMMMMMMMMMMMMMM
  kMkMkMkMkMkMkMkM
  RMRMRMRMRMRMRMRM
  RMRMRMRMRMRMRMRM
  MMMMMMMMMMMMMMMM
  RkRkRkRkRkRkRkRk
  MRMRMRMRMRMRMRMR
  MYMYMYMYMYMYMYMY
  MMMMMMMMMMMMMMMM
  kMkMkMkMkMkMkMkM
  RMRMRMRMRMRMRMRM
  RMRMRMRMRMRMRMRM
  MMMMMMMMMMMMMMMM
  RkRkRkRkRkRkRkRk
  MRMRMRMRMRMRMRMR
  MYMYMYMYMYMYMYMY
  MMMMMMMMMMMMMMMM
  kMkMkMkMkMkMkMkM
  RMRMRMRMRMRMRMRM
  RMRMRMRMRMRMRMRM
  MMMMMMMMMMMMMMMM
`);

export const KNIGHT_BARRIER_SPRITES: SpriteDef = {
  key: "fx-firewall-barrier",
  w: 16,
  h: 32,
  frames: [BARRIER_0, BARRIER_1],
  anims: [{ key: "flare", frames: [0, 1], frameRate: 8, repeat: -1 }],
};

// --- Rootkit Slime, 16x16 ----------------------------------------------------
// A corrupt green-red blob. blob f0/f1 wobble the body; burrow f0/f1 show it
// sinking into the floor leaving a dark hole. Uses G/g body with R/r corruption
// specks and W eye glints.

const SLIME_BLOB_0 = frame(`
  ................
  ................
  .....gggg.......
  ...ggGGGGgg.....
  ..gGGGGGGGGg....
  ..gGWGGGGWGg....
  .gGGGGGGGGGGg...
  .gGGrGGGGrGGg...
  .gGGGGGGGGGGg...
  .gGGGGrrGGGGg...
  ..gGGGGGGGGg....
  ..gggGGGGggg....
  ...gg.gg.gg.....
  ................
  ................
  ................
`);

const SLIME_BLOB_1 = frame(`
  ................
  ................
  ................
  ....gggggg......
  ..ggGGGGGGgg....
  ..gGWGGGGWGg....
  .gGGGGGGGGGGg...
  .gGrGGGGGGrGg...
  .gGGGGGGGGGGg...
  .gGGGGrrGGGGg...
  .gGGGGGGGGGGg...
  ..gGGGGGGGGg....
  ..ggg.gg.ggg....
  ...g...g..g.....
  ................
  ................
`);

const SLIME_BURROW_0 = frame(`
  ................
  ................
  ................
  ................
  ................
  .....gggg.......
  ...ggGGGGgg.....
  ..gGGrrGGGGg....
  ..gGGGGGGGGg....
  ...gggGGggg.....
  ....kkkkkk......
  ...kKKKKKKk.....
  ..kKKKKKKKKk....
  ................
  ................
  ................
`);

const SLIME_BURROW_1 = frame(`
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ......gg........
  ....ggGGgg......
  ...kkgggkkk.....
  ..kKKKKKKKKk....
  ..kKKKKKKKKk....
  ...kKKKKKKk.....
  ....kkkkkk......
  ................
  ................
`);

export const SLIME_SPRITES: SpriteDef = {
  key: "enemy-slime",
  w: 16,
  h: 16,
  frames: [SLIME_BLOB_0, SLIME_BLOB_1, SLIME_BURROW_0, SLIME_BURROW_1],
  anims: [
    { key: "blob", frames: [0, 1], frameRate: 4, repeat: -1 },
    { key: "burrow", frames: [2, 3], frameRate: 6, repeat: 0 },
  ],
};

// --- Rootkit Slime mini, 8x8 -------------------------------------------------
// The two half-size splits: a tiny R/r-flecked green blob.

const MINI_0 = frame(`
  ........
  ..gggg..
  .gGGGGg.
  .gGrrGg.
  .gGGGGg.
  .ggGGgg.
  ..g..g..
  ........
`);

const MINI_1 = frame(`
  ........
  ..gggg..
  .gGrGGg.
  .gGGGGg.
  .gGGrGg.
  .gggGgg.
  .g...g..
  ........
`);

export const SLIME_MINI_SPRITES: SpriteDef = {
  key: "enemy-slime-mini",
  w: 8,
  h: 8,
  frames: [MINI_0, MINI_1],
  anims: [{ key: "blob", frames: [0, 1], frameRate: 6, repeat: -1 }],
};

export const ENEMIES3_SPRITES: SpriteDef[] = [
  BRUTE_SPRITES,
  KNIGHT_SPRITES,
  KNIGHT_BARRIER_SPRITES,
  SLIME_SPRITES,
  SLIME_MINI_SPRITES,
];
