import { frame } from "../grid";
import type { SpriteDef } from "../textures";

// World-2 enemies, 16x16 each. Authored to schema; a permanent integrity test
// (art/grid.test.ts) parses every frame for palette membership, size, and
// per-anim non-duplicate frames.

// --- Malware Bat: a corrupted cyborg bat -------------------------------------
// Dark leathery body (k/K) with violet membrane wings (v/U) and a single
// glowing red cyborg eye (R) in place of the usual two. Small white fangs
// (W) bare from the jaw. Stray R/r glitch specks read as corruption debris.

// flap f0: wings UP — spread high, tips reaching the top corners, silhouette
// widest in the upper half of the frame.
const FLAP_0 = frame(`
  ......k..k......
  v....kk..kk....v
  .v..kkkkkkkk..v.
  .Uv.KkkRRkkK.vU.
  UvvUKkWkkWkKUvvU
  ..UvUkkkkkkUvU..
  ...U..kkkk..U...
  .....kkkkkk.....
  .....kKkkKk.....
  ......kkkk......
  ......k..k......
  ......K..K......
  .......UU.......
  ................
  ................
  ................
`);

// flap f1: wings DOWN — swept low, tips reaching the bottom corners, mirror
// silhouette of FLAP_0 with wing mass in the lower half instead of the upper.
const FLAP_1 = frame(`
  ......k..k......
  .....kk..kk.....
  ....kkkkkkkk....
  ....KkkRRkkK....
  ....KkWkkWkK....
  .....kkkkkk.....
  ......kkkk......
  ....vkkkkkkv....
  ...Uv.kkkk.vU...
  ..Uvv......vvU..
  UvvU........UvvU
  .Uv..........vU.
  .......KK.......
  ................
  ................
  ................
`);

// dive: wings swept back and pressed tight against the body — a streamlined
// dart plunging straight down, jaw open wide for the strike, glitch specks
// trailing off as corruption debris, body elongated to a pinched tail point.
const DIVE = frame(`
  ..U..........U..
  ..R...k..k......
  ....kkkkkkkk....
  ....KkkRRkkK....
  ....KkWkkWkK....
  .....kkkkkk.....
  ...UvkkkkkkvU...
  ..Uv.kkkkkk.vU..
  .....UkkkkU.....
  ...r..kkkk......
  .......kk.......
  ......U..U......
  .......v........
  ................
  ................
  ................
`);

// squash (death): flattened splat, wings crushed flat to the sides, a couple
// of red glitch specks still popping off the corpse as it dissolves.
const SQUASH = frame(`
  ................
  ................
  ................
  ................
  ................
  ................
  ...R........r...
  .vvvvvvvvvvvvvv.
  .vvvRRvvvvrRvvv.
  .UUUUUUUUUUUUUU.
  .kWkkkkRRkkkkWk.
  .kkkkrRkkrRkkkk.
  ..kkUvv..vvUkk..
  ...vv......vv...
  ................
  ................
`);

export const MALWARE_BAT_SPRITES: SpriteDef = {
  key: "enemy-malware-bat",
  w: 16,
  h: 16,
  frames: [FLAP_0, FLAP_1, DIVE, SQUASH],
  anims: [
    { key: "flap", frames: [0, 1], frameRate: 8, repeat: -1 },
    { key: "dive", frames: [2], frameRate: 1, repeat: 0 },
    { key: "squash", frames: [3], frameRate: 1, repeat: 0 },
  ],
};

export const ENEMIES2_SPRITES: SpriteDef[] = [MALWARE_BAT_SPRITES];
