import { frame, mirrorFrame } from "../grid";
import type { SpriteDef } from "../textures";

// pixel-Abrar, 16x24: dark wavy hair (H/h), black sunglasses band with
// glints (O band, d glints), tan skin (S/s), silver chain (C), black
// tee + cargo pants (K/k with O accents), black sneakers with white
// soles (K/W). IDLE_0 is the canonical reference frame for proportions
// and palette usage; every other frame is authored (or derived) to
// read as the same character.

const IDLE_0 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKKS..
  .SKKKKKKKKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// idle f1: torso rows 10-16 shifted down 1px (head steady, breathing).
// Row10 becomes a repeated neck sliver, rows11-16 = old rows10-15,
// legs (17-23) stay planted.
const IDLE_1 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKKS..
  .SKKKKKKKKKKKS..
  ..kKKKKKKKKKk...
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// run f0: wide stride (legs shifted apart), right hand swings forward,
// left hand swings back 1px.
const RUN_0 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .KKKKKKKKKKKKKS.
  SKKKKKKKKKKKKK..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ..KKk....kKKk...
  ..KKk....kKKk...
  ..KKk....kKKk...
  .kKKk....kKKkk..
  .WWWk....kWWWk..
  KWWW......KWWWk.
  ................
`);

// run f1: crossing/passing stride (legs converge), arms swapped.
const RUN_1 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  SKKKKKKKKKKKKK..
  .KKKKKKKKKKKKKS.
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ....KKkkKKk.....
  ....KKkkKKk.....
  ....KKkkKKk.....
  ...kKKkkKKkk....
  ...WWWkkWWWk....
  ..KWWW..KWWWk...
  ................
`);

// run f2/f3: mirrorFrame() applied to just the leg-row band (17-22),
// per the run-cycle rule — head/torso/arms stay put, legs flip side.
const LEG_ROW_START = 17;
const LEG_ROW_END = 23;

function withMirroredLegs(f: string[]): string[] {
  return [
    ...f.slice(0, LEG_ROW_START),
    ...mirrorFrame(f.slice(LEG_ROW_START, LEG_ROW_END)),
    ...f.slice(LEG_ROW_END),
  ];
}

const RUN_2 = withMirroredLegs(RUN_0);
const RUN_3 = withMirroredLegs(RUN_1);

// jump: legs tucked into a compact blob, arms raised straight up.
const JUMP_0 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  .SOOOOOOOOOOd.S.
  .SOddOOOOddOd.S.
  .ShSSSSSSSSSs.S.
  .S.SSSSssSSs..S.
  .S..sSSSSSs...S.
  ..KKKCCCCKKK.K..
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .KKKKKKKKKKKKK..
  .KKKKKKKKKKKKK..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  .....kKKKKk.....
  .....kKKKKk.....
  ......kKKk......
  ................
  ................
  ................
  ................
`);

// fall: head block shifted up 1px (hair reads lifted, neck stretches
// a sliver), legs splayed wide (split-leg silhouette).
const FALL_0 = frame(`
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKKS..
  .SKKKKKKKKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  .KKk......kKKk..
  .KKk......kKKk..
  .KKk......kKKk..
  kKKk......kKKkk.
  WWWk......kWWWk.
  WWW........KWWWk
  ................
`);

// attack f0: right hand starts to extend, a single spark appears.
const ATK_0 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs...v.
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKK.S.
  .SKKKKKKKKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// attack f1: arm extends further, arc thickens into a diagonal sweep.
const ATK_1 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd..V
  ..hSSSSSSSSSs.V.
  ...SSSSssSSs..v.
  ....sSSSSSs..vV.
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKK..S
  .SKKKKKKKKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// attack f2: full extension, big bright V arc with a U dark accent —
// the impact frame.
const ATK_2 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd..V
  ..OddOOOOddOd.vV
  ..hSSSSSSSSSsvVV
  ...SSSSssSSs.UvV
  ....sSSSSSs.UvV.
  ...KKCCCCKKK.v..
  ..KKKKCCKKKKKU..
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKK..S
  .SKKKKKKKKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// hurt: torso+head recoil 1px right, legs stay planted, mouth forced
// open, red damage flecks flash on the chest.
const HURT_0 = frame(`
  .....HHHHHHHH...
  ....HHHHHHHHHh..
  ...HHhHHHHHHHHh.
  ...HHSSSSSSSSH..
  ...hSSSSSSSSSS..
  ...OOOOOOOOOOd..
  ...OddOOOOddOd..
  ...hSSSSSSSSSs..
  ....SSSSOOSSs...
  .....sSSSSSs....
  ....KKCCCCKKK...
  ...KKKKCCKKKKK..
  ..KKRKKKKKKRKKk.
  ..SKKKKKKKKKKKS.
  ..SKKKRKKKKKKKS.
  ...kKKKKKKKKKk..
  ....KKKKKKKKk...
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// parry f0: forearms cross in front of the chest, a B glint flares
// above the cross.
const PARRY_0 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKBKKKKKKKKk..
  ..KKKSKKKKSKK...
  ..KKKKKSSKKKK...
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// parry f1: pose held, glint flickers to a new spot + a spark flies off.
const PARRY_1 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKKB..
  .KKKKKKKKKKKKk..
  ..KKKSKKBKSKK...
  ..KKKKKSSKKKK...
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// interact f0: right arm pokes a hand out past the silhouette at
// chest height, clearly separated from the torso.
const INT_0 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKkKS
  .SKKKKKKKKKKKS..
  .SKKKKKKKKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// interact f1: arm extends further and rises — a second, higher arm
// segment appears at shoulder height so the reach visibly grows.
const INT_1 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKKKS.
  .KKKKKKKKKKKKkKS
  .SKKKKKKKKKKKS..
  .SKKKKKKKKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// victory f0: both arms up, gold sparkles at the hairline/hand/hip.
const VIC_0 = frame(`
  ..Y.HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS.Y.
  .SOOOOOOOOOOd.S.
  .SOddOOOOddOd.S.
  .ShSSSSSSSSSs.S.
  .S.SSSSssSSs..S.
  .S..sSSSSSs...Sy
  ..KKKCCCCKKK.K..
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .KKKKKKKKKKKKK..
  .KKKKKKKKKKKKK..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// victory f1: arms held, sparkles twinkle to new positions.
const VIC_1 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh.Y.
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ySOOOOOOOOOOd.S.
  .SOddOOOOddOd.S.
  .ShSSSSSSSSSs.S.
  .S.SSSSssSSs..SY
  .S..sSSSSSs...S.
  ..KKKCCCCKKK.K..
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .KKKKKKKKKKKKK..
  .KKKKKKKKKKKKK..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WWWk..kWWWk...
  .KWWW....KWWWk..
  ................
`);

// death f0: ankles/shoes just start to sparkle away.
const DEATH_0 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKKS..
  .SKKKKKKKKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..v.Kv..v.Kv....
  ...Wv....Wv.k...
  ..Wv.....v.Wv...
  ................
`);

// death f1: legs and shoes fully dissolve into scattered V/v particles.
const DEATH_1 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCCCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKKS..
  .SKKKKKKKKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ....Kv..v.Kv....
  ...Kv....Kv.....
  ...v.k..kv.k....
  ..v.Kv..v.Kv....
  ...Wv....Wv.k...
  ..Wv.....v.Wv...
  ................
`);

// death f2: legs are gone entirely, torso now dissolves too — only
// the head stays intact.
const DEATH_2 = frame(`
  ....HHHHHHHH....
  ...HHHHHHHHHh...
  ..HHhHHHHHHHHh..
  ..HHSSSSSSSSH...
  ..hSSSSSSSSSS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...v.Cv.Cv.K....
  ..v.Kv.Cv.Kv....
  .v.Kv.Kv.Kv.Kv..
  ..Kv.Kv.Kv.Kv...
  .Sv.Kv.Kv.Kv.S..
  ...Kv.Kv.Kv.k...
  ...v.Kv.Kv.k....
  ................
  ................
  ................
  ................
  ................
  ................
  ................
`);

// death f3: everything below the head is gone; the head itself
// dissolves into its last scattered V/v motes.
const DEATH_3 = frame(`
  ....v.Hv.Hv.....
  ...v.Hv.Hv.Hv...
  ..v.hv.Hv.Hv.h..
  ...Hv.Sv.Sv.H...
  ..hv.Sv.Sv.Sv...
  ..v.Ov.Ov.Ov....
  ...dv.Ov.dv.d...
  ..hv.Sv.Sv.Sv...
  ....Sv.sv.Sv....
  ....v.Sv.Sv.....
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
`);

export const PLAYER_SPRITES: SpriteDef = {
  key: "player",
  w: 16,
  h: 24,
  frames: [IDLE_0, IDLE_1, RUN_0, RUN_1, RUN_2, RUN_3, JUMP_0, FALL_0,
           ATK_0, ATK_1, ATK_2, HURT_0, PARRY_0, PARRY_1, INT_0, INT_1,
           VIC_0, VIC_1, DEATH_0, DEATH_1, DEATH_2, DEATH_3],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 3, repeat: -1 },
    { key: "run", frames: [2, 3, 4, 5], frameRate: 10, repeat: -1 },
    { key: "jump", frames: [6], frameRate: 1, repeat: -1 },
    { key: "fall", frames: [7], frameRate: 1, repeat: -1 },
    { key: "attack", frames: [8, 9, 10], frameRate: 12, repeat: 0 },
    { key: "hurt", frames: [11], frameRate: 1, repeat: 0 },
    { key: "parry", frames: [12, 13], frameRate: 10, repeat: 0 },
    { key: "interact", frames: [14, 15], frameRate: 6, repeat: 0 },
    { key: "victory", frames: [16, 17], frameRate: 4, repeat: -1 },
    { key: "death", frames: [18, 19, 20, 21], frameRate: 6, repeat: 0 },
  ],
};
