import { frame, mirrorFrame } from "../grid";
import type { SpriteDef } from "../textures";

// pixel-Abrar, 16x24: dark wavy hair (H with h wave streaks), black
// sunglasses band with cyan lens glints (O band, B/d glints), tan skin
// (S with s cheek/jaw shading), silver chain with a W sparkle link, black
// tee with a 2x2 violet v logo (site brand), cargo pants (K/k), black
// sneakers with white soles + a cyan B side tick. IDLE_0 is the canonical
// reference frame for proportions and palette usage; every other frame is
// authored (or derived) to read as the same character.

const IDLE_0 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKvvKKKKS..
  .SKKKKKvvKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// idle f1: torso rows 10-16 shifted down 1px (head steady, breathing).
// Row10 becomes a repeated neck sliver, rows11-16 = old rows10-15,
// legs (17-23) stay planted.
const IDLE_1 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKvvKKKKS..
  .SKKKKKvvKKKKS..
  ..kKKKKKKKKKk...
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// run f0: wide stride (legs shifted apart), right hand swings forward,
// left hand swings back 1px.
const RUN_0 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .KKKKKvvKKKKKKS.
  SKKKKKvvKKKKKK..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ..KKk....kKKk...
  ..KKk....kKKk...
  ..KKk....kKKk...
  .kKKk....kKKkk..
  .WBWk....kWBWk..
  KWWW......KWWWk.
  ................
`);

// run f1: crossing/passing stride (legs converge), arms swapped.
const RUN_1 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  SKKKKKvvKKKKKK..
  .KKKKKvvKKKKKKS.
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ....KKkkKKk.....
  ....KKkkKKk.....
  ....KKkkKKk.....
  ...kKKkkKKkk....
  ...WBWkkWBWk....
  ..KWWW..KWWWk...
  ................
`);

// run f2/f3: mirrorFrame() applied to just the leg-row band (17-22),
// per the run-cycle rule — head/torso/arms stay put, legs flip side.
const LEG_ROW_START = 17;
const LEG_ROW_END = 23;

function withMirroredLegs(f: string[]): string[] {
  return [
    ...f.slice(0, LEG_ROW_START),
    ...mirrorFrame(f.slice(LEG_ROW_START, LEG_ROW_END)),
    ...f.slice(LEG_ROW_END),
  ];
}

const RUN_2 = withMirroredLegs(RUN_0);
const RUN_3 = withMirroredLegs(RUN_1);

// jump: legs tucked into a compact blob, arms raised straight up.
const JUMP_0 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  .SOOOOOOOOOOd.S.
  .SOBdOOOOBdOd.S.
  .ShSSSSSSSSSs.S.
  .S.SSSSssSSs..S.
  .S..sSSSSSs...S.
  ..KKKCWCCKKK.K..
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .KKKKKvvKKKKKK..
  .KKKKKvvKKKKKK..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  .....kKKKKk.....
  .....kKKKKk.....
  ......kKKk......
  ................
  ................
  ................
  ................
`);

// fall: head block shifted up 1px (hair reads lifted, neck stretches
// a sliver), legs splayed wide (split-leg silhouette).
const FALL_0 = frame(`
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKvvKKKKS..
  .SKKKKKvvKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  .KKk......kKKk..
  .KKk......kKKk..
  .KKk......kKKk..
  kKKk......kKKkk.
  WBWk......kWBWk.
  WWW........KWWWk
  ................
`);

// attack f0: right hand starts to extend, a single spark appears.
const ATK_0 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs...v.
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKK.S.
  .SKKKKKvvKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// attack f1: arm extends further, arc thickens into a diagonal sweep.
const ATK_1 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OddOOOOddOd..V
  ..hSSSSSSSSSs.V.
  ...SSSSssSSs..v.
  ....sSSSSSs..vV.
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKK..S
  .SKKKKKvvKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// attack f2: full extension, big bright V arc with a U dark accent —
// the impact frame.
const ATK_2 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd..V
  ..OddOOOOddOd.vV
  ..hSSSSSSSSSsvVV
  ...SSSSssSSs.UvV
  ....sSSSSSs.UvV.
  ...KKCCCCKKK.v..
  ..KKKKCCKKKKKU..
  .KKKKKKKKKKKKk..
  .SKKKKKKKKKKK..S
  .SKKKKKvvKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// hurt: torso+head recoil 1px right, legs stay planted, mouth forced
// open, red damage flecks flash on the chest.
const HURT_0 = frame(`
  .....HHhHHHHH...
  ....HhHHHHhHHh..
  ...HHhHHhHHHHHh.
  ...HHSSSSSSSsH..
  ...hSSSSSSSSsS..
  ...OOOOOOOOOOd..
  ...OBdOOOOBdOd..
  ...hSSSSSSSSSs..
  ....SSSSOOSSs...
  .....sSSSSSs....
  ....KKCWCCKKK...
  ...KKKKCCKKKKK..
  ..KKRKKKKKKRKKk.
  ..SKKKKKvvKKKKS.
  ..SKKKRKKKKKKKS.
  ...kKKKKKKKKKk..
  ....KKKKKKKKk...
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// parry f0: forearms cross in front of the chest, a B glint flares
// above the cross.
const PARRY_0 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKBKKKKKKKKk..
  ..KKKSKKKKSKK...
  ..KKKKKSSKKKK...
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// parry f1: pose held, glint flickers to a new spot + a spark flies off.
const PARRY_1 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKKB..
  .KKKKKKKKKKKKk..
  ..KKKSKKBKSKK...
  ..KKKKKSSKKKK...
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// interact f0: right arm pokes a hand out past the silhouette at
// chest height, clearly separated from the torso.
const INT_0 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKkKS
  .SKKKKKvvKKKKS..
  .SKKKKKvvKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// interact f1: arm extends further and rises — a second, higher arm
// segment appears at shoulder height so the reach visibly grows.
const INT_1 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKKKS.
  .KKKKKKKKKKKKkKS
  .SKKKKKvvKKKKS..
  .SKKKKKvvKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// victory f0: both arms up, gold sparkles at the hairline/hand/hip.
const VIC_0 = frame(`
  ..Y.HHHHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSSS.Y.
  .SOOOOOOOOOOd.S.
  .SOBdOOOOBdOd.S.
  .ShSSSSSSSSSs.S.
  .S.SSSSssSSs..S.
  .S..sSSSSSs...Sy
  ..KKKCWCCKKK.K..
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .KKKKKvvKKKKKK..
  .KKKKKvvKKKKKK..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// victory f1: arms held, sparkles twinkle to new positions.
const VIC_1 = frame(`
  ....HHhHHHHH....
  ...HHHHHHHHHh.Y.
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ySOOOOOOOOOOd.S.
  .SOBdOOOOBdOd.S.
  .ShSSSSSSSSSs.S.
  .S.SSSSssSSs..SY
  .S..sSSSSSs...S.
  ..KKKCWCCKKK.K..
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .KKKKKvvKKKKKK..
  .KKKKKvvKKKKKK..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..kKKk..kKKkk...
  ..WBWk..kWBWk...
  .KWWW....KWWWk..
  ................
`);

// death f0: ankles/shoes just start to sparkle away.
const DEATH_0 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKvvKKKKS..
  .SKKKKKvvKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ...KKk..kKKk....
  ..v.Kv..v.Kv....
  ...Wv....Wv.k...
  ..Wv.....v.Wv...
  ................
`);

// death f1: legs and shoes fully dissolve into scattered V/v particles.
const DEATH_1 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...KKCWCCKKK....
  ..KKKKCCKKKKK...
  .KKKKKKKKKKKKk..
  .SKKKKKvvKKKKS..
  .SKKKKKvvKKKKS..
  ..kKKKKKKKKKk...
  ...KKKKKKKKk....
  ....Kv..v.Kv....
  ...Kv....Kv.....
  ...v.k..kv.k....
  ..v.Kv..v.Kv....
  ...Wv....Wv.k...
  ..Wv.....v.Wv...
  ................
`);

// death f2: legs are gone entirely, torso now dissolves too — only
// the head stays intact.
const DEATH_2 = frame(`
  ....HHhHHHHH....
  ...HhHHHHhHHh...
  ..HHhHHhHHHHHh..
  ..HHSSSSSSSsH...
  ..hSSSSSSSSsS...
  ..OOOOOOOOOOd...
  ..OBdOOOOBdOd...
  ..hSSSSSSSSSs...
  ...SSSSssSSs....
  ....sSSSSSs.....
  ...v.Cv.Cv.K....
  ..v.Kv.Cv.Kv....
  .v.Kv.Kv.Kv.Kv..
  ..Kv.Kv.Kv.Kv...
  .Sv.Kv.Kv.Kv.S..
  ...Kv.Kv.Kv.k...
  ...v.Kv.Kv.k....
  ................
  ................
  ................
  ................
  ................
  ................
  ................
`);

// death f3: everything below the head is gone; the head itself
// dissolves into its last scattered V/v motes.
const DEATH_3 = frame(`
  ....v.Hv.Hv.....
  ...v.Hv.Hv.Hv...
  ..v.hv.Hv.Hv.h..
  ...Hv.Sv.Sv.H...
  ..hv.Sv.Sv.Sv...
  ..v.Ov.Ov.Ov....
  ...dv.Ov.dv.d...
  ..hv.Sv.Sv.Sv...
  ....Sv.sv.Sv....
  ....v.Sv.Sv.....
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
`);

function swordCanvas(
  blade: readonly [number, number][],
  accents: readonly [number, number, string][] = [],
): string[] {
  const rows = Array.from({ length: 32 }, () => Array<string>(32).fill("."));
  for (const [x, y] of blade) {
    if (rows[y]?.[x] !== undefined) rows[y][x] = "W";
    if (rows[y]?.[x + 1] !== undefined) rows[y][x + 1] = "C";
  }
  for (const [x, y, color] of accents) {
    if (rows[y]?.[x] !== undefined) rows[y][x] = color;
  }
  return rows.map((row) => row.join(""));
}

function linePoints(x0: number, y0: number, x1: number, y1: number): [number, number][] {
  const length = Math.max(Math.abs(x1 - x0), Math.abs(y1 - y0));
  return Array.from({ length: length + 1 }, (_, index) => {
    const t = length === 0 ? 0 : index / length;
    return [Math.round(x0 + (x1 - x0) * t), Math.round(y0 + (y1 - y0) * t)];
  });
}

const SWORD_IDLE = swordCanvas(linePoints(12, 23, 25, 8), [[11, 24, "B"], [10, 25, "V"], [24, 8, "V"]]);
const SWORD_SWING_0 = swordCanvas(linePoints(11, 21, 25, 5), [[10, 22, "B"], [26, 5, "V"]]);
const SWORD_SWING_1 = swordCanvas(linePoints(10, 15, 29, 13), [[9, 16, "B"], [29, 12, "V"]]);
const SWORD_SWING_2 = swordCanvas(linePoints(11, 10, 27, 27), [[10, 9, "B"], [28, 28, "V"]]);
const SWORD_RUSH = swordCanvas(linePoints(8, 16, 31, 16), [[7, 16, "B"], [29, 15, "V"], [30, 17, "V"]]);
const SWORD_WAVE = swordCanvas(
  [[22, 5], [25, 7], [27, 10], [28, 13], [28, 16], [27, 19], [25, 22], [22, 24], [19, 25]],
  [[23, 5, "B"], [28, 15, "V"], [20, 25, "V"]],
);

export const PLAYER_SPRITES: SpriteDef = {
  key: "player",
  w: 16,
  h: 24,
  frames: [IDLE_0, IDLE_1, RUN_0, RUN_1, RUN_2, RUN_3, JUMP_0, FALL_0,
           ATK_0, ATK_1, ATK_2, HURT_0, PARRY_0, PARRY_1, INT_0, INT_1,
           VIC_0, VIC_1, DEATH_0, DEATH_1, DEATH_2, DEATH_3],
  anims: [
    { key: "idle", frames: [0, 1], frameRate: 3, repeat: -1 },
    { key: "run", frames: [2, 3, 4, 5], frameRate: 10, repeat: -1 },
    { key: "jump", frames: [6], frameRate: 1, repeat: -1 },
    { key: "fall", frames: [7], frameRate: 1, repeat: -1 },
    { key: "attack", frames: [8, 9, 10], frameRate: 12, repeat: 0 },
    { key: "hurt", frames: [11], frameRate: 1, repeat: 0 },
    { key: "parry", frames: [12, 13], frameRate: 10, repeat: 0 },
    { key: "interact", frames: [14, 15], frameRate: 6, repeat: 0 },
    { key: "victory", frames: [16, 17], frameRate: 4, repeat: -1 },
    { key: "death", frames: [18, 19, 20, 21], frameRate: 6, repeat: 0 },
  ],
};

/** A separate 32×32 layer makes Abrar's blade read as a real weapon without
 * changing the compact collision/player sheet. PlatformLevelScene keeps this
 * sprite attached to the character and switches rows with combat actions. */
export const PLAYER_SWORD_SPRITES: SpriteDef = {
  key: "player-sword",
  w: 32,
  h: 32,
  frames: [SWORD_IDLE, SWORD_SWING_0, SWORD_SWING_1, SWORD_SWING_2, SWORD_RUSH, SWORD_WAVE],
  anims: [
    { key: "idle", frames: [0], frameRate: 1, repeat: -1 },
    { key: "swing", frames: [1, 2, 3], frameRate: 15, repeat: 0 },
    { key: "rush", frames: [4], frameRate: 1, repeat: -1 },
    { key: "wave", frames: [5], frameRate: 1, repeat: 0 },
  ],
};
