import { describe, it, expect } from "vitest";
import { parseLevel } from "./parse";
import { LEVELS } from "./index";
import type { LevelDefinition, EnemyKind } from "./types";
import type { LevelId } from "../ids";

const mini = (map: string): LevelDefinition => ({
  id: "1-1", name: "t", theme: "fields", bossId: "glitch-toad",
  music: "level-1", map, introDialogueId: null, fragmentDialogueId: null,
});

const countChar = (map: string, ch: string): number =>
  [...map].filter((c) => c === ch).length;

describe("parseLevel", () => {
  it("classifies tiles and finds markers", () => {
    const lvl = parseLevel(mini(["P..b..M..D", "##==^..###"].join("\n")));
    expect(lvl.widthTiles).toBe(10);
    expect(lvl.heightTiles).toBe(2);
    expect(lvl.playerStart).toEqual({ tx: 0, ty: 0 });
    expect(lvl.bossDoor).toEqual({ tx: 9, ty: 0 });
    expect(lvl.fragment).toEqual({ tx: 6, ty: 0 });
    expect(lvl.solids[1][0]).toBe(true);
    expect(lvl.oneWays[1][2]).toBe(true);
    expect(lvl.hazards[1][4]).toBe(true);
    expect(lvl.spawns).toEqual([{ kind: "bugling", at: { tx: 3, ty: 0 } }]);
  });

  it("classifies fake platforms (F) and boats (o) into their own lists", () => {
    const lvl = parseLevel(mini(["P..F..o..D", "##########"].join("\n")));
    expect(lvl.fakes).toEqual([{ tx: 3, ty: 0 }]);
    expect(lvl.boats).toEqual([{ tx: 6, ty: 0 }]);
    // Neither is a solid/one-way/hazard cell — they are spawn markers, not tiles.
    expect(lvl.solids[0][3]).toBe(false);
    expect(lvl.oneWays[0][3]).toBe(false);
  });

  it("gives every parsed level empty fakes/boats when it has none", () => {
    const lvl = parseLevel(mini(["P....D", "######"].join("\n")));
    expect(lvl.fakes).toEqual([]);
    expect(lvl.boats).toEqual([]);
  });

  it("classifies rotator pivots (@) into their own list without touching tile layers", () => {
    const lvl = parseLevel(mini(["P..@..D", "#######"].join("\n")));
    expect(lvl.rotators).toEqual([{ tx: 3, ty: 0 }]);
    // A pivot is a marker, not a tile: the 3 orbiting arm cells are generated by
    // the scene, so the pivot cell itself is neither solid nor one-way nor hazard.
    expect(lvl.solids[0][3]).toBe(false);
    expect(lvl.oneWays[0][3]).toBe(false);
    expect(lvl.hazards[0][3]).toBe(false);
  });

  it("gives every parsed level an empty rotators list when it has none", () => {
    const lvl = parseLevel(mini(["P....D", "######"].join("\n")));
    expect(lvl.rotators).toEqual([]);
  });

  it("classifies conveyors (< left / > right), timed gates (G), lasers (L)", () => {
    const lvl = parseLevel(mini(["P.<.>.G.L.D", "###########"].join("\n")));
    expect(lvl.conveyors).toEqual([
      { at: { tx: 2, ty: 0 }, dir: -1 },
      { at: { tx: 4, ty: 0 }, dir: 1 },
    ]);
    expect(lvl.gates).toEqual([{ tx: 6, ty: 0 }]);
    expect(lvl.lasers).toEqual([{ tx: 8, ty: 0 }]);
    // Conveyor cells double as solids (floor you stand on); gates/lasers do not.
    expect(lvl.solids[0][2]).toBe(true);
    expect(lvl.solids[0][4]).toBe(true);
    expect(lvl.solids[0][6]).toBe(false);
    expect(lvl.solids[0][8]).toBe(false);
  });

  it("gives every parsed level empty conveyors/gates/lasers when it has none", () => {
    const lvl = parseLevel(mini(["P....D", "######"].join("\n")));
    expect(lvl.conveyors).toEqual([]);
    expect(lvl.gates).toEqual([]);
    expect(lvl.lasers).toEqual([]);
  });

  it("throws when P or D is missing", () => {
    expect(() => parseLevel(mini("...\n###"))).toThrow(/player start/i);
    expect(() => parseLevel(mini("P..\n###"))).toThrow(/boss door/i);
  });

  it("throws on ragged maps", () => {
    expect(() => parseLevel(mini("P.D\n##"))).toThrow(/ragged/i);
  });
});

describe("authored levels", () => {
  it("every registered level parses", () => {
    for (const def of Object.values(LEVELS)) expect(() => parseLevel(def!)).not.toThrow();
  });
});

describe("level content requirements", () => {
  const CONTENT: Partial<Record<LevelId, {
    rowLen: number; checkpointsMin: number; fragments: number;
    spawnMins: Partial<Record<EnemyKind, number>>;
    hazards: boolean; oneWays: boolean;
  }>> = {
    "1-1": { rowLen: 160, checkpointsMin: 2, fragments: 1,
             spawnMins: { bugling: 4, phishling: 2 }, hazards: true, oneWays: true },
    "1-2": { rowLen: 170, checkpointsMin: 2, fragments: 1,
             spawnMins: { bugling: 3, phishling: 2, "malware-bat": 3 }, hazards: true, oneWays: true },
    "1-3": { rowLen: 180, checkpointsMin: 2, fragments: 1,
             spawnMins: { brute: 2, "firewall-knight": 2, "rootkit-slime": 2 }, hazards: true, oneWays: true },
    "1-4": { rowLen: 160, checkpointsMin: 2, fragments: 1,
             spawnMins: { bugling: 3, "malware-bat": 2, "rootkit-slime": 3 }, hazards: true, oneWays: true },
  };

  // Enemy kinds that fly (no gravity): exempt from the ground-standability check
  // below — they spawn over water/gaps by design (Task 18 malware bats hover
  // over the boat crossings, where the only tile beneath them is the water
  // hazard). Grounded walkers/floaters still must land on solid/one-way ground.
  const FLYING_KINDS = new Set<EnemyKind>(["malware-bat"]);

  for (const [id, expected] of Object.entries(CONTENT) as [
    LevelId,
    NonNullable<(typeof CONTENT)[LevelId]>,
  ][]) {
    describe(id, () => {
      const def = LEVELS[id]!;
      const rawLines = def.map.split("\n");

      it("has no ragged rows", () => {
        for (const line of rawLines) expect(line.length).toBe(expected.rowLen);
      });

      it("has exactly one player start (P)", () => {
        expect(countChar(def.map, "P")).toBe(1);
      });

      it("has exactly one boss door (D)", () => {
        expect(countChar(def.map, "D")).toBe(1);
      });

      it("has exactly the expected number of fragments (M), catching duplicates", () => {
        expect(countChar(def.map, "M")).toBe(expected.fragments);
      });

      it("has no empty line sandwiched between two non-empty lines", () => {
        for (let i = 1; i < rawLines.length - 1; i++) {
          if (rawLines[i].length === 0) {
            expect(rawLines[i - 1].length === 0 || rawLines[i + 1].length === 0).toBe(true);
          }
        }
      });

      it("parses with at least the minimum checkpoints", () => {
        const lvl = parseLevel(def);
        expect(lvl.checkpoints.length).toBeGreaterThanOrEqual(expected.checkpointsMin);
      });

      it("parses with a fragment iff the level expects one", () => {
        const lvl = parseLevel(def);
        expect(lvl.fragment !== null).toBe(expected.fragments > 0);
      });

      it("meets the minimum spawn count for every required enemy kind", () => {
        const lvl = parseLevel(def);
        for (const [kind, min] of Object.entries(expected.spawnMins) as [EnemyKind, number][]) {
          const count = lvl.spawns.filter((s) => s.kind === kind).length;
          expect(count).toBeGreaterThanOrEqual(min);
        }
      });

      it("has hazards/one-ways present iff expected", () => {
        const lvl = parseLevel(def);
        const anyHazard = lvl.hazards.some((row) => row.some(Boolean));
        const anyOneWay = lvl.oneWays.some((row) => row.some(Boolean));
        expect(anyHazard).toBe(expected.hazards);
        expect(anyOneWay).toBe(expected.oneWays);
      });

      it("every spawn has standable ground beneath it (solid or one-way, never a hazard or open air)", () => {
        const lvl = parseLevel(def);
        for (const spawn of lvl.spawns) {
          if (FLYING_KINDS.has(spawn.kind)) continue; // flyers hover over gaps by design
          const { tx, ty } = spawn.at;
          let landedTy: number | null = null;
          for (let y = ty + 1; y < lvl.heightTiles; y++) {
            if (lvl.solids[y][tx] || lvl.oneWays[y][tx] || lvl.hazards[y][tx]) {
              landedTy = y;
              break;
            }
          }
          expect(
            landedTy,
            `${id} spawn "${spawn.kind}" at (${tx},${ty}) falls out of the map with nothing solid beneath it`,
          ).not.toBeNull();
          if (landedTy !== null) {
            expect(
              lvl.solids[landedTy][tx] || lvl.oneWays[landedTy][tx],
              `${id} spawn "${spawn.kind}" at (${tx},${ty}) lands on a hazard at row ${landedTy}`,
            ).toBe(true);
          }
        }
      });
    });
  }

  it("parser maps every enemy char, the checkpoint marker, and fake/boat spawns", () => {
    const lvl = parseLevel(mini("PbpmBksCFoD"));
    expect(lvl.spawns).toEqual([
      { kind: "bugling", at: { tx: 1, ty: 0 } },
      { kind: "phishling", at: { tx: 2, ty: 0 } },
      { kind: "malware-bat", at: { tx: 3, ty: 0 } },
      { kind: "brute", at: { tx: 4, ty: 0 } },
      { kind: "firewall-knight", at: { tx: 5, ty: 0 } },
      { kind: "rootkit-slime", at: { tx: 6, ty: 0 } },
    ]);
    expect(lvl.checkpoints).toEqual([{ tx: 7, ty: 0 }]);
    expect(lvl.fakes).toEqual([{ tx: 8, ty: 0 }]);
    expect(lvl.boats).toEqual([{ tx: 9, ty: 0 }]);
  });

  it("throws on an unknown map char", () => {
    expect(() => parseLevel(mini("P?D"))).toThrow(/unknown map char/i);
  });
});
