import type { LevelId, BossId, TrackId } from "../ids";

/** A rising-corruption segment (Task 21 castle): between tile columns
 *  `fromTx`..`toTx` a red tide rises `12px/s` while the player is inside the
 *  span, capping at `ceilTy` and resetting to the top of `floorTy` whenever the
 *  player leaves the span or respawns. Hardcoded per-level (only the castle
 *  authors one) rather than parsed from the map, since it is a scene-driven
 *  region, not a tile. */
export interface CorruptionSegment {
  /** Left column of the shaft (inclusive). */
  fromTx: number;
  /** Right column of the shaft (inclusive). */
  toTx: number;
  /** Tile row whose TOP the tide surface starts at (and resets to). */
  floorTy: number;
  /** Tile row the rising tide surface caps at (won't climb past its top). */
  ceilTy: number;
}

/** A purely-decorative sprite placed at a tile cell (Task 21 castle chains,
 *  banners, demonic statues). No collision, no gameplay — the scene renders
 *  these behind the actors when a level authors them. */
export interface DecorMark {
  kind: "chain" | "banner" | "statue";
  tx: number;
  ty: number;
}

export interface LevelDefinition {
  id: LevelId;
  name: string;
  theme: "fields" | "harbor" | "factory" | "archive" | "castle";
  bossId: BossId;
  music: TrackId;
  map: string;
  introDialogueId: string | null;
  fragmentDialogueId: string | null;
  /** Rising-corruption shaft region (castle only; see CorruptionSegment). */
  corruption?: CorruptionSegment;
  /** Decorative sprites the scene renders behind actors (castle only). */
  decor?: DecorMark[];
}

export interface Pt {
  tx: number;
  ty: number;
}

/** A conveyor belt cell (legend `<` / `>`). The cell is also a solid the entity
 *  stands on; `dir` is the horizontal push direction (-1 left, +1 right). */
export interface Conveyor {
  at: Pt;
  dir: 1 | -1;
}

export type EnemyKind =
  | "bugling"
  | "phishling"
  | "malware-bat"
  | "brute"
  | "firewall-knight"
  | "rootkit-slime";

export interface ParsedLevel {
  widthTiles: number;
  heightTiles: number;
  solids: boolean[][];
  oneWays: boolean[][];
  hazards: boolean[][];
  playerStart: Pt;
  checkpoints: Pt[];
  fragment: Pt | null;
  bossDoor: Pt;
  spawns: { kind: EnemyKind; at: Pt }[];
  /** Fake-platform spawn cells (legend `F`): 16x8 one-way look-alikes that
   *  flicker near the player and vanish once stood on (see PlatformLevelScene). */
  fakes: Pt[];
  /** Boat spawn cells (legend `o`): 32x16 moving platforms that tween ±64px
   *  horizontally and carry a rider (see PlatformLevelScene). */
  boats: Pt[];
  /** Conveyor cells (legend `<` / `>`): solid floor that adds ±60px/s to a
   *  grounded entity's x-velocity in `dir` (see PlatformLevelScene, factory). */
  conveyors: Conveyor[];
  /** Timed-gate cells (legend `G`): a 16x32 barrier (this cell + the one below)
   *  that cycles solid/open on a fixed period (see PlatformLevelScene). */
  gates: Pt[];
  /** Laser-emitter cells (legend `L`): a floor device firing an upward beam
   *  that cycles on/off; attacking the emitter disables it (PlatformLevelScene). */
  lasers: Pt[];
  /** Rotator-pivot cells (legend `@`): a hub around which the 3 tiles to its
   *  right orbit in 90° steps every 2s (see PlatformLevelScene, archive). The
   *  3 one-way arm platforms are generated by the scene from the pivot, not
   *  authored — the pivot cell itself is a bare marker (no tile layer set). */
  rotators: Pt[];
  /** Fireball-fountain cells (legend `!`): a lava spout that launches an
   *  arcing, gravity-affected fireball every 2.2s (Task 21 castle). A marker,
   *  not a tile — the cell is neither solid/one-way/hazard; the scene spawns
   *  pooled fireballs from it. */
  fountains: Pt[];
  /** Collapsing-bridge cells (legend `~`): a bridge tile that shakes 400ms
   *  after the FIRST touch then falls (body disabled, sprite tweens down +
   *  fades) and respawns 3s later (Task 21 castle). A marker whose one-way
   *  collision body + sprite are built by the scene, not a plain solid tile. */
  bridges: Pt[];
}
